### ISSUE TITLE
Neomutt segfaults on `mutt.set('realname', …)`

### ISSUE THREAD

**Issue by fgrsnau** [neomutt/neomutt#1096]
**Expected behavior**
Enter `:lua mutt.set('realname', 'Test')` should lead to `set ?realname` outputting `Test`.

**Actual behavior**
Neomutt segfaults.

**Steps to reproduce**
The above command segfault’s every time for me. It is part of my Lua code for switching between multiple accounts.

It is not triggered by, e.g. `:lua mutt.set('signature', …)`.

**Used program versions**
I use Arch Linux' neomutt-20180223-1 package. I confirmed that 079cbcb8a94db6b88f7b5c1ea899623da0e302da is still affected.

**Operating System and its version**
Arch Linux

**Stacktrace**
```
:lua mutt.set('realname', 'Test')
Thread 1 "neomutt" received signal SIGSEGV, Segmentation fault.
0x000055555564247b in mutt_str_strdup (s=0x550074736554 <error: Cannot access memory at address 0x550074736554>) at mutt/string.c:328
328	  if (!s || !*s)
(gdb) bt
#0  0x000055555564247b in mutt_str_strdup (s=0x550074736554 <error: Cannot access memory at address 0x550074736554>)
    at mutt/string.c:328
#1  0x00005555555b78e5 in mutt_option_set (val=0x7fffffffbf00, err=0x7fffffffbf20) at init.c:463
#2  0x0000555555632bc2 in lua_mutt_set (l=0x555555a28ff8) at mutt_lua.c:148
#3  0x00007ffff6063bd6 in  () at /usr/lib/liblua.so.5.3
#4  0x00007ffff607091d in  () at /usr/lib/liblua.so.5.3
#5  0x00007ffff6063eaf in  () at /usr/lib/liblua.so.5.3
#6  0x00007ffff6063f01 in  () at /usr/lib/liblua.so.5.3
#7  0x00007ffff6063322 in  () at /usr/lib/liblua.so.5.3
#8  0x00007ffff60641fb in  () at /usr/lib/liblua.so.5.3
#9  0x00007ffff605f8e4 in lua_pcallk () at /usr/lib/liblua.so.5.3
#10 0x0000555555633816 in mutt_lua_parse (tmp=0x7fffffffc710, s=0x7fffffffc690, data=0, err=0x7fffffffc6f0) at mutt_lua.c:393
#11 0x00005555555bfbb3 in mutt_parse_rc_line (line=0x7fffffffc730 "lua mutt.set('realname', 'Test')", token=0x7fffffffc710, err=0x7fffffffc6f0) at init.c:3082
#12 0x0000555555583ad7 in mutt_enter_command () at commands.c:645
#13 0x000055555559d234 in mutt_index_menu () at curs_main.c:2901
#14 0x00005555555c8562 in main (argc=1, argv=0x7fffffffe398, env=0x7fffffffe3a8) at main.c:924
```

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @fgrsnau 
Branch [issue/1096](https://github.com/neomutt/neomutt/tree/issue/1096) will fix your problem.

**Comment by flatcap** [comment]
Note: "paths" and "strings" are handled separately, which is why your 'signature' test succeeded.
