### ISSUE TITLE
Possible buffer underflow in mutt/path.c

### ISSUE THREAD

**Issue by z2v** [neomutt/neomutt#1315]
## Expected Behaviour

Tests pass.

## Actual Behaviour

Running tests with AddressSanitizer enabled results in the following alert:
```
test/neomutt-test
Test test_base64_encode...                      [   OK   ]
Test test_base64_decode...                      [   OK   ]
Test test_base64_lengths...                     [   OK   ]
Test test_rfc2047...                            [   OK   ]
Test test_md5...                                [   OK   ]
Test test_md5_ctx...                            [   OK   ]
Test test_md5_ctx_bytes...                      [   OK   ]
Test test_string_strfcpy...                     [   OK   ]
Test test_string_strnfcpy...                    [   OK   ]
Test test_addr_mbox_to_udomain...               [   OK   ]
Test test_mutt_path_tidy_slash...               =================================================================
==51915==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fffffffe13f at pc 0x00000030a2b9 bp 0x7fffffffe010 sp 0x7fffffffe008
READ of size 1 at 0x7fffffffe13f thread T0
    #0 0x30a2b8 in mutt_path_tidy_slash /home/vovka/projects/neomutt/mutt/path.c:85:8
    #1 0x2d4201 in test_mutt_path_tidy_slash /home/vovka/projects/neomutt/test/path.c:41:5
    #2 0x2d26dd in test_do_run__ /home/vovka/projects/neomutt/./test/acutest.h:464:9
    #3 0x2d16ba in test_run__ /home/vovka/projects/neomutt/./test/acutest.h:546:23
    #4 0x2d0c7b in main /home/vovka/projects/neomutt/./test/acutest.h:816:13
    #5 0x249094 in _start /usr/src/lib/csu/amd64/crt1.c:74:7

Address 0x7fffffffe13f is located in stack of thread T0 at offset 31 in frame
    #0 0x2d40af in test_mutt_path_tidy_slash /home/vovka/projects/neomutt/test/path.c:8

  This frame has 1 object(s):
    [32, 96) 'buf' (line 37) <== Memory access at offset 31 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow /home/vovka/projects/neomutt/mutt/path.c:85:8 in mutt_path_tidy_slash
Shadow bytes around the buggy address:
  0x4ffffffffbd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffffffbe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffffffbf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffffffc00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffffffc10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x4ffffffffc20: 00 00 00 00 f1 f1 f1[f1]00 00 00 00 00 00 00 00
  0x4ffffffffc30: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffffffc40: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x4ffffffffc50: f8 f8 f8 f8 f8 f8 f3 f3 f3 f3 f3 f3 00 00 00 00
  0x4ffffffffc60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffffffc70: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==51915==ABORTING
Test test_mutt_path_tidy_dotdot...              [   OK   ]
Test test_mutt_path_tidy...                     [   OK   ]
FAILED: 1 of 13 unit tests have failed.
*** Error code 1
```

## Steps to Reproduce

* Configure NeoMutt with AddressSanitizer
* Run tests

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to current master

## NeoMutt Version

```
System: FreeBSD 12.0-ALPHA2 (amd64)
ncurses: ncurses 5.9.20140222 (compiled with 5.9.20140222)
libiconv: 1.14
GPGme: 1.11.1
hcache backends: tokyocabinet, lmdb

Compiler:
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin

Configure options: --with-ssl=/usr/lib --gpgme --notmuch --lmdb --tokyocabinet --disable-idn --sasl

Compilation CFLAGS: -pipe -march=native -g -fstack-protector -fno-strict-aliasing -isystem /usr/local/include -fsanitize=address -fno-omit-frame-pointer -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/lib/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme -gss +hcache -homespool -idn -locales_hack -lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

```

**Comment by flatcap** [comment]
Good find!  Thanks!
