### ISSUE TITLE
Segfault in SSL_write

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1364]
20180716-513-573638

```
#0  0x00007fc0e07c960a in SSL_write () from /usr/lib64/libssl.so.1.0.0
#1  0x000056243da46b7d in ssl_socket_write (conn=<optimized out>, buf=<optimized out>, count=<optimized out>)
    at conn/ssl.c:1364
#2  0x000056243da44cbe in mutt_socket_write_d (conn=0x56243ecd4150, buf=0x56243eca59a0 "a0000 LOGOUT\r\n", len=14, 
    dbg=dbg@entry=2) at conn/socket.c:183
#3  0x000056243da378b4 in cmd_start (adata=0x56243ecd0540, cmdstr=cmdstr@entry=0x56243da7c84a "LOGOUT", 
    flags=flags@entry=0) at imap/command.c:206
#4  0x000056243da37911 in imap_cmd_start (adata=<optimized out>, cmdstr=cmdstr@entry=0x56243da7c84a "LOGOUT")
    at imap/command.c:1075
#5  0x000056243da39862 in imap_logout (adata=adata@entry=0x56243ecd43d8) at imap/imap.c:1137
#6  0x000056243da39938 in imap_logout_all () at imap/imap.c:759
#7  0x000056243d9d038d in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1218
```

**Comment by l29ah** [comment]
Another, similar one on 20180716-516-6047ee:
```
#0  0x00007ff13f0c75b5 in SSL_write () from /usr/lib64/libssl.so.1.0.0
#1  0x0000562eac13dbe3 in ssl_socket_write (conn=<optimized out>, buf=<optimized out>, count=<optimized out>) at conn/ssl.c:1364
#2  0x0000562eac13bd24 in mutt_socket_write_d (conn=0x562eac4db910, buf=0x562eac5379d0 "a0000 IDLE\r\n", len=12, dbg=dbg@entry=2) at conn/socket.c:183
#3  0x0000562eac12e91a in cmd_start (adata=adata@entry=0x562eac4d7d00, cmdstr=cmdstr@entry=0x562eac1730d3 "IDLE", flags=flags@entry=8) at imap/command.c:206
#4  0x0000562eac12e994 in imap_cmd_idle (adata=adata@entry=0x562eac4d7d00) at imap/command.c:1364
#5  0x0000562eac1314db in imap_check (adata=0x562eac4d7d00, force=force@entry=false) at imap/imap.c:1395
#6  0x0000562eac131682 in imap_mbox_check (ctx=0x562eac4aeae0, index_hint=<optimized out>) at imap/imap.c:2513
#7  0x0000562eac0d4eba in mx_mbox_check (ctx=<optimized out>, index_hint=index_hint@entry=0x7fffa965408c) at mx.c:1070
#8  0x0000562eac0a2990 in mutt_index_menu () at curs_main.c:1041
#9  0x0000562eac0c7378 in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1213
```
