### ISSUE TITLE
Segfault in mutt_socket_write_d

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1371]
```
#0  0x000055e09dcb1c6d in mutt_socket_write_d (conn=0x0, buf=0x55e09e77e700 "a0000 UID FETCH 7042 RFC822\r\n", len=29, dbg=dbg@entry=2) at conn/socket.c:173
#1  0x000055e09dca4203 in cmd_start (adata=adata@entry=0x55e09e6a7880, cmdstr=cmdstr@entry=0x7fff9d19f230 "UID FETCH 7042 RFC822", flags=flags@entry=0) at imap/command.c:207
#2  0x000055e09dca4269 in imap_cmd_start (adata=adata@entry=0x55e09e6a7880, cmdstr=cmdstr@entry=0x7fff9d19f230 "UID FETCH 7042 RFC822") at imap/command.c:1076
#3  0x000055e09dcadd6c in imap_msg_open (ctx=0x55e09e6a0590, msg=0x55e09e724520, msgno=<optimized out>) at imap/message.c:1867
#4  0x000055e09dc49fe6 in mx_msg_open (ctx=0x55e09e6a0590, msgno=2) at mx.c:1121
#5  0x000055e09dc46e04 in mutt_parse_mime_message (ctx=0x55e09e6a0590, cur=cur@entry=0x55e09e77d3f0) at mutt_parse.c:56
#6  0x000055e09dc09638 in mutt_display_message (cur=0x55e09e77d3f0) at commands.c:106
#7  0x000055e09dc1b960 in mutt_index_menu () at curs_main.c:2301
#8  0x000055e09dc3c3cd in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1215
```
20180716-566-b63e77

**Comment by l29ah** [comment]
Occurs when i try to open any mail in my IMAP mailbox.

**Comment by N8Fear** [comment]
Trying to bisect it, gives me e46ba978910c911ec57aea7fb7735a5a941717c5 as the first faulty commit.

**Comment by l29ah** [comment]
Now it crashes right at the start, looks relevant:
```
#0  mutt_socket_readchar (conn=0x0, c=c@entry=0x7ffe84d8fc8f "") at conn/socket.c:229
#1  0x000056073aaf0b9b in imap_read_literal (fp=fp@entry=0x56073b4346f0, adata=adata@entry=0x56073b5ba8d0, bytes=622, pbar=pbar@entry=0x0) at imap/imap.c:799
#2  0x000056073aaf5e33 in msg_fetch_header (m=m@entry=0x56073b5b8800, ih=ih@entry=0x7ffe84d8fd70, 
    buf=0x56073b5f524b "UID 1398 FLAGS (\\Seen) INTERNALDATE \"20-Dec-2017 10:28:19 +0200\" RFC822.SIZE 2216709 BODY[HEADER.FIELDS (DATE FROM SUBJECT TO CC MESSAGE-ID REFERENCES CONTENT-TYPE CONTENT-DESCRIPTION IN-REPLY-TO REPL"..., 
    fp=0x56073b4346f0) at imap/message.c:454
#3  0x000056073aaf6e32 in read_headers_fetch_new (adata=adata@entry=0x56073b59ffb0, msn_begin=msn_begin@entry=1, msn_end=msn_end@entry=194, evalhc=evalhc@entry=false, maxuid=maxuid@entry=0x7ffe84d8ffb4, 
    initial_download=initial_download@entry=true) at imap/message.c:1056
#4  0x000056073aaf77dd in imap_read_headers (adata=adata@entry=0x56073b59ffb0, msn_begin=msn_begin@entry=1, msn_end=msn_end@entry=194, initial_download=initial_download@entry=true) at imap/message.c:1291
#5  0x000056073aaf51bb in imap_mbox_open (ctx=0x56073b5b35e0) at imap/imap.c:2667
#6  0x000056073aa96586 in mx_mbox_open (m=<optimized out>, path=<optimized out>, flags=0) at mx.c:334
#7  0x000056073aa873bc in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1201
```

**Comment by l29ah** [comment]
On Tue, Oct 30, 2018 at 11:33:34AM -0700, Austin Ray wrote:
> @l29ah is your spoolfile an IMAPS mailbox? What happens if you comment out the spoolfile statement in your configuration file?

Yeah. Then it would run and complain about non-existent local mailbox or smth like that.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by sileht** [comment]
I'm guessing https://github.com/neomutt/neomutt/pull/1396 have fixed this. My imap is working again since. Let's close this for now. Feel free to reopen if that occurs again.
