### ISSUE TITLE
segfault in mutt_index_menu

### ISSUE THREAD

**Issue by EdwardBetts** [neomutt/neomutt#1433]
Running 38b0451b6

When I quit neomutt it says "Error saving flags. Close anyway? ([no]/yes):" I go with the default (no) and it segfaults. I'm reading mail via IMAP. This happens every time. Here is some debugging from gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555594440 in mutt_index_menu () at index.c:1020
1020        menu->max = Context ? Context->mailbox->vcount : 0;
(gdb) bt
#0  0x0000555555594440 in mutt_index_menu () at index.c:1020
#1  0x000055555556f380 in main (argc=<optimized out>, argv=0x7fffffffdc18, envp=<optimized out>) at main.c:1216
(gdb) p Context
$1 = (struct Context *) 0x555555702340
(gdb) p Context->mailbox
$2 = (struct Mailbox *) 0x0
(gdb) p Context->mailbox->vcount
Cannot access memory at address 0x2040
(gdb)
```

neomutt -v output:
```
System: Linux 4.18.0-2-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.2.0-9' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.2.0 (Debian 8.2.0-9) 

Configure options: --enable-debug --ssl --mixmaster

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__  -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss -hcache -homespool +idn +inotify -locales_hack -lua +meta 
  +mixmaster +nls -notmuch +openssl +pgp -sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

**Comment by gahr** [comment]
Is this still happening with a fresh `master`?

**Comment by EdwardBetts** [comment]
Yes, still happening with `master`. I just test and I get this error:
`terminated by signal SIGSEGV (Address boundary error)`

**Comment by gahr** [comment]
Can you figure the reason why it's failing to store the flags?

**Comment by EdwardBetts** [comment]
I'm running against a mock IMAP server that doesn't support saving the flags.

**Comment by gahr** [comment]
I think I have replicated the workflow by debugging the code, but I can't reproduce the crash answering `No` to `Error saving flags. Close anyway?`. Can you please check with a fresh master?

**Comment by EdwardBetts** [comment]
I just tried with master. I can confirm that this is fixed.

**Comment by gahr** [comment]
Thanks for checking!
