### ISSUE TITLE
segfaults on neomutt-1.7.0-20160910.fc24.x86_64

### ISSUE THREAD

**Issue by sadsfae** [neomutt/neomutt#147]
I'll see if I can reproduce this but I'm getting segfaults on the latest Fedora 24 build.

```
Sep 15 13:10:53 oberschnutz kernel: mutt[2804]: segfault at 18 ip 0000558d6529223a sp 00007ffe5cdfc1f0 error 4 in mutt[558d6525f000+10e000]
Sep 15 13:10:53 oberschnutz systemd: Started Process Core Dump (PID 5981/UID 0).
```

This behavior occurs when I hit **q** to exit a thread.  It only happens occasionally, and i'll try and see if I can reproduce it.  Leave this here for now - I don't have any gdb or further trace information at this time.

**Comment by flatcap** [comment]
Thanks for the info.

It always crashes in the pager, but I think the damage may be happening elsewhere.

Do you have ABRT enabled?  The COPR build automatically generates debuginfo rpms.
There's probably a way to get a stack trace.  Is there anything in /var/spool/abrt ?

**Comment by sadsfae** [comment]
I disable ABRT but I can install it and see about collecting more info.

**Comment by sthen** [comment]
Not sure if it exactly the same crasher but I am seeing this on 20160910:

```
Fetching message headers... 2526/2526 (100%)Segmentation fault (core dumped) 

$ gdb /usr/local/bin/mutt mutt.core  
[..snip..]
This GDB was configured as "amd64-unknown-openbsd6.0"...
Core was generated by `mutt'.
Program terminated with signal 11, Segmentation fault.
[..snip..]
#0  update_index (menu=0x0, ctx=0x17f5b61bf00, check=1, oldcount=2526, index_hint=0)
    at /usr/obj/ports/mutt-1.7.0.20160910-gpgme/neomutt-20160910/curs_main.c:371
371	    if (menu->current < ctx->vcount)
```

Null deref of menu.

```
(gdb) bt
#0  update_index (menu=0x0, ctx=0x17f5b61bf00, check=1, oldcount=2526, index_hint=0)
    at /usr/obj/ports/mutt-1.7.0.20160910-gpgme/neomutt-20160910/curs_main.c:371
#1  0x0000017ce454f070 in mutt_pager (banner=0x0, fname=Variable "fname" is not available.
)
    at /usr/obj/ports/mutt-1.7.0.20160910-gpgme/neomutt-20160910/pager.c:2031
#2  0x0000017ce4512829 in mutt_display_message (cur=0x17fa515bd00)
    at /usr/obj/ports/mutt-1.7.0.20160910-gpgme/neomutt-20160910/commands.c:225
#3  0x0000017ce451e4cc in mutt_index_menu ()
    at /usr/obj/ports/mutt-1.7.0.20160910-gpgme/neomutt-20160910/curs_main.c:1902
#4  0x0000017ce453dab7 in main (argc=1, argv=0x7f7ffffc5cd8)
    at /usr/obj/ports/mutt-1.7.0.20160910-gpgme/neomutt-20160910/main.c:901
```

My build looks like this:

```
NeoMutt 20160910 (1.7.0)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: OpenBSD 6.0 (amd64)
libidn: 1.33 (compiled with 1.33)
hcache backend: qdbm 1.8.78

Compiler:
Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.0/4.2.1/specs
Target: amd64-unknown-openbsd6.0
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719 

Configure options: '--enable-external_dotlock' '--disable-fcntl' '--enable-compressed' '--enable-flock' '--enable-hcache' '--disable-notmuch' '--enable-sidebar' '--with-idn' '--enable-imap' '--enable-pop' '--enable-smtp' '--enable-nntp' '--without-gdbm' '--without-tokyocabinet' '--with-qdbm' '--with-docdir=/usr/local/share/doc/mutt' '--with-ssl' '--enable-debug' '--enable-gpgme' '--with-curses' '--prefix=/usr/local' '--sysconfdir=/etc/mutt' '--mandir=/usr/local/man' '--infodir=/usr/local/info' '--localstatedir=/var' '--disable-silent-rules' '--disable-gtk-doc' 'CC=cc' 'CFLAGS=-O2 -pipe -g' 'LDFLAGS=-L/usr/local/lib' 'CPPFLAGS=-I/usr/local/include'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -O2 -pipe -g

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME +CRYPT_BACKEND_GPGME 
+DEBUG +DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET +HAVE_GETADDRINFO 
+HAVE_GETSID +HAVE_ICONV +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR 
+HAVE_LIBIDN +HAVE_META +HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS +USE_COMPRESSED -USE_DOTLOCK 
-USE_FCNTL +USE_FLOCK -USE_FMEMOPEN -USE_GNU_REGEX -USE_GSS +USE_HCACHE 
+USE_IMAP -USE_NOTMUCH +USE_NNTP +USE_POP -USE_SASL -USE_SETGID +USE_SIDEBAR 
+USE_SMTP -USE_SSL_GNUTLS +USE_SSL_OPENSSL 
-DOMAIN
-MIXMASTER
ISPELL="/usr/local/bin/ispell"
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SYSCONFDIR="/etc/mutt"
EXECSHELL="/bin/sh"

patch-attach-headers-color-neomutt
patch-compress-neomutt
patch-cond-date-neomutt
patch-encrypt-to-self-neomutt
patch-fmemopen-neomutt
patch-forgotten-attachments-neomutt
patch-ifdef-neomutt
patch-index-color-neomutt
patch-initials-neomutt
patch-keywords-neomutt
patch-limit-current-thread-neomutt
patch-lmdb-neomutt
patch-multiple-fcc-neomutt
patch-nested-if-neomutt
patch-new-mail-neomutt
patch-nntp-neomutt
patch-notmuch-neomutt
patch-progress-neomutt
patch-quasi-delete-neomutt
patch-reply-with-xorig-neomutt
patch-sensible-browser-neomutt
patch-sidebar-neomutt
patch-skip-quoted-neomutt
patch-smime-encrypt-self-neomutt
patch-status-color-neomutt
patch-timeout-neomutt
patch-tls-sni-neomutt
```

**Comment by flatcap** [comment]
Thanks for the report @sthen 
It **does** look like another manifestation of the same problem.
I've already made a commit that will prevent this crash: acd53aa (and hopefully some others).

I'll probably make a release later this evening, containing just bug-fixes.

**Comment by brad0** [comment]
I am seeing a crash like so with 20160916 every time I try and open my SENT box..

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strcmp () at /usr/src/lib/libc/arch/amd64/string/strcmp.S:46
46      /usr/src/lib/libc/arch/amd64/string/strcmp.S: No such file or directory.
(gdb) bt
#0  strcmp () at /usr/src/lib/libc/arch/amd64/string/strcmp.S:46
#1  0x000006ea87aa6b9e in mutt_strcmp (a=0x6ed28c58730 "Judith", b=0x6ecea989e00 <error: Cannot access memory at address 0x6ecea989e00>) at lib.c:875
#2  0x000006ea87a48f08 in hash_find_hash (table=0x6ecd3a25680, hash=129, key=0x6ed28c58730 "Judith") at hash.c:150
#3  0x000006ea87a4d3db in mutt_label_ref_dec (env=0x6eca0354700) at headers.c:230
#4  0x000006ea87aa935e in mutt_free_envelope (p=0x6ecc5225848) at muttlib.c:778
#5  0x000006ea87aa8057 in mutt_free_header (h=0x6ed545f7ab0) at muttlib.c:365
#6  0x000006ea87a640c8 in mx_fastclose_mailbox (ctx=0x6eca9f2e500) at mx.c:735
#7  0x000006ea87a6566d in mx_close_mailbox (ctx=0x6eca9f2e500, index_hint=0x7f7ffffbe188) at mx.c:1137
#8  0x000006ea87a26afe in main_change_folder (menu=0x6ed048e4800, op=111, buf=0x7f7ffffbe9b0 "imap://brad@mail.comstyle.com/Sent", bufsz=1024, oldcount=0x7f7ffffbe190, 
    index_hint=0x7f7ffffbe188, flags=0) at curs_main.c:668
#9  0x000006ea87a2aa01 in mutt_index_menu () at curs_main.c:1869
#10 0x000006ea87a54dc2 in main (argc=1, argv=0x7f7ffffbf8f8) at main.c:900
```

**Comment by flatcap** [comment]
hi @brad0, thanks for the bug report.
Your problem is in a different version of NeoMutt and, according to the backtrace, a different place.
I've opened a new issue for you: #164 and deleted your post from this issue (to save confusion).
