### ISSUE TITLE
neomutt segfaults when trying to save a message (using FCC) to an mbox it is reading

### ISSUE THREAD

**Issue by melbit-naveennathan** [neomutt/neomutt#1524]
## Expected Behaviour

Open a mbox file, send an email, saving to the same mbox file that is opened.

## Actual Behaviour

Segfault (but it does write the email to the mbox).

## Steps to Reproduce

```bash
>tmp.mbox;
neomutt -F /dev/null -e 'fcc-hook . tmp.mbox' -f tmp.mbox
# compose an email and send it and neomutt will segfault
```

Here is the stack trace:

```
$ lldb ./neomutt -c /cores/core.82923
(lldb) target create "./neomutt" --core "/cores/core.82923"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Core file '/cores/core.82923' (x86_64) was loaded.
(lldb) bt
neomutt was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00000001061bd6fa neomutt`ctx_update_tables(ctx=0x00007fa49c6052d0, committing=false) at context.c:172 [opt]
    frame #1: 0x00000001061bda58 neomutt`ctx_mailbox_changed(m=<unavailable>, action=<unavailable>) at context.c:274 [opt]
    frame #2: 0x000000010623480e neomutt`mbox_mbox_check at mbox.c:587 [opt]
    frame #3: 0x000000010623479d neomutt`mbox_mbox_check(m=0x00007fa49e076400, index_hint=0x00007ffee9a53dec) at mbox.c:1107 [opt]
    frame #4: 0x00000001061f7517 neomutt`mx_mbox_check(m=0x00007fa49e076400, index_hint=<unavailable>) at mx.c:1025 [opt]
    frame #5: 0x00000001061d2048 neomutt`mutt_index_menu at index.c:1064 [opt]
    frame #6: 0x00000001062241b2 neomutt`main(argc=<unavailable>, argv=<unavailable>, envp=<unavailable>) at main.c:1216 [opt]
    frame #7: 0x00007fff6234c085 libdyld.dylib`start + 1
    frame #8: 0x00007fff6234c085 libdyld.dylib`start + 1
(lldb) f 0
frame #0: 0x00000001061bd6fa neomutt`ctx_update_tables(ctx=0x00007fa49c6052d0, committing=false) at context.c:172 [opt]
   169    int i, j, padding;
   170  
   171    /* update memory to reflect the new state of the mailbox */
-> 172    m->vcount = 0;
   173    ctx->vsize = 0;
   174    m->msg_tagged = 0;
   175    m->msg_deleted = 0;
(lldb) f 1
frame #1: 0x00000001061bda58 neomutt`ctx_mailbox_changed(m=<unavailable>, action=<unavailable>) at context.c:274 [opt]
   271        ctx_update(ctx);
   272        break;
   273      case MBN_RESORT:
-> 274        ctx_update_tables(ctx, false);
   275        mutt_sort_headers(ctx, true);
   276        break;
   277    }
(lldb) f 2
frame #2: 0x000000010623480e neomutt`mbox_mbox_check at mbox.c:587 [opt]
   584  
   585      old_sort = Sort;
   586      Sort = SORT_ORDER;
-> 587      mutt_mailbox_changed(m, MBN_RESORT);
   588      Sort = old_sort;
   589    }
   590  
```

## How often does this happen?

Always.

## When did it start to happen?

Latest release and also master branch.

## NeoMutt Version

```
$ ./neomutt -v
NeoMutt 20180716-1053-b5862a
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.0.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
hcache backends: tokyocabinet, lmdb

Compiler:
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: --disable-doc --lmdb --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool +idn -inotify -locales_hack -lua +meta 
  -mixmaster +nls -notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
OSX 10.14

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
No

**Comment by melbit-naveennathan** [comment]
Also verified this is bug doesn't manifest in mutt 1.11.1 (2018-12-01).

**Comment by scottkosty** [comment]
Did it happen on a previous neomutt version? If not, maybe consider a git bisect?

**Comment by roccoblues** [comment]
I'm trying to cleanup some older issues here. Can you still reproduce this issue with the latest version? Thanks!

**Comment by pwaring** [comment]
I also experienced this issue, however it isn't happening for me on the latest stable release (20231023). It does affect the version in Ubuntu 22.04 LTS - I had to move to building Neomutt from source as there was no other way to fix the issue. As there are broken versions in Linux packages this might still get reported upstream.
