### ISSUE TITLE
crashes when replying to an attachment

### ISSUE THREAD

**Issue by alvherre** [neomutt/neomutt#1525]
Hello

I just had neomutt crash on me when I was trying to reply to an attachment.  I've used this feature in the past in order to comment on patches submitted as attachments.  Here's the backtrace:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558c0d20663f in ci_send_message (flags=<optimized out>, flags@entry=3, 
    msg=<optimized out>, 
    tempfile=tempfile@entry=0x7ffce4dd1240 "/home/alvherre/tmp/neomutt-alvherre-1000-7952-7966511958087673173", ctx=ctx@entry=0x0, cur=<optimized out>, 
    cur@entry=0x558c17ee9f40) at send.c:1721
1721	      mutt_message_hook(ctx->mailbox, cur, MUTT_REPLY_HOOK);
(gdb) bt
#0  0x0000558c0d20663f in ci_send_message (flags=<optimized out>, flags@entry=3, 
    msg=<optimized out>, 
    tempfile=tempfile@entry=0x7ffce4dd1240 "/home/alvherre/tmp/neomutt-alvherre-1000-7952-7966511958087673173", ctx=ctx@entry=0x0, cur=<optimized out>, 
    cur@entry=0x558c17ee9f40) at send.c:1721
#1  0x0000558c0d202128 in mutt_attach_reply (fp=0x558c39e75f50, 
    e=e@entry=0x558c17ee9f40, actx=0x558c39d21980, cur=<optimized out>, flags=3)
    at recvcmd.c:1039
#2  0x0000558c0d200706 in mutt_view_attachments (e=0x558c17ee9f40)
    at recvattach.c:1573
#3  0x0000558c0d1f5c38 in mutt_pager (banner=banner@entry=0x0, 
    fname=fname@entry=0x7ffce4dd3730 "/home/alvherre/tmp/neomutt-alvherre-1000-7952-5897500737996992337", flags=flags@entry=66, extra=extra@entry=0x7ffce4dd4730)
    at pager.c:3375
#4  0x0000558c0d1ab542 in mutt_display_message (cur=0x558c17ee9f40)
    at commands.c:255
#5  0x0000558c0d1ca803 in mutt_index_menu () at index.c:2291
#6  0x0000558c0d1a276d in main (argc=<optimized out>, argv=<optimized out>, 
    envp=<optimized out>) at main.c:1215
```

This is on commit 3112e6cab89236b1f7422a96228ea2454d48034a.  Haven't tried on newer master branch yet.

**Comment by flatcap** [comment]
Thanks for the bug report, @alvherre.
