### ISSUE TITLE
Crash on startup - imap tries to use history

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1592]
irc user _jm reports that:

The segfault is generated because `mutt_hist_init()` hasn't be called yet.
In `mutt_hist_add()` the History pointer `h` is not null however it's internal
data structure `h->hist` is NULL which generate the segfault on the `h->hist[prev]`
access.

Here is a quick an dirty fix, which moves the `mutt_hist_init()` sooner during `mutt_init()`.
However I don't known where this initialisation makes more sense.

**NeoMutt version**: master @ 539968e80

```diff
diff --git a/init.c b/init.c
index d2fd13f9a..6ce1ef1d0 100644
--- a/init.c
+++ b/init.c
@@ -3182,6 +3182,9 @@ int mutt_init(bool skip_sys_rc, struct ListHead *commands)
     }
   }

+  mutt_hist_init();
+  mutt_hist_read_file();
+
   /* Read the user's initialization file.  */
   struct ListNode *np = NULL;
   STAILQ_FOREACH(np, &Muttrc, entries)
@@ -3222,9 +3225,6 @@ int mutt_init(bool skip_sys_rc, struct ListHead *commands)

   mutt_file_mkdir(C_Tmpdir, S_IRWXU);

-  mutt_hist_init();
-  mutt_hist_read_file();
-
 #ifdef USE_NOTMUCH
   if (C_VirtualSpoolfile)
   {
```

backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004be3a9 in mutt_hist_add (hclass=hclass@entry=HC_OTHER, str=str@entry=0x898fa0 "jm", save=save@entry=true) at mutt/history.c:495
#0  0x00000000004be3a9 in mutt_hist_add (hclass=hclass@entry=HC_OTHER, str=str@entry=0x898fa0 "jm", save=save@entry=true) at mutt/history.c:495
#1  0x0000000000421f19 in mutt_enter_string_full (buf=buf@entry=0x898fa0 "jm", buflen=buflen@entry=128, col=28, flags=flags@entry=0, multiple=multiple@entry=false, files=files@entry=0x0,
    numfiles=numfiles@entry=0x0, state=0x992e40) at enter.c:777
#2  0x000000000041c6f3 in mutt_get_field_full (field=field@entry=0x7fffffff84e0 "Username at mail.xxx: ", buf=buf@entry=0x898fa0 "jm", buflen=buflen@entry=128, complete=complete@entry=0,
    multiple=multiple@entry=false, files=files@entry=0x0, numfiles=numfiles@entry=0x0) at curs_lib.c:274
#3  0x000000000041c781 in mutt_get_field_unbuffered (msg=msg@entry=0x7fffffff84e0 "Username at mail.xxx: ", buf=buf@entry=0x898fa0 "jm", buflen=buflen@entry=128, flags=flags@entry=0)
    at curs_lib.c:297
#4  0x0000000000442736 in mutt_account_getuser (account=0x898fa0) at mutt_account.c:234
#5  0x00000000004977f7 in imap_auth_plain (adata=0x8960a0, method=<optimized out>) at imap/auth_plain.c:52
#6  0x0000000000496d45 in imap_authenticate (adata=adata@entry=0x8960a0) at imap/auth.c:113
#7  0x000000000049eee0 in imap_login (adata=adata@entry=0x8960a0) at imap/imap.c:1918
#8  0x000000000049f15c in imap_ac_add (a=0x894f30, m=0x896dd0) at imap/imap.c:1875
#9  0x000000000044b16d in mx_ac_add (a=a@entry=0x894f30, m=0x896dd0) at mx.c:1535
#10 0x0000000000436d75 in parse_mailboxes (buf=0x7fffffff9b60, s=0x7fffffff9ab0, data=<optimized out>, err=<optimized out>) at init.c:1372
#11 0x0000000000437b7f in mutt_parse_rc_line (line=<optimized out>, token=token@entry=0x7fffffff9b60, err=err@entry=0x7fffffffac10) at init.c:3292
#12 0x0000000000437e65 in mutt_parse_rc_line (err=0x7fffffffac10, token=0x7fffffff9b60, line=<optimized out>) at init.c:821
#13 source_rc (rcfile_path=<optimized out>, err=err@entry=0x7fffffffac10) at init.c:823
#14 0x0000000000438b55 in mutt_init (skip_sys_rc=<optimized out>, commands=commands@entry=0x7fffffffb6d0) at init.c:3191
#15 0x0000000000407c24 in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:692
```

**Comment by flatcap** [comment]
Unfortunately, the offered fix won't help.
Initialising the history has to happen after we've read the user's config.
