### ISSUE TITLE
Crash when opening SENT box

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#164]
@brad0
I am seeing a crash like so with 20160916 every time I try and open my SENT box..

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strcmp () at /usr/src/lib/libc/arch/amd64/string/strcmp.S:46
46      /usr/src/lib/libc/arch/amd64/string/strcmp.S: No such file or directory.
(gdb) bt
#0  strcmp () at /usr/src/lib/libc/arch/amd64/string/strcmp.S:46
#1  0x000006ea87aa6b9e in mutt_strcmp (a=0x6ed28c58730 "Judith", b=0x6ecea989e00 <error: Cannot access memory at address 0x6ecea989e00>) at lib.c:875
#2  0x000006ea87a48f08 in hash_find_hash (table=0x6ecd3a25680, hash=129, key=0x6ed28c58730 "Judith") at hash.c:150
#3  0x000006ea87a4d3db in mutt_label_ref_dec (env=0x6eca0354700) at headers.c:230
#4  0x000006ea87aa935e in mutt_free_envelope (p=0x6ecc5225848) at muttlib.c:778
#5  0x000006ea87aa8057 in mutt_free_header (h=0x6ed545f7ab0) at muttlib.c:365
#6  0x000006ea87a640c8 in mx_fastclose_mailbox (ctx=0x6eca9f2e500) at mx.c:735
#7  0x000006ea87a6566d in mx_close_mailbox (ctx=0x6eca9f2e500, index_hint=0x7f7ffffbe188) at mx.c:1137
#8  0x000006ea87a26afe in main_change_folder (menu=0x6ed048e4800, op=111, buf=0x7f7ffffbe9b0 "imap://brad@mail.comstyle.com/Sent", bufsz=1024, oldcount=0x7f7ffffbe190, 
    index_hint=0x7f7ffffbe188, flags=0) at curs_main.c:668
#9  0x000006ea87a2aa01 in mutt_index_menu () at curs_main.c:1869
#10 0x000006ea87a54dc2 in main (argc=1, argv=0x7f7ffffbf8f8) at main.c:900
```

**Comment by flatcap** [comment]
Hi @brad0

I've had a quick look, but I can't reproduce a crash.
"Cannot access memory" -- implies it trying to access somethine that's already been freed.  Not a good sign.

Have you used other, older, versions of NeoMutt?
Did they work correctly?
Do you use a **lot** of different labels?  Say \>50?

Do any other folders cause a crash?
The crash, above, was looking for a label: "Judith".  Can you copy that email into another folder and see if that causes a crash?  Obviously, you'll need a working version of NeoMutt/Mutt for that.

How are your debugging skills?
Have you heard of valgrind?
Can I talk you through using it?

I'm still thinking, but any extra info you can find out will help me.
Thanks.

**Comment by sthen** [comment]
@brad0 It might be worth checking to see if you can get a different trace with MALLOC_OPTIONS FGJ..

**Comment by flatcap** [comment]
@0-wiz-0 writes:

I have a repeatable core dump leaving one of my maildirs.

Here's the backtrace:
```
(gdb) bt
#0  0x00007f7ff4300388 in strcmp () from /usr/lib/libc.so.12
#1  0x0000000000498e05 in mutt_strcmp (a=0x7f7ff1d7eaa0 "SUBJECT", b=0x7f7ff31c8fc0 <error: Cannot access memory at address 0x7f7ff31c8fc0>) at lib.c:875
#2  0x0000000000446c1b in hash_find_hash (table=0x7f7fee599da0, hash=75, key=0x7f7ff1d7eaa0 "SUBJECT") at hash.c:150
#3  0x000000000044ab34 in mutt_label_ref_dec (env=0x7f7ff1d80cc0) at headers.c:230
#4  0x000000000049b0eb in mutt_free_envelope (p=0x7f7ff69c4b28) at muttlib.c:778
#5  0x0000000000499fb0 in mutt_free_header (h=0x7f7fef53dcd8) at muttlib.c:365
#6  0x000000000045edd5 in mx_fastclose_mailbox (ctx=0x7f7ff7791350) at mx.c:735
#7  0x000000000045fc67 in mx_close_mailbox (ctx=0x7f7ff7791350, index_hint=0x7f7fffffc4bc) at mx.c:1070
#8  0x0000000000428671 in main_change_folder (menu=0x7f7ff7b355c0, op=113, buf=0x7f7fffffc8d0 "/home/USERNAME/Maildir", bufsz=1024, oldcount=0x7f7fffffc4c8, index_hint=0x7f7fffffc4bc, flags=0) at curs_main.c:677
#9  0x000000000042b997 in mutt_index_menu () at curs_main.c:1886
#10 0x0000000000451a64 in main (argc=1, argv=0x7f7fffffd588) at main.c:882
```

**Comment by flatcap** [comment]
@0-wiz-0
The backtrace implies there's a double free happening.

Good news.
I haven't managed to repeat the crash, but I can repeat the bug reliably under valgrind.

**Setup**:
- Inbox only (maildir)
- Two emails only
- Both have the same single label
- Start mutt
- Immediately close mutt

**Result**:  Valgrind reports an "Invalid read"

Now I have something to debug.

**Comment by brad0** [comment]
That last commit does indeed fix the crash I was experiencing.
