### ISSUE TITLE
segfault in mutt

### ISSUE THREAD

**Issue by phmarek** [neomutt/neomutt#167]
debian package 1.7.0-6; happened after reconnecting (because of network change):

Looks a bit like #147, but I guess that the referenced commit is already in -6?!

```
Authentifiziere (PLAIN)...
                          Program received signal SIGSEGV, Segmentation fault.
                                                                              0x00005555555bb0b2 in mutt_pager (banner=banner@entry=0x0, fname=fname@entry=0x7fffffffc550 "/tmp/mutt-cacao-1044-31304-12457555196043887172", flags=<optimized out>, flags@entry=0x42,
    extra=extra@entry=0x7fffffffc520) at ../../pager.c:1768
1768    ../../pager.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00005555555bb0b2 in mutt_pager (banner=banner@entry=0x0, fname=fname@entry=0x7fffffffc550 "/tmp/mutt-...", flags=<optimized out>, flags@entry=0x42,
    extra=extra@entry=0x7fffffffc520) at ../../pager.c:1768
#1  0x000055555557c055 in mutt_display_message (cur=0x5555567879a0) at ../../commands.c:225
#2  0x000055555558c68b in mutt_index_menu () at ../../curs_main.c:1905
#3  0x000055555556c7aa in main (argc=0x1, argv=<optimized out>) at ../../main.c:877
(gdb) info locals
searchbuf = '\000' <repeats 255 times>
buffer = "-*-NeoMutt: =Lists/openssh [Msgs:261 New:4 Inc:11 2,5M]---(threads/reverse-last-date-received)", '-' <repeats 44 times>, "(3%)---\000", ' ' <repeats 16 times>, "-- (78%)\000indrot.org/show_bug.cgi?id=83"...
helpstr = "i:Verlassen  -:S.zurück  <Space>:S.vor v:Anhänge betr.  d:Lösch.  r:Antw.  j:Nächste Nachr. ?:Hilfe", '\000' <repeats 41 times>, "us-ascii", '\000' <repeats 103 times>
tmphelp = "i:Verlassen  -:S.zurück  <Space>:S.vor v:Anhänge betr.  d:Lösch.  r:Antw.  j:Nächste Nachr.", '\000' <repeats 160 times>
maxLine = 0x30
lastLine = 0x0
lineInfo = 0x555555947740
QuoteList = 0x0
i = <optimized out>
j = <optimized out>
ch = <optimized out>
rc = 0xffffffff
hideQuoted = <optimized out>
q_level = 0x0
force_redraw = 0x0
lines = <optimized out>
curline = <optimized out>
topline = 0x0
oldtopline = <optimized out>
err = <optimized out>
first = <optimized out>
r = <optimized out>
wrapped = <optimized out>
searchctx = <optimized out>
redraw = 0xa0
fp = 0x5555563b26d0
last_pos = 0x500
last_offset = <optimized out>
old_smart_wrap = <optimized out>
old_markers = <optimized out>
sb = {st_dev = 0x2a, st_ino = 0x3606239, st_nlink = 0x1, st_mode = 0x8180, st_uid = 0x414, st_gid = 0x414, __pad0 = 0x0, st_rdev = 0x0, st_size = 0x65e, st_blksize = 0x1000, st_blocks = 0x8, st_atim = {
    tv_sec = 0x57eca8ce, tv_nsec = 0x1bbab026}, st_mtim = {tv_sec = 0x57eca8ce, tv_nsec = 0x25440feb}, st_ctim = {tv_sec = 0x57eca8ce, tv_nsec = 0x25440feb}, __glibc_reserved = {0x0, 0x0, 0x0}}
SearchRE = {buffer = 0x0, allocated = 0x0, used = 0x0, syntax = 0x0, fastmap = 0x0, translate = 0x0, re_nsub = 0x0, can_be_null = 0x0, regs_allocated = 0x0, fastmap_accurate = 0x0, no_sub = 0x0,
  not_bol = 0x0, not_eol = 0x0, newline_anchor = 0x0}
SearchCompiled = 0x0
SearchFlag = <optimized out>
SearchBack = <optimized out>
has_types = <optimized out>
index_status_window = 0x55555639ab90
index_window = 0x55555639abb0
pager_status_window = 0x55555639abd0
pager_window = 0x555556634e20
index = 0x555556634e40
indexlen = <optimized out>
indicator = <optimized out>
old_PagerIndexLines = <optimized out>
index_hint = 0x0
oldcount = <optimized out>
check = <optimized out>
followup_to = <optimized out>
```

**Comment by P-EB** [comment]
Thanks for the report, and for the backtrace.

1.7.0-6 is 20160916 tag. I had a look, but can't see where we create a dangling pointer.

I'll continue investigating.

**Comment by P-EB** [comment]
This seems to be some gcc's optimization, a NULL pointer check is ignored.

With -fno-delete-null-pointer-checks option, this issue should be gone.

@flatcap wants to get more intel on this.

**Comment by aradici** [comment]
FTR
http://bugs.debian.org/839153
http://bugs.debian.org/838720

**Comment by P-EB** [comment]
Commit 65fc87b should fix this issue.

Leaving open for some days.

**Comment by P-EB** [comment]
Everything seems fine, closing. :)
