### ISSUE TITLE
Recent index_format feature can cause crash.

### ISSUE THREAD

**Issue by sileht** [neomutt/neomutt#1711]
Crash when I open certains mailboxes.

## Expected Behaviour

Not crashing

## Actual Behaviour

Crash :)

```
mutt_replacelist_apply (rl=<optimized out>, buf=<optimized out>, buflen=<optimized out>, str=<optimized out>) at mutt/regex.c:422
422                     dst[tlen++] = src[i];
#0  mutt_replacelist_apply (rl=<optimized out>, buf=<optimized out>, buflen=<optimized out>, str=<optimized out>) at mutt/regex.c:422
#1  0x0000000000429601 in apply_subject_mods (env=<optimized out>) at hdrline.c:467
#2  index_format_str (buf=0x40 <error: Cannot access memory at address 0x40>, buflen=1024, col=47, cols=184, op=<optimized out>, src=0x7fffffff9245 " %* (%?l?%l&%c?)", prec=0x7fffffff9110 "",
    if_str=0x7fffffff9710 "➘ ", else_str=0x7fffffff9190 "", data=140737488329576, flags=51 '3') at hdrline.c:1128
#3  0x000000000044746a in mutt_expando_format (buf=<optimized out>, buflen=<optimized out>, col=18446744073709551615, cols=<optimized out>, src=<optimized out>, callback=<optimized out>, data=<optimized out>,
    flags=<optimized out>) at muttlib.c:1268
#4  0x00000000004278a3 in mutt_make_string_flags (buf=0x1 <error: Cannot access memory at address 0x1>, buflen=16, s=0x1b7c545 "@%2]: %R", ctx=<optimized out>, m=<optimized out>, e=<optimized out>,
    flags=<optimized out>) at hdrline.c:1501
#5  0x000000000042d96e in index_make_entry (buf=0x1 <error: Cannot access memory at address 0x1>, buflen=16, menu=<optimized out>, line=<optimized out>) at index.c:803
#6  0x0000000000442773 in menu_make_entry (buflen=1024, buf=<optimized out>, menu=<optimized out>, i=<optimized out>) at menu.c:331
#7  menu_redraw_index (menu=0x99b510) at menu.c:428
#8  0x0000000000434e17 in index_custom_redraw (menu=0x99b510) at index.c:984
#9  0x000000000042e479 in mutt_index_menu () at index.c:1193
#10 0x000000000044240c in main (argc=<optimized out>, argv=0x7fffffffe128, envp=<optimized out>) at main.c:1227

```

## Steps to Reproduce

I have a mailbox when it always occurs.

my index_format is

```
set index_format  = "[%Z] %{%b-%d %H:%M} | %-20.20L | %@label@ %?M?➘ ?%s %* (%?l?%l&%c?)"

index-format-hook label "~f mergify.io" "🔀"
index-format-hook label "~f tetaneutral.net" "📶"
index-format-hook label "~f wazo.io" "💼"
index-format-hook label ".*" "  "
```

Removing %@label@ from the index_fomat fix the issue.

## NeoMutt Version

NeoMutt 20180716-1807-5acfb8

**Comment by gahr** [comment]
I can't reproduce this...

**Comment by flatcap** [comment]
nor me :-(

**Comment by sileht** [comment]
I regulatory rebase my production branch and It doesn't occurred since a while now. I'm closing it.
