### ISSUE TITLE
SIGSEGV when <entire-thread> on empty mailbox

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1719]
To reproduce, run

    :exec entire-thread

from the index when there is no message (i.e., the directory is empty).

## Expected Behaviour

A no-op or user-friendly error.

## Actual Behaviour

SIGSEGV

```
Thread 1 "neomutt" received signal SIGSEGV, Segmentation fault.
0x00005555555a9172 in mutt_index_menu () at index.c:1964
1964	          if (!CUR_EMAIL || !CUR_EMAIL->env || !CUR_EMAIL->env->message_id)
(gdb) bt
#0  0x00005555555a9172 in mutt_index_menu () at index.c:1964
#1  0x00005555555c0ac9 in main (argc=1, argv=0x7fffffffdb88, envp=0x7fffffffdb98) at main.c:1227 
```

## How often does this happen?

- Always (when the directory that neomutt starts up on is empty)

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20180716-1844-e630b3
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.0.0-15-generic (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
$
```

## Extra Info

- Ubuntu 19.04.
- local (maildir), from offlineimap, but I think it can be reproduced also with remote IMAP.

**Comment by scottkosty** [comment]
I should also mention that I use notmuch. Perhaps that is important for reproducing.

**Comment by flatcap** [comment]
@Austin-Ray 
The `CUR_EMAIL` macro is underflowing (`Context->mailbox->emails[Context->mailbox->v2r[menu->current]]`)
`Context->mailbox->v2r[menu->current] == -1`

We probably just need to move the `prereq()` check ahead of this code.

https://github.com/neomutt/neomutt/blob/5dedc626ea3bf332dcbc001067ef3dac13c42a09/index.c#L1959-L1985

**Comment by Austin-Ray** [comment]
@scottkosty I'm unable to reproduce with an empty mailbox, but can reproduce when I have no mailboxes configured. Is this what you meant by empty directory?

I've created #1720 with flatcap's suggested change. Could you try it out and tell me if the bug is fixed? It works when no mailbox is configured.

**Comment by scottkosty** [comment]
@Austin-Ray 
> I'm unable to reproduce with an empty mailbox, but can reproduce when I have no mailboxes configured. Is this what you meant by empty directory?

Sorry for my poor description. That's not what I meant. The specific use case is when I have no messages in my INBOX.

> I've created #1720 with flatcap's suggested change. Could you try it out and tell me if the bug is fixed? It works when no mailbox is configured.

Yes it appears to fix the issue for me. There is no crash and I now get a status "There are no messages", which seems like expected behavior. Thanks to you and flatcap for the fix!
