### ISSUE TITLE
SIGSEGV at `parse_alias`

### ISSUE THREAD

**Issue by mkoskar** [neomutt/neomutt#1882]
## Expected Behaviour
No SIGSEGV

## Actual Behaviour

```
Program received signal SIGSEGV, Segmentation fault.                                                              
mutt_addrlist_append (a=0x5555557e6ad0, al=0x5555557e65c0) at address/address.c:1404                     
1404        TAILQ_INSERT_TAIL(al, a, entries);                                                                    

+(gdb) bt
#0  0x000055555564d9ba in mutt_addrlist_append (a=0x5555557e6ad0, al=0x5555557e65c0) at address/address.c:1404
#1  0x000055555564d9ba in mutt_addrlist_append (al=al@entry=0x5555557e65c0, a=0x5555557e6ad0) at address/address.c:1401
#2  0x000055555564dd88 in group_add_addrlist (al=0x5555557e6638, g=0x5555557e65c0) at address/group.c:189
#3  0x000055555564dd88 in mutt_grouplist_add_addrlist (gl=gl@entry=0x7fffffff80a0, al=al@entry=0x5555557e6638) at address/group.c:233
#4  0x00005555555a7a90 in parse_alias (buf=0x7fffffff81c0, s=<optimized out>, data=<optimized out>, err=0x7fffffffb3e0) at init.c:953
#5  0x00005555555a7d7f in mutt_parse_rc_line (line=<optimized out>, token=token@entry=0x7fffffff81c0, err=err@entry=0x7fffffffb3e0) at init.c:3257
#6  0x00005555555a80b3 in mutt_parse_rc_line (err=0x7fffffffb3e0, token=0x7fffffff81c0, line=<optimized out>) at init.c:3230
#7  0x00005555555a80b3 in source_rc (rcfile_path=rcfile_path@entry=0x7fffffff9230 "/home/miro/.mutt/aliases", err=err@entry=0x7fffffffb3e0) at init.c:830
#8  0x00005555555a84a2 in parse_source (buf=0x7fffffffa340, s=0x7fffffffa280, data=<optimized out>, err=0x7fffffffb3e0) at init.c:1930
#9  0x00005555555a7d7f in mutt_parse_rc_line (line=<optimized out>, token=token@entry=0x7fffffffa340, err=err@entry=0x7fffffffb3e0) at init.c:3257
#10 0x00005555555a80b3 in mutt_parse_rc_line (err=0x7fffffffb3e0, token=0x7fffffffa340, line=<optimized out>) at init.c:3230
#11 0x00005555555a80b3 in source_rc (rcfile_path=<optimized out>, err=err@entry=0x7fffffffb3e0) at init.c:830
#12 0x00005555555a8eb8 in mutt_init (skip_sys_rc=<optimized out>, commands=0x7fffffffbf30) at init.c:3162
#13 0x0000555555571194 in main (argc=1, argv=0x7fffffffd628, envp=<optimized out>) at main.c:702
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

Arch Linux neomutt package <https://www.archlinux.org/packages/community/x86_64/neomutt/>:
```
[ALPM] upgraded neomutt (20180716-8 -> 20191025-1)
```

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

So this happens when we parse any ``alias`` found in configuration.

I've raised this in `#neomutt` and @flatcap managed to fix it in ``[devel/alias-group]`` which I've tested and can verify that problem went away.

**Comment by flatcap** [comment]
Fixed in f9b997d02
