### ISSUE TITLE
Segfault when StartTLS negotiation fails

### ISSUE THREAD

**Issue by dominikpaulus** [neomutt/neomutt#1886]
#860  Expected Behaviour

$ neomutt -f imap://myusername@mymailserver.tld/

where 'mymailserver.tld' refuses to negotiate StartTLS, should not crash.

## Actual Behaviour

Segmentation fault due to a double call to SSL_CTX_free().

## Steps to Reproduce

This happened after upgrading my mailserver to buster, and due to a configuration error, it refused to negotiate a TLS session using StartTLS. After that, any connect to that server using the above neomutt-command caused neomutt to segfault (reproducibly, always).

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
cc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -g -fvar-tracking-assignments -fdebug-prefix-map=/home/dominik/neomutt/trunk/src=/usr/src/debug -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

Full stacktrace of the crash:
```
#0  0x00007ffff7b6383e in OPENSSL_sk_free () at /usr/lib/libcrypto.so.1.1
#1  0x00007ffff7c93706 in SSL_CTX_free () at /usr/lib/libssl.so.1.1
#2  0x0000555555636134 in ssl_socket_close (conn=0x555555804430) at conn/ssl.c:1432
#3  0x0000555555636179 in ssl_socket_close_and_restore (conn=0x555555804430) at conn/ssl.c:652
#4  0x0000555555634289 in mutt_socket_close (conn=0x555555804430) at conn/socket.c:105
#5  0x00005555556283e8 in imap_close_connection (adata=0x5555557fa700) at imap/imap.c:943
#6  0x0000555555628581 in imap_open_connection (adata=0x5555557fa700) at imap/imap.c:928
#7  0x000055555562b475 in imap_login (adata=adata@entry=0x5555557fa700) at imap/imap.c:1897
#8  0x000055555562b6d4 in imap_ac_add (a=0x5555557fa300, m=0x5555557fa110) at imap/imap.c:1858
#9  0x00005555555bfa6e in mx_ac_add (a=0x5555557fa300, m=0x5555557fa110) at mx.c:1561
#10 0x00005555555a79a9 in parse_mailboxes (buf=0x7fffffffb3d0, s=0x7fffffffb310, data=<optimized out>, err=<optimized out>) at init.c:1380
#11 0x00005555555a8b5e in mutt_parse_rc_line (line=<optimized out>, token=token@entry=0x7fffffffb3d0, err=err@entry=0x7fffffffc470)
    at init.c:3257
#12 0x00005555555a8e7f in mutt_parse_rc_line (err=0x7fffffffc470, token=0x7fffffffb3d0, line=<optimized out>) at init.c:3230
#13 0x00005555555a8e7f in source_rc (rcfile_path=<optimized out>, err=err@entry=0x7fffffffc470) at init.c:830
#14 0x00005555555a9c18 in mutt_init (skip_sys_rc=<optimized out>, commands=0x7fffffffcfc0) at init.c:3162
#15 0x000055555557302d in main (argc=1, argv=0x7fffffffe6b8, envp=<optimized out>) at main.c:702
```

The initial error that caused the connection attempt to be aborted occured in conn/ssl.c, line 1221 ('err = SSL_connect(ssldata->ssl);'), calltrace to this point:
```
#0  0x0000555555636c84 in ssl_negotiate (ssldata=0x55555580a220, conn=0x555555804430) at conn/ssl.c:1180
#1  0x0000555555636c84 in ssl_setup (conn=conn@entry=0x555555804430) at conn/ssl.c:1323
#2  0x0000555555638695 in mutt_ssl_starttls (conn=0x555555804430) at conn/ssl.c:1451
#3  0x0000555555628500 in imap_open_connection (adata=0x5555557fa700) at imap/imap.c:889
[everything else as above]
```

This then causes a crash, as SSL_CTX_free() is both called in the goto-cascade in ssl_setup() in conn/ssl.c, as well as in conn_socket_close, which is called when ssl_setup() fails.

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @dominikpaulus 

I think I've found and fixed the problem.
Please can you give this branch a try: [[devel/ssl](https://github.com/neomutt/neomutt/tree/devel/ssl)].
