### ISSUE TITLE
Won't load IMAP folders

### ISSUE THREAD

**Issue by mkoskar** [neomutt/neomutt#1887]
## Expected Behaviour

IMAP folders are loaded.

## Actual Behaviour

IMAP folders are **not** loaded (browser is empty).

## Steps to Reproduce

1. Start ``neomutt``.
2. Press ``c`` (for ``<change-folder>``).
3. Press ``?`` (browser should open).
4. Press ``c`` (for ``<change-dir>``).
5. Press ``^U`` (i.e., remove the path).
6. Input IMAP root e.g., ``imaps://user@imap.gmail.com:993/``.
7. Press ``<Enter>``.

Now browser is empty and seemingly nothing happened, no messages displayed about connecting to IMAP server.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

Arch Linux neomutt package <https://www.archlinux.org/packages/community/x86_64/neomutt/>:
```
[ALPM] upgraded neomutt (20180716-8 -> 20191025-1)
```

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

When I do ``$ neomutt -f imaps://user@imap.gmail.com:993/``, IMAP works and I get INBOX loaded, then also browsing of IMAP folders works.

**Comment by nyc-tinker** [comment]
Don't know if this is related, but I get a core dump (segmentation fault) when trying to access an IMAP folder.  The above 'Extra Info' solution (specifying the imap server from the command line) allows me to access the folder, however.  mbox mailboxes (via offlineimap) work fine.

I am using ProtonMail, using bridge, accessing localhost without TLS.  Similarly, this only just happened after upgrading Arch Linux (and the glibc library, which is referenced in the core dump below).

```
> Oct 28 15:55:58 thinkarch systemd-coredump[7719]: Process 7714 (neomutt) of user 1000 dumped core.
>                                                   
> Stack trace of thread 7714:
> #0  0x0000561400251bbc n/a (neomutt)
> #1  0x0000561400271926 n/a (neomutt)
> #2  0x0000561400244af1 n/a (neomutt)
> #3  0x00007f69c1e56153 __libc_start_main (libc.so.6)
> #4  0x00005614002457ce n/a (neomutt)
```

**Comment by gahr** [comment]
I can reproduce this. You can work-around it by not going into folder list mode, i.e., remove steps 2 and 3 from your steps list above.

**Comment by Krakonos** [comment]
This kind of happens to me as well, but just after selecting the folder (regardless if that is done over 'c' and typing it in, the browser, or the sidebar), I am stuck with "Selecting FOLDERNAME..." and have to kill off mutt.

From the last update (neomutt in Arch linux repository), only inbox works properly.

I tried stracing neomutt and here is a snippet (I censored the write() call just to be sure, but it seems to be encrypted data):
```
rt_sigaction(SIGINT, {sa_handler=0x5650316a3940, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f38f14cefb0}, NULL, 8) = 0
stat("+kicad-dev", 0x7fff3297d610)      = -1 ENOENT (No such file or directory)
stat("imaps://krakonos@krakonos.org/INBOX", 0x7fff3297e550) = -1 ENOENT (No such file or directory)
write(1, "\r\33[38;5;7mMailbox is unchanged\33["..., 47) = 47
munmap(0x7f38eff5e000, 368640)          = 0
munmap(0x7f38efe71000, 307200)          = 0
nanosleep({tv_sec=1, tv_nsec=0}, 0x7fff3297e670) = 0
write(1, "\r\33[38;5;7mReading imaps://krakon"..., 65) = 65
write(1, "\r\33[38;5;7mSelecting \33[19P\33[71;23"..., 47) = 47
stat("/home/krakonos/postponed", {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
write(4, "===CENSORED==="..., 1149) = 1149
rt_sigaction(SIGINT, {sa_handler=0x5650316a3940, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f38f14cefb0}, NULL, 8) = 0
read(4, "\27\3\3\10s", 5)               = 5
read(4, "\277V\345g\320+*\326p;o-\313\34\316\33 \347\374\252\366\24\231|\r\31\263\207\35\222\234\277"..., 2163) = 2163
rt_sigaction(SIGINT, {sa_handler=0x5650316a3940, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f38f14cefb0}, NULL, 8) = 0
read(4, 
```

Here is a stacktrace when I try to use sidebar:
```(gdb) bt
#0  0x00007fad0416942c in read () at /usr/lib/libc.so.6
#1  0x00007fad044791c7 in  () at /usr/lib/libcrypto.so.1.1
#2  0x00007fad0447453a in  () at /usr/lib/libcrypto.so.1.1
#3  0x00007fad044733b4 in  () at /usr/lib/libcrypto.so.1.1
#4  0x00007fad044739a3 in BIO_read () at /usr/lib/libcrypto.so.1.1
#5  0x00007fad046c13a2 in  () at /usr/lib/libssl.so.1.1
#6  0x00007fad046c52fb in  () at /usr/lib/libssl.so.1.1
#7  0x00007fad046c2b91 in  () at /usr/lib/libssl.so.1.1
#8  0x00007fad046ca1b6 in  () at /usr/lib/libssl.so.1.1
#9  0x00007fad046d4f3d in  () at /usr/lib/libssl.so.1.1
#10 0x00007fad046d5044 in SSL_read () at /usr/lib/libssl.so.1.1
#11 0x000055b50b194d57 in ssl_socket_read (conn=<optimized out>, buf=<optimized out>, count=<optimized out>)
    at ../conn/ssl.c:1378
#12 0x000055b50b192bc5 in mutt_socket_readchar (conn=conn@entry=0x55b50c076bb0, c=c@entry=0x7fff09b13f47 "")
    at ../conn/socket.c:213
#13 0x000055b50b192d28 in mutt_socket_readln_d
    (buf=0x55b50c172440 "a0019 NO Mailbox doesn't exist: openocd (0.001 + 0.000 secs).", buflen=512, conn=0x55b50c076bb0, dbg=dbg@entry=5) at ../conn/socket.c:251
#14 0x000055b50b1833c0 in imap_cmd_step (adata=<optimized out>) at ../imap/command.c:1102
#15 0x000055b50b1833c0 in imap_cmd_step (adata=adata@entry=0x55b50c0766f0) at ../imap/command.c:1071
#16 0x000055b50b188318 in imap_mbox_open (m=0x55b50c16a980) at ../imap/imap.c:2010
#17 0x000055b50b11ea51 in mx_mbox_open (m=0x55b50c16a980, flags=<optimized out>) at ../mx.c:347
#18 0x000055b50b0faba2 in main_change_folder (menu=0x55b50f523fc0, op=op@entry=231, m=<optimized out>, 
    m@entry=0x55b50c16a980, buf=0x55b5109c9400 "imaps://krakonos.org/kicad-dev", buflen=<optimized out>, oldcount=oldcount@entry=0x7fff09b15220, index_hint=0x7fff09b15224) at ../index.c:751
#19 0x000055b50b0fbe6e in mutt_index_menu () at ../index.c:2366
#20 0x000055b50b0d2833 in main (argc=<optimized out>, argv=0x7fff09b18478, envp=<optimized out>) at ../main.c:1247
```
When running GDB, I noticed the string "NO Mailbox doesn't exist: openocd". Indeed, I don't have a mailbox of that name, so I deleted it from the "mailboxes" configuration (was the very last entry). Surprisingly, this fixed my issue and everything works again!

I hope it helps with the investigation.

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!
