### ISSUE TITLE
neomutt crashes trying to send prepared message from cli

### ISSUE THREAD

**Issue by sjbronner** [neomutt/neomutt#1943]
## Expected Behaviour

I was trying to use `neomutt` to send an e-mail from the command line (non-interactive).

## Actual Behaviour

`neomutt` experienced a segmentation fault.

If NeoMutt crashed, did your OS create a 'coredump' file?

Yes. You can view it here, along with an `strace`: https://gist.github.com/1f49fb3ef828e287a653410fa06a7f25

## Steps to Reproduce

I believe it only requires the following single command, although I can't discount the possibility of my environment being a factor:

```
neomutt -s 'test subject' waschtl@sbronner.com <<< 'Message text'
```

## How often does this happen?

Always

## When did it start to happen?

This is my first attempt to use `neomutt` this way. However, I also recently upgraded. So I can't really say.

## NeoMutt Version

```
NeoMutt 20191102
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-2-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info
--with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-sys
tem-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-un
ique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-functi
on --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/inclu
de/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-id
n2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTEN
SIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version:

  ArchLinux 2019-11-04

* Were you using multiple copies of NeoMutt at once?

  The error occurs whether another instance of `neomutt` is running or not. I tried both.

* Were you using 'screen' or 'tmux'?

  `tmux` and also directly in the terminal

* Is your email local (maildir) or remote (IMAP)?

  I suspect this couldn't possibly apply, since this bug report is only about sending e-mail. The e-mail was supposed to be sent via SMTP.

* Comment:

  I got the impression from the `strace` that `neomutt` was crashing while looking for an `nntp` server.

**Comment by flatcap** [comment]
Thanks for the debugging, @sjbronner, that lead me straight to the problem.
Refactoring some of the code, I accidentally put some GUI variables in a non-GUI place!

**Comment by Strahinja** [comment]
I am still having this problem. This is the debugging session (redacted my email):
```
$ LC_ALL=en_US.UTF-8 gdb neomutt
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from neomutt...
(gdb) run -B -s "Automated message" -- <snip@snip> <<<"Some text"
Starting program: /home/strajder/src/neomutt/neomutt -B -s "Automated message" -- <snip@snip> <<<"Some text"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
parse_uncolor (buf=0x555555751ea0, s=0x555555751ec0, c=0x0, err=0x7fffffffd2a0, uncolor=<optimized out>) at gui/color.c:859
859         c->defs[object] = A_NORMAL;
(gdb) bt
#0  parse_uncolor (buf=0x555555751ea0, s=0x555555751ec0, c=0x0, err=0x7fffffffd2a0, uncolor=<optimized out>) at gui/color.c:859
#1  0x0000555555597020 in mutt_parse_rc_buffer (line=0x555555751ec0, token=0x555555751ea0, err=err@entry=0x7fffffffd2a0) at init.c:1016
#2  0x0000555555597383 in mutt_parse_rc_buffer (line=<optimized out>, token=<optimized out>, err=err@entry=0x7fffffffd2a0) at init.c:1034
#3  0x000055555558172e in source_rc (rcfile_path=rcfile_path@entry=0x7fffffffb0f0 "/home/strajder/.config/mutt/colorrc", err=err@entry=0x7fffffffd2a0)
    at command_parse.c:215
#4  0x00005555555835e0 in parse_source (buf=0x555555751ee0, s=0x555555751f00, data=<optimized out>, err=0x7fffffffd2a0) at command_parse.c:1150
#5  0x0000555555597020 in mutt_parse_rc_buffer (line=0x555555751f00, token=0x555555751ee0, err=err@entry=0x7fffffffd2a0) at init.c:1016
#6  0x0000555555597383 in mutt_parse_rc_buffer (line=<optimized out>, token=<optimized out>, err=err@entry=0x7fffffffd2a0) at init.c:1034
#7  0x000055555558172e in source_rc (rcfile_path=<optimized out>, err=err@entry=0x7fffffffd2a0) at command_parse.c:215
#8  0x00005555555977e0 in mutt_init (cs=<optimized out>, skip_sys_rc=<optimized out>, commands=commands@entry=0x7fffffffd6e0) at init.c:911
#9  0x0000555555576046 in main (argc=2, argv=0x7fffffffdd78, envp=<optimized out>) at main.c:676
(gdb) display c
1: c = (struct Colors *) 0x0
(gdb)
```
It seems the execution doesn't even get to the line 847 from the e48d4aa26f076825b477d286e9053a2e3baaefea, the crash happens at `main.c:676`, assigning to `Colors` by reading a GUI startup file when executing a CLI command.
