### ISSUE TITLE
segfault in email_free when sending a mail

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1987]
## Expected Behaviour

Pressed `y` to send my mail.

## Actual Behaviour

```
(gdb) bt
#0  email_free (ptr=0x56156bf065e8) at email/email.c:48
#1  0x000056156aaf2926 in mx_fastclose_mailbox (m=m@entry=0x56156bf06410) at mx.c:432
#2  0x000056156aaf4483 in mx_mbox_close (ptr=ptr@entry=0x7ffc8577d9d8) at mx.c:593
#3  0x000056156ab16de5 in mutt_write_fcc (path=path@entry=0x7ffc8577df60 "imaps://mail.cock.li:993/Sent", e=e@entry=0x56156bf1ac80, msgid=msgid@entry=0x0, post=post@entry=false, fcc=fcc@entry=0x0, finalpath=finalpath@entry=0x7ffc85780080)
    at sendlib.c:3465
#4  0x000056156ab16f64 in mutt_write_multiple_fcc (path=<optimized out>, e=e@entry=0x56156bf1ac80, msgid=msgid@entry=0x0, post=post@entry=false, fcc=fcc@entry=0x0, finalpath=finalpath@entry=0x7ffc85780080) at sendlib.c:3228
#5  0x000056156ab0ced5 in save_fcc (e=0x56156bf1ac80, fcc=fcc@entry=0x7ffc85780090, clear_content=0x0, pgpkeylist=0x0, flags=flags@entry=3, finalpath=finalpath@entry=0x7ffc85780080) at send.c:1708
#6  0x000056156ab10586 in ci_send_message (flags=flags@entry=3, e_templ=<optimized out>, e_templ@entry=0x0, tempfile=tempfile@entry=0x0, ctx=0x56156bef4fe0, el=el@entry=0x7ffc857805c0) at send.c:2609
#7  0x000056156aafc0d7 in mutt_pager (banner=banner@entry=0x0, fname=<optimized out>, flags=flags@entry=66, extra=extra@entry=0x7ffc85780ff0) at pager.c:3266
#8  0x000056156aab3363 in mutt_display_message (win=<optimized out>, m=<optimized out>, e=0x56156bfb3310) at commands.c:361
#9  0x000056156aad36d3 in mutt_index_menu () at index.c:2436
#10 0x000056156aae3e7e in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1260
```

If NeoMutt crashed, did your OS create a 'coredump' file?
yea

## Steps to Reproduce

dunno

## How often does this happen?

dunno

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

git

## NeoMutt Version

```
NeoMutt 20191111-36-edfa04
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.11+ (x86_64)
ncurses: ncurses 6.1.20190609 (compiled with 6.1.20190609)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.13.1
hcache backends: bdb

Compiler:
Using built-in specs.
COLLECT_GCC=x86_64-pc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-8.3.0-r3/work/gcc-8.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 8.3.0-r3 p3' --enable-esp --enable-libstdcxx-time --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libmpx --disable-systemtap --enable-vtable-verify --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.3.0 (Gentoo Hardened 8.3.0-r3 p3) 

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --libdir=/usr/lib64 CCACHE=none --disable-doc --enable-nls --disable-notmuch --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -march=ivybridge -mtune=native -ftree-vectorize -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +sasl -smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Gentoo GNU/Linux
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
IMAP

**Comment by l29ah** [comment]
Seems to occur every time i'm trying to send a mail.

**Comment by flatcap** [comment]
Please can you give the branch [[devel/send]](https://github.com/neomutt/neomutt/tree/devel/send) a try.

**Comment by flatcap** [comment]
Sorry, slight change of plan.
I've merged the fix, as it's clearly a bug, to prevent other people being affected.
If this doesn't fix your problem, please re-open the bug and I'll keep looking.
Thanks.

**Comment by l29ah** [comment]
Now it's good, thank you.
