### ISSUE TITLE
Segfault on quit in tunnel_socket_close

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1989]
(This form seems weirdly backwards to me, but okay)

## Expected Behaviour

Quit neomutt.

## Actual Behaviour

A segfault!

```
Thread 1 "neomutt" received signal SIGSEGV, Segmentation fault.
tunnel_socket_close (conn=0x555555c9ffc0) at conn/tunnel.c:210
210	  close(tunnel->fd_read);
(gdb) bt
#0  0x0000555555641208 in tunnel_socket_close (conn=0x555555c9ffc0) at conn/tunnel.c:210
#1  0x000055555563c32a in imap_adata_free (ptr=0x555555c98510) at imap/util.c:83
#2  0x0000555555647399 in account_free (ptr=ptr@entry=0x7fffffffd368) at core/account.c:123
#3  0x00005555556479c8 in neomutt_account_remove (n=n@entry=0x555555714790, a=a@entry=0x0) at core/neomutt.c:119
#4  0x0000555555647a45 in neomutt_free (ptr=0x5555556c4af8 <NeoMutt>) at core/neomutt.c:70
#5  0x000055555557aad4 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1302

(gdb) bt full
(gdb) bt full
#0  0x0000555555641208 in tunnel_socket_close (conn=0x555555c9ffc0) at conn/tunnel.c:210
        tunnel = 0x0
        status = 21845
        __func__ = "tunnel_socket_close"
#1  0x000055555563c32a in imap_adata_free (ptr=0x555555c98510) at imap/util.c:83
        adata = 0x555555c9fb00
#2  0x0000555555647399 in account_free (ptr=ptr@entry=0x7fffffffd368) at core/account.c:123
        a = 0x555555c984e0
#3  0x00005555556479c8 in neomutt_account_remove (n=n@entry=0x555555714790, a=a@entry=0x0) at core/neomutt.c:119
        ev_a = {account = 0x555555c984e0}
        result = <optimized out>
        np = 0x555555c984e0
        tmp = 0x0
#4  0x0000555555647a45 in neomutt_free (ptr=0x5555556c4af8 <NeoMutt>) at core/neomutt.c:70
        n = 0x555555714790
#5  0x000055555557aad4 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1302
        subject = <optimized out>
        include_file = <optimized out>
        draft_file = <optimized out>
        new_magic = <optimized out>
        dlevel = <optimized out>
        dfile = <optimized out>
        cli_nntp = <optimized out>
        e = 0x0
        attach = {stqh_first = 0x0, stqh_last = 0x7fffffffd4c0}
        commands = {stqh_first = 0x0, stqh_last = 0x7fffffffd4d0}
        queries = {stqh_first = 0x0, stqh_last = 0x7fffffffd4e0}
        alias_queries = {stqh_first = 0x0, stqh_last = 0x7fffffffd4f0}
        cc_list = {stqh_first = 0x0, stqh_last = 0x7fffffffd500}
        bcc_list = {stqh_first = 0x0, stqh_last = 0x7fffffffd510}
        sendflags = <optimized out>
        flags = <optimized out>
        version = <optimized out>
        i = <optimized out>
        explicit_folder = <optimized out>
        dump_variables = <optimized out>
        hide_sensitive = <optimized out>
        batch_mode = <optimized out>
        edit_infile = <optimized out>
        test_config = <optimized out>
        double_dash = <optimized out>
        nargc = <optimized out>
        rc = 0
        repeat_error = <optimized out>
        folder = {data = 0x0, dptr = 0x0, dsize = 0}
        expanded_infile = {data = 0x0, dptr = 0x0, dsize = 0}
        tempfile = {data = 0x0, dptr = 0x0, dsize = 0}
        __func__ = "main"
        out = -874948143
        rc2 = <optimized out>
```

## Steps to Reproduce

1. `neomutt -f imaps://fridge/`
2. accept the SSL certificate despite name not matching (WHICH SHOULD NOT BE THERE, I'M USING AN SSH TUNNEL, WHAT SSL)
3. accept default username/blank password (THERE SHOULD BE NO PROMPTS FOR THESE, I'M USING AN SSH TUNNEL, WHAT USERNAME/PASSWORD)
4. ignore the connection error, see that the inbox is shown correctly
5. press `x` to exit
6. segfault!

My neomuttrc contains
```
folder-hook imaps://fridge/ 'set folder=imaps://fridge; source $HOME/.mutt/folders.work'
# folders.work sets $mbox, $postponetd, $record, $spoolfile,
# sets up mailboxes (including the infamous `unmailboxes *` at the start),
# sets up a few send-hooks and save-hooks, and sets up a few keyboard macros)

account-hook . 'unset tunnel'
account-hook imaps://fridge/ 'set tunnel="ssh -q -o ControlMaster=auto fridge /usr/lib/dovecot/imap"'
account-hook imaps://fridge/ 'set imap_delim_chars=/'
```

## How often does this happen?

Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?   I dunno?  I rarely use IMAP.  I'm quite certain the 2018 release did not have this problem.  I suppose I can bisect.

## NeoMutt Version

```
NeoMutt 20191111-39-6a98d5
Copyright (C) 1996-2016 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.3.0-23-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.12.0
hcache backends: tokyocabinet

Compiler:
cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version  Ubuntu 19.10
* Were you using multiple copies of NeoMutt at once?  technically yes but not really
* Were you using 'screen' or 'tmux'?  no
* Is your email local (maildir) or remote (IMAP)?  IMAP

**Comment by mgedmin** [comment]
I've tried git bisection, but it's hard (some versions segfault on startup, some versions ask IMAP credentials where they shouldn't and then quit instead of showing my inbox, etc).  I couldn't find where the segfault on exit was introduced, but the last actually working version was the parent of e46ba978910c911ec57aea7fb7735a5a941717c5.

e46ba978910c911ec57aea7fb7735a5a941717c5 segfaults on startup. Something like 20-40 commits later the segfault goes away and I start getting SSL confirmation prompts and PLAIN authentication failures.

On a grander scale, the last working release was neomutt-20180716.

**Comment by mgedmin** [comment]
Here's a [valgrind.log](https://github.com/neomutt/neomutt/files/3886978/valgrind.log) of the crash.  It's not very informative.

**Comment by gahr** [comment]
#1991 should cure the symptoms, although I don't know why you end up there with a NULL tunnel connection to begin with :/

**Comment by mgedmin** [comment]
The segfault is indeed gone!  I'll file a separate issue about mutt trying to talk to my IMAP server directly before using my tunnel configuration.
