### ISSUE TITLE
SIGSEGV when <entire-thread> with IMAP

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2030]
## Expected Behaviour

I (accidentally) executed `<entire-thread>` when connected with IMAP (as opposed to when using NeoMutt locally thanks to offlineimap). I would expect NeoMutt to give an error in this case.

## Actual Behaviour

NeoMutt had SIGSEGV. Backtrace below:

```
Error opening database at /imap.mail.ufl.edu:993//.notmuch: No such file or directory?
                                                                                      Thread 1 "neomutt" received signal SIGSEGV, Segmentation fault.
                                                                                                                                                     0x00005555555ac10e in mutt_index_menu () at index.c:2128
2128	          if (Context->mailbox->msg_count == 0)
(gdb) bt
#0  0x00005555555ac10e in mutt_index_menu () at index.c:2128
#1  0x00005555555c2cf8 in main (argc=1, argv=0x7fffffffdad8, envp=0x7fffffffdaf8) at main.c:1254
(gdb) 
```

## Steps to Reproduce

I just start NeoMutt with IMAP and run `:exec <entire-thread>` on any message.

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.0-24-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by flokli** [comment]
might be the a dup of https://github.com/neomutt/neomutt/issues/2010
