### ISSUE TITLE
Segfault in ssl_socket_poll

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#2058]
## Expected Behaviour

quit mutt

## Actual Behaviour

```
(gdb) bt
#0  0x0000561ce4e8fa10 in ssl_socket_poll (conn=0x561ce64a3660, wait_secs=15) at conn/ssl.c:1353
#1  0x0000561ce4e8dcd3 in mutt_socket_poll (conn=<optimized out>, wait_secs=<optimized out>) at conn/socket.c:196
#2  0x0000561ce4e81bb1 in imap_logout (adata=0x561ce64a31a0) at imap/imap.c:680
#3  0x0000561ce4e830fa in imap_logout_all () at imap/imap.c:705
#4  0x0000561ce4e16a79 in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1260
```

If NeoMutt crashed, did your OS create a 'coredump' file?
yeah

## Steps to Reproduce

dunno

## How often does this happen?

dunno

## When did it start to happen?

dunno

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.6+ (x86_64)
ncurses: ncurses 6.1.20190609 (compiled with 6.1.20190609)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.13.1
hcache backends: bdb

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --libdir=/usr/lib64 CCACHE=none --disable-doc --enable-nls --disable-notmuch --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -march=ivybridge -mtune=native -ftree-vectorize -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +sasl -smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by scottkosty** [comment]
@l29ah Can you reproduce on master or the newest release? There's been a lot of fixes since then that hopefully fixed it.
