### ISSUE TITLE
20161028 hdr_format_str, crash when deref'ing hdr

### ISSUE THREAD

**Issue by sthen** [neomutt/neomutt#220]
It looks like the changes in 20161028 may have moved the header formatting crash around but not fully resolved it yet - I hit this one after shutting down the IMAP server while displaying a message body:

```
Mailbox closedSegmentation fault (core dumped)
```

Here's the backtrace, though I think that (as with the previous backtrace I sent) it's of limited use because it only shows where hdr was accessed rather than where it might have been freed.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  hdr_format_str (dest=0x7f7ffffedc50 "", destlen=1024, col=0, cols=120, op=83 'S', src=0x1aa41a3a3362 " [%C/%T] %n (%l) %s", 
    prefix=0x7f7ffffee150 "", ifstring=0x7f7ffffee0d0 "", elsestring=0x7f7ffffee050 "B", data=140187732468752, flags=MUTT_FORMAT_MAKEPRINT)
    at hdrline.c:795
795       if (hdr->deleted)
(gdb) p *hdr
Cannot access memory at address 0x1aa3f183f100
(gdb) bt
#0  hdr_format_str (dest=0x7f7ffffedc50 "", destlen=1024, col=0, cols=120, op=83 'S', src=0x1aa41a3a3362 " [%C/%T] %n (%l) %s", 
    prefix=0x7f7ffffee150 "", ifstring=0x7f7ffffee0d0 "", elsestring=0x7f7ffffee050 "B", data=140187732468752, flags=MUTT_FORMAT_MAKEPRINT)
    at hdrline.c:795
#1  0x00001aa1b1079065 in mutt_FormatString (dest=0x7f7ffffee890 "N [9483/L] Mark Steward (23) Re: [uknot] sudo NOPASSWD straw poll", 
    destlen=479, col=0, cols=120, src=0x1aa41a3a3362 " [%C/%T] %n (%l) %s", callback=0x1aa1b10348d0 <hdr_format_str>, 
    data=140187732468752, flags=<optimized out>) at muttlib.c:1571
#2  0x00001aa1b1034360 in mutt_make_string_info (dst=0x7f7ffffedc50 "", dstlen=1024, cols=120, 
    s=0x53 <error: Cannot access memory at address 0x53>, hfi=<optimized out>, flags=<optimized out>) at hdrline.c:1052
#3  0x00001aa1b104c5dd in mutt_pager (banner=0x0, fname=<optimized out>, flags=66, extra=0x7f7ffffeef10) at pager.c:1951
#4  0x00001aa1b10123b9 in mutt_display_message (cur=0x1aa3f183f100) at commands.c:225
#5  0x00001aa1b101f658 in mutt_index_menu () at curs_main.c:1933
#6  0x00001aa1b103c593 in main (argc=1, argv=0x7f7fffff0c48) at main.c:906
```

```
NeoMutt 20161028 (1.7.1)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: OpenBSD 6.0 (amd64)
libidn: 1.33 (compiled with 1.33)
hcache backend: kyotocabinet 1.2.76

Compiler:
Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.0/4.2.1/specs
Target: amd64-unknown-openbsd6.0
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719 

Configure options: '--enable-compressed' '--enable-external_dotlock' '--disable-fcntl' '--enable-flock' '--enable-hcache' '--enable-imap' '--enable-nntp' '--disable-notmuch' '--enable-pop' '--enable-sidebar' '--enable-smtp' '--with-curses' '--with-docdir=/usr/local/share/doc/mutt' '--without-tokyocabinet' '--without-gdbm' '--with-idn' '--with-ssl' '--enable-gpgme' '--with-kyotocabinet' '--without-qdbm' '--prefix=/usr/local' '--sysconfdir=/etc/mutt' '--mandir=/usr/local/man' '--infodir=/usr/local/info' '--localstatedir=/var' '--disable-silent-rules' '--disable-gtk-doc' 'CC=cc' 'CFLAGS=-O2 -pipe -g' 'LDFLAGS=-L/usr/local/lib' 'CPPFLAGS=-I/usr/local/include'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -O2 -pipe -g

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME +CRYPT_BACKEND_GPGME 
-DEBUG +DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET +HAVE_GETADDRINFO 
+HAVE_GETSID +HAVE_ICONV +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR 
+HAVE_LIBIDN +HAVE_META +HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS +USE_COMPRESSED -USE_DOTLOCK 
-USE_FCNTL +USE_FLOCK -USE_FMEMOPEN -USE_GNU_REGEX -USE_GSS +USE_HCACHE 
+USE_IMAP -USE_NOTMUCH +USE_NNTP +USE_POP -USE_SASL -USE_SETGID +USE_SIDEBAR 
+USE_SMTP -USE_SSL_GNUTLS +USE_SSL_OPENSSL 
-DOMAIN
-MIXMASTER
ISPELL="/usr/local/bin/ispell"
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/mutt"
SYSCONFDIR="/etc/mutt"
EXECSHELL="/bin/sh"

patch-attach-headers-color-neomutt
patch-compose-to-sender-neomutt
patch-compress-neomutt
patch-cond-date-neomutt
patch-encrypt-to-self-neomutt
patch-fmemopen-neomutt
patch-forgotten-attachments-neomutt
patch-ifdef-neomutt
patch-index-color-neomutt
patch-initials-neomutt
patch-keywords-neomutt
patch-kyoto-neomutt
patch-limit-current-thread-neomutt
patch-lmdb-neomutt
patch-multiple-fcc-neomutt
patch-nested-if-neomutt
patch-new-mail-neomutt
patch-nntp-neomutt
patch-notmuch-neomutt
patch-progress-neomutt
patch-quasi-delete-neomutt
patch-reply-with-xorig-neomutt
patch-sensible-browser-neomutt
patch-sidebar-neomutt
patch-skip-quoted-neomutt
patch-smime-encrypt-self-neomutt
patch-status-color-neomutt
patch-timeout-neomutt
patch-tls-sni-neomutt

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by flatcap** [comment]
*sigh*
Thanks for the bug report @sthen.
Well at least I know the code quite well now :-)

**Comment by gahr** [comment]
@sthen  Could you please try and see whether you can reproduce with a newer version?

**Comment by flatcap** [comment]
This no longer seems to be reproduceable.
