### ISSUE TITLE
SIGSEGV on master when trying to compose a message

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2213]
## Expected Behaviour

Compose a message.

## Actual Behaviour

SIGSEGV.

## Steps to Reproduce

Press 'm', then enter to address and subject. After entering the subject I get the crash. Here is the backtrace:

```
(gdb) bt
#0  0x00005555555f775c in convert_file_from_to (fp=0x5555556f22d0, fromcodes=0x555555838c80 "utf-8", tocodes=0x555555722830, fromcode=0x7fffffff9d78, tocode=0x7fffffff9d80, info=0x555555845440) at sendlib.c:986
#1  0x00005555555f7c11 in mutt_get_content_info (fname=0x5555558782b0 "/home/scott/mutt_tmp_sk/neomutt-tallinn-1000-6967-8216060766004769664", b=0x5555558890c0) at sendlib.c:1073
#2  0x00005555555f952e in mutt_update_encoding (a=0x5555558890c0) at sendlib.c:1500
#3  0x00005555555f3efa in ci_send_message (flags=0, e_templ=0x555555871f70, tempfile=0x0, ctx=0x555555859ad0, el=0x0) at send.c:2231
#4  0x00005555555a904b in mutt_index_menu (dlg=0x555555845b30) at index.c:3507
#5  0x00005555555b6659 in main (argc=1, argv=0x7fffffffdb88, envp=0x7fffffffdb98) at main.c:1192
```

## How often does this happen?

- Always

## When did it start to happen?

A bisect leads to cabf7002.

## NeoMutt Version

```
NeoMutt 20200320-25-744506
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.0-42-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1c  28 May 2019
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua -lz4 +meta -mixmaster +nls +notmuch +openssl +pgp +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

maildir

**Comment by flatcap** [comment]
Sorry about that.  The changes weren't ready.
I've reverted the commit.
