### ISSUE TITLE
SIGABRT when closing large IMAP folder

### ISSUE THREAD

**Issue by sruffell** [neomutt/neomutt#2550]
My LKML folder on my IMAP server has 397K messages in it.  When I open this folder and then try to shut down, neomutt crashes with a SIGABRT.

## Expected Behaviour

I would expect neomutt to update the flags and close without error.

## Actual Behaviour

Long delay, followed by the following prompt `Error saving flags. Close anyway? ([no]/yes):` .  When I hit `y`, neomutt then instantly crashes with the following printed:

```
double free or corruption (!prev)
Aborted (core dumped)
```

## Steps to Reproduce

1. Run `neomutt -f +lkml` to open my LKML folder hosted by Gmail
2. Enter `q` to quit neomutt.

## How often does this happen?

It happens repeatedly.

## When did it start to happen?

I cannot say, since I only just recently tried to use neomutt with the large IMAP folders (normally I use local maildirs)

## NeoMutt Version

```
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.15.0-112-generic (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1  11 Sep 2018
storage: tokyocabinet

Configure options: --prefix=/home/sruffell --ssl --sqlite --tokyocabinet --sasl

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/home/sruffell/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/home/sruffell/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/home/sruffell/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

I haven't spent any extra time troubleshooting, but I was able to collect this backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff651a8b1 in __GI_abort () at abort.c:79
#2  0x00007ffff6563907 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6690dfa "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff656a97a in malloc_printerr (str=str@entry=0x7ffff6692af0 "double free or corruption (!prev)") at malloc.c:5350
#4  0x00007ffff6571ef4 in _int_free (have_lock=0, p=0x555555a13310, av=0x7ffff68c5c40 <main_arena>) at malloc.c:4281
#5  __GI___libc_free (mem=0x555555a13320) at malloc.c:3124
#6  0x0000555555645c49 in mutt_mem_free (ptr=0x7ffff4239010) at mutt/memory.c:75
#7  0x0000555555632750 in email_free (ptr=<optimized out>) at email/email.c:61
#8  0x000055555562b4a9 in mailbox_free (ptr=0x5555559c3360) at core/mailbox.c:73
#9  0x000055555562b2e5 in account_mailbox_remove (a=a@entry=0x555555992950, m=m@entry=0x0) at core/account.c:111
#10 0x000055555562b36f in account_free (ptr=ptr@entry=0x7fffffffdc18) at core/account.c:136
#11 0x000055555562ba1d in neomutt_account_remove (n=n@entry=0x5555558b58b0, a=a@entry=0x0) at core/neomutt.c:120
#12 0x000055555562ba90 in neomutt_free (ptr=0x55555589fd48 <NeoMutt>) at core/neomutt.c:71
#13 0x000055555556f95c in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1273
```

**Comment by sruffell** [comment]
I'm not sure what the problem was, but I noticed recently that it wasn't crashing anymore while closing the folder. I did update my system where I run neomutt to Ubuntu 20.04 and neomutt to 20200925, but I'm not too concerned about trying to reproduce this specific crash.

Currently I'm running:
```
$ neomutt -v
NeoMutt 20200925
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-53-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
storage: tokyocabinet

Configure options: --prefix=/home/sruffell --ssl --sqlite --tokyocabinet --sasl

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/home/sruffell/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/home/sruffell/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/home/sruffell/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

and my folder still has 411K messages:

```
---NeoMutt: =lkml [Msgs:411310 4203M]---(threads/last-date-received)----------------------------------------------(end)---
```

So closing, but I'll reopen if I see this again in case it helps anyone else.
