### ISSUE TITLE
neomutt segfaults on U*<CR>

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#2653]
## Expected Behaviour

`U*`

## Actual Behaviour

```
#0  0x00007fef747b6a9f in ?? ()
#1  0x0000000000000000 in ?? ()
```

If NeoMutt crashed, did your OS create a 'coredump' file?
yup

## How often does this happen?

- Always

## When did it start to happen?

dunno

## NeoMutt Version

```
NeoMutt 20200821-88-f8d76b
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.8.1+ (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.36 (compiled with 1.36)
GPGME: 1.14.0
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
storage: bdb

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --with-sysroot=/ --libdir=/usr/lib64 CCACHE=none --disable-doc --enable-nls --disable-notmuch --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -march=ivybridge -mtune=native -ftree-vectorize -malign-data=cacheline -mtls-dialect=gnu2 -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I//usr/include -DNCURSES_WIDECHAR -I/include -I//usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex +sasl 
  -smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version
gentoo
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
local

**Comment by gahr** [comment]
The root cause is an invalid regular expression: you want `U .*`. Additionally, NeoMutt is not correctly handling the failure to compile the regex.

**Comment by gahr** [comment]
Can you please give the branch devel/issue-2653 a try?
