### ISSUE TITLE
Segfault when query inside query window

### ISSUE THREAD

**Issue by nblock** [neomutt/neomutt#2860]
## Expected Behaviour
A new query inside the query result window should not crash but display an empty query result window instead.

## Actual Behaviour

Neomutt crashes with SIGSEGV when a new query is started inside the query result window and the search term can't be found by the query program.

## Steps to Reproduce

* Open neomutt
* Press `Q` to start a query and enter some string
* The query result window displays matches
* Inside the query result windows, press `Q` again
* Enter a search term that can't be found
* neomutt crashes with SIGSEGV

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.7-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.15.1
GnuTLS: 3.7.1
libnotmuch: 5.3.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/build/neomutt/src=/usr/src/debug -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Backtrace
Rebuilt the Arch package with debug symbols and `make EXTRA_CFLAGS="-g -O0"` and ran the following:

```bash
gdb neomutt
r -F neomuttrc
(follow steps to reproduce)
bt
```

Backtrace:
```
#0  0x000055555567a177 in query_format_str
    (buf=0x7fffffff9fc0 "", buflen=1024, col=0, cols=179, op=99 'c', src=0x7fffffff9ec3 " %t %-25.25n %-25.25a | %e", prec=0x7fffffff9dc0 "3", if_str=0x7fffffff9e40 "", else_str=0x7fffffffa3c0 "\260\252\377\377\377\177", data=0, flags=16 '\020') at alias/dlgquery.c:143
#1  0x00005555555bb7f6 in mutt_expando_format
    (buf=0x7fffffffa8a0 "", buflen=1023, col=0, cols=179, src=0x7fffffff9ec3 " %t %-25.25n %-25.25a | %e", callback=0x55555567a0f4 <query_format_str>, data=0, flags=16 '\020')
    at muttlib.c:1214
#2  0x000055555567a71d in query_make_entry (buf=0x7fffffffa8a0 "", buflen=1024, menu=0x5555557696b0, line=0) at alias/dlgquery.c:209
#3  0x00005555555b5460 in make_entry (buf=0x7fffffffa8a0 "", buflen=1024, menu=0x5555557696b0, i=0) at menu.c:321
#4  0x00005555555b5716 in menu_redraw_index (menu=0x5555557696b0) at menu.c:393
#5  0x00005555555b7a40 in menu_redraw (menu=0x5555557696b0) at menu.c:1291
#6  0x00005555555b7b5d in mutt_menu_loop (menu=0x5555557696b0) at menu.c:1333
#7  0x000055555567ae93 in dlg_select_query (buf=0x7fffffffaf90 "foonope", buflen=256, all=0x7fffffffaf80, retbuf=false, sub=0x555555795f10) at alias/dlgquery.c:349
#8  0x000055555567c0a6 in query_index (sub=0x555555795f10) at alias/dlgquery.c:666
#9  0x00005555555a5d0b in mutt_index_menu (dlg=0x555555887020) at index.c:3263
#10 0x00005555555b4b96 in main (argc=1, argv=0x7fffffffe0c8, envp=0x7fffffffe0e8) at main.c:1238
```

## Files to reproduce
All files are stored in `~/tmp/neomutt`.

neomuttrc:
```
set folder = "~/tmp/neomutt/mail"
set query_command = "~/tmp/neomutt/query.sh %s"
```

query.sh:
```bash
#!/bin/sh

echo "Search results for query »$1«:"
grep -i "$1" ~/tmp/neomutt/*.alias
```

sent.alias (field separator is `tab`):
```
foo@example.com	Foo	Sent
bar@example.com	Bar	Sent
someone.else@example.com	Someone Else	Sent
```

## Extra Info
* Operating System and its version: Arch, latest as of 2021-03-21
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by flatcap** [comment]
Thanks for a perfect bug report!
I've fixed the problem in 9b6660fb443f97bb378702c4008842e38442b3eb.
