### ISSUE TITLE
ASAN reported memory leak

### ISSUE THREAD

**Issue by ngortheone** [neomutt/neomutt#2884]
How to reproduce:

1. Start neomutt
2. while in index do `exec view-raw-message` on any message
3. close your EDITOR, you should pop back to neomutt index
4. exit neomott

```
=================================================================
==1190179==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 272 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44d963c3 in mailbox_new core/mailbox.c:54
    #3 0x55cf44bdab4d in mx_path_resolve /usr/local/src/github.com/neomutt/neomutt/mx.c:1711
    #4 0x55cf44b52b49 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:73
    #5 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #6 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #7 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #8 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44d9645f in mailbox_new core/mailbox.c:60
    #3 0x55cf44bdab4d in mx_path_resolve /usr/local/src/github.com/neomutt/neomutt/mx.c:1711
    #4 0x55cf44b52b49 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:73
    #5 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #6 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #7 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #8 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8bf8 in realloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafbf8)
    #1 0x55cf44df15a9 in mutt_mem_realloc mutt/memory.c:131
    #2 0x55cf44dd3cb6 in mutt_buffer_alloc mutt/buffer.c:282
    #3 0x55cf44dd2f8b in mutt_buffer_addstr_n mutt/buffer.c:105
    #4 0x55cf44dd3963 in mutt_buffer_addstr mutt/buffer.c:229
    #5 0x55cf44dd3e25 in mutt_buffer_strcpy mutt/buffer.c:315
    #6 0x55cf44bdaba9 in mx_path_resolve /usr/local/src/github.com/neomutt/neomutt/mx.c:1713
    #7 0x55cf44b52b49 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:73
    #8 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #9 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #10 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #11 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 100 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44d964d5 in mailbox_new core/mailbox.c:61
    #3 0x55cf44bdab4d in mx_path_resolve /usr/local/src/github.com/neomutt/neomutt/mx.c:1711
    #4 0x55cf44b52b49 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:73
    #5 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #6 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #7 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #8 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 57 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351e93327 in __interceptor_strdup (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0x5a327)
    #1 0x55cf44dfda02 in mutt_str_dup mutt/string.c:375
    #2 0x55cf44dfde85 in mutt_str_replace mutt/string.c:451
    #3 0x55cf44bd9ac1 in mx_path_canon2 /usr/local/src/github.com/neomutt/neomutt/mx.c:1516
    #4 0x55cf44bdac1f in mx_path_resolve /usr/local/src/github.com/neomutt/neomutt/mx.c:1715
    #5 0x55cf44b52b49 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:73
    #6 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #7 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #8 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #9 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44da9903 in cs_subset_new config/subset.c:136
    #3 0x55cf44d973b8 in mailbox_set_subset core/mailbox.c:226
    #4 0x55cf44d95a34 in account_mailbox_add core/account.c:77
    #5 0x55cf44bdaf8f in mx_ac_add /usr/local/src/github.com/neomutt/neomutt/mx.c:1795
    #6 0x55cf44bd0461 in mx_mbox_ac_link /usr/local/src/github.com/neomutt/neomutt/mx.c:283
    #7 0x55cf44bd08be in mx_mbox_open /usr/local/src/github.com/neomutt/neomutt/mx.c:327
    #8 0x55cf44b52b88 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:74
    #9 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #10 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #11 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #12 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44df16a4 in notify_new mutt/notify.c:51
    #3 0x55cf44da9ae4 in cs_subset_new config/subset.c:156
    #4 0x55cf44d973b8 in mailbox_set_subset core/mailbox.c:226
    #5 0x55cf44d95a34 in account_mailbox_add core/account.c:77
    #6 0x55cf44bdaf8f in mx_ac_add /usr/local/src/github.com/neomutt/neomutt/mx.c:1795
    #7 0x55cf44bd0461 in mx_mbox_ac_link /usr/local/src/github.com/neomutt/neomutt/mx.c:283
    #8 0x55cf44bd08be in mx_mbox_open /usr/local/src/github.com/neomutt/neomutt/mx.c:327
    #9 0x55cf44b52b88 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:74
    #10 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #11 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #12 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #13 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44df16a4 in notify_new mutt/notify.c:51
    #3 0x55cf44d963d8 in mailbox_new core/mailbox.c:57
    #4 0x55cf44bdab4d in mx_path_resolve /usr/local/src/github.com/neomutt/neomutt/mx.c:1711
    #5 0x55cf44b52b49 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:73
    #6 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #7 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #8 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #9 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f7351ee8a0f in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libasan.so.6+0xafa0f)
    #1 0x55cf44df1328 in mutt_mem_calloc mutt/memory.c:55
    #2 0x55cf44df2214 in notify_observer_add mutt/notify.c:189
    #3 0x55cf44bd071b in mx_mbox_open /usr/local/src/github.com/neomutt/neomutt/mx.c:316
    #4 0x55cf44b52b88 in ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:74
    #5 0x55cf44b547ed in mutt_ev_message /usr/local/src/github.com/neomutt/neomutt/editmsg.c:288
    #6 0x55cf44c26a96 in mutt_index_menu index/index.c:3384
    #7 0x55cf44b9d36d in main /usr/local/src/github.com/neomutt/neomutt/main.c:1261
    #8 0x7f7351be9e39 in __libc_start_main (/lib64/libc.so.6+0x23e39)

SUMMARY: AddressSanitizer: 861 byte(s) leaked in 9 allocation(s).
```

**Comment by ebblake** [comment]
FWIW, I'm still seeing it on commit aafbf5a06 (I haven't tried applying the PR to see if that helps)
```

=================================================================
==598939==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 272 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x6d77f5 in mailbox_new core/mailbox.c:70
    #3 0x4b8c58 in mx_path_resolve /home/eblake/neomutt/mx.c:1677
    #4 0x4b8f78 in mx_resolve /home/eblake/neomutt/mx.c:1748
    #5 0x4870ec in main /home/eblake/neomutt/main.c:1238
    #6 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x6d7891 in mailbox_new core/mailbox.c:76
    #3 0x4b8c58 in mx_path_resolve /home/eblake/neomutt/mx.c:1677
    #4 0x4b8f78 in mx_resolve /home/eblake/neomutt/mx.c:1748
    #5 0x4870ec in main /home/eblake/neomutt/main.c:1238
    #6 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3cb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x730101 in mutt_mem_realloc mutt/memory.c:131
    #2 0x713bf0 in mutt_buffer_alloc mutt/buffer.c:282
    #3 0x712f90 in mutt_buffer_addstr_n mutt/buffer.c:105
    #4 0x7138d5 in mutt_buffer_addstr mutt/buffer.c:229
    #5 0x713d5f in mutt_buffer_strcpy mutt/buffer.c:315
    #6 0x4b8cb4 in mx_path_resolve /home/eblake/neomutt/mx.c:1679
    #7 0x4b8f78 in mx_resolve /home/eblake/neomutt/mx.c:1748
    #8 0x4870ec in main /home/eblake/neomutt/main.c:1238
    #9 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 100 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x6d7907 in mailbox_new core/mailbox.c:77
    #3 0x4b8c58 in mx_path_resolve /home/eblake/neomutt/mx.c:1677
    #4 0x4b8f78 in mx_resolve /home/eblake/neomutt/mx.c:1748
    #5 0x4870ec in main /home/eblake/neomutt/main.c:1238
    #6 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x6ea131 in cs_subset_new config/subset.c:148
    #3 0x6d87a4 in mailbox_set_subset core/mailbox.c:243
    #4 0x6d6c41 in account_mailbox_add core/account.c:77
    #5 0x4b9094 in mx_ac_add /home/eblake/neomutt/mx.c:1761
    #6 0x4af1b6 in mx_mbox_ac_link /home/eblake/neomutt/mx.c:282
    #7 0x4af41c in mx_mbox_open /home/eblake/neomutt/mx.c:318
    #8 0x4871d0 in main /home/eblake/neomutt/main.c:1240
    #9 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x5ca8bf in maildir_mdata_new maildir/mdata.c:49
    #3 0x5c4dea in maildir_read_dir maildir/maildir.c:688
    #4 0x5c6fee in maildir_mbox_open maildir/maildir.c:1094
    #5 0x4afd16 in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #6 0x4871d0 in main /home/eblake/neomutt/main.c:1240
    #7 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x7301f0 in notify_new mutt/notify.c:62
    #3 0x6d780a in mailbox_new core/mailbox.c:73
    #4 0x4b8c58 in mx_path_resolve /home/eblake/neomutt/mx.c:1677
    #5 0x4b8f78 in mx_resolve /home/eblake/neomutt/mx.c:1748
    #6 0x4870ec in main /home/eblake/neomutt/main.c:1238
    #7 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x7301f0 in notify_new mutt/notify.c:62
    #3 0x6ea310 in cs_subset_new config/subset.c:168
    #4 0x6d87a4 in mailbox_set_subset core/mailbox.c:243
    #5 0x6d6c41 in account_mailbox_add core/account.c:77
    #6 0x4b9094 in mx_ac_add /home/eblake/neomutt/mx.c:1761
    #7 0x4af1b6 in mx_mbox_ac_link /home/eblake/neomutt/mx.c:282
    #8 0x4af41c in mx_mbox_open /home/eblake/neomutt/mx.c:318
    #9 0x4871d0 in main /home/eblake/neomutt/main.c:1240
    #10 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fc5e967 in strdup (/lib64/libasan.so.6+0x59967)
    #1 0x73ce8b in mutt_str_dup mutt/string.c:375
    #2 0x73d2e7 in mutt_str_replace mutt/string.c:451
    #3 0x4b7c52 in mx_path_canon2 /home/eblake/neomutt/mx.c:1482
    #4 0x4b8d26 in mx_path_resolve /home/eblake/neomutt/mx.c:1681
    #5 0x4b8f78 in mx_resolve /home/eblake/neomutt/mx.c:1748
    #6 0x4870ec in main /home/eblake/neomutt/main.c:1238
    #7 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x730fc1 in notify_observer_add mutt/notify.c:210
    #3 0x507378 in ibar_index_observer index/ibar.c:224
    #4 0x7306f4 in send mutt/notify.c:136
    #5 0x730d99 in notify_send mutt/notify.c:175
    #6 0x50547c in index_shared_data_set_context index/shared_data.c:206
    #7 0x4ea1ba in mutt_index_menu index/dlg_index.c:1137
    #8 0x487540 in main /home/eblake/neomutt/main.c:1258
    #9 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fa57fcb3af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x72fe93 in mutt_mem_calloc mutt/memory.c:55
    #2 0x730fc1 in notify_observer_add mutt/notify.c:210
    #3 0x43419e in ctx_new /home/eblake/neomutt/context.c:89
    #4 0x4ea1a5 in mutt_index_menu index/dlg_index.c:1137
    #5 0x487540 in main /home/eblake/neomutt/main.c:1258
    #6 0x7fa57f293b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

SUMMARY: AddressSanitizer: 865 byte(s) leaked in 11 allocation(s).

```
