### ISSUE TITLE
Segmentation fault when trying to send a message from CLI

### ISSUE THREAD

**Issue by Strahinja** [neomutt/neomutt#2909]
## Expected Behaviour

I was trying to use neomutt to send an email in non-interactive mode (CLI).

## Actual Behaviour

The program aborted with a segmentation fault.

### If NeoMutt crashed, did your OS create a 'coredump' file?

Yes, here (gzipped):
[core.4225.gz](https://github.com/neomutt/neomutt/files/6350348/core.4225.gz)

## Steps to Reproduce

Run:
```
$ neomutt -s "Test message" - email@domain.org <<<"Test message body"
Segmentation fault
```

## How often does this happen?

- Always

## When did it start to happen?

First time using this feature.

## NeoMutt Version

```
NeoMutt 20210205-255-fb9b7a
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.14-artix1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.15.1
GnuTLS: 3.7.1
libnotmuch: 5.3.0
PCRE2: 10.36 2020-12-04
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --with-ssl=/usr --with-gnutls=/usr --lua --notmuch --disable-idn --idn2 --kyotocabinet --gdbm --bdb --pcre2 --sqlite --lz4 --lmdb --zlib --zstd --gpgme --mixmaster --autocrypt --with-gss=/usr --gss --sasl

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pcre2 +pgp +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

My `~/.config/mutt/muttrc` sources [`~/.config/mutt/colorrc`](https://git.sr.ht/~strahinja/dotfiles/tree/master/item/mutt/colorrc), which contains a number of lines setting colors in my client. This file seems to get parsed anyway, even when starting neomutt in non-interactive mode from the command line.

Also see my comment here: https://github.com/neomutt/neomutt/issues/1943#issuecomment-823332818

* Operating System and its version? Latest Artix GNU/Linux (kernel 5.11.14)
* Were you using multiple copies of NeoMutt at once? No.
* Were you using 'screen' or 'tmux'? tmux
* Is your email local (maildir) or remote (IMAP)? Not relevant here because I was trying to send messages through SMTP, but I have local mailboxes synced with mbsync from IMAP.

**Comment by gahr** [comment]
Try with two dashes: 
```
neomutt -s "Test message" -- email@domain.org <<<"Test message body"
```

I suppose `<<<` is the bash equivalent of

```
echo "Test message body" | neomutt -s "Test message" -- email@domain.org
```

**Comment by Strahinja** [comment]
> Try with two dashes:
> 
> ```
> neomutt -s "Test message" -- email@domain.org <<<"Test message body"
> ```

I tried that as well, with the same result. 

> 
> I suppose `<<<` is the bash equivalent of
> 
> ```
> echo "Test message body" | neomutt -s "Test message" -- email@domain.org
> ```

Yes. I also tried with redirection and here-doc `<<EOT`, and this segmentation fault is unrelated. See my comment here: https://github.com/neomutt/neomutt/issues/1943#issuecomment-823332818

**Comment by gahr** [comment]
Can you post a backtrace of running `neomutt -s "Test message" -- email@domain.org <<<"Test message body"`? I can't read your core file on my system.

**Comment by Strahinja** [comment]
Of course. I already posted it in the linked comment, but here it is again:
```
$ gdb neomutt
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from neomutt...
(gdb) run -s "Test message" -- email@domain.org <<<"Test message body"
Starting program: /usr/bin/neomutt -s "Test message" -- email@domain.org <<<"Test message body"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
parse_uncolor (buf=0x55555575d6e0, s=0x55555575d700, c=0x0, err=0x7fffffffd560, uncolor=<optimized out>) at gui/color.c:859
859         c->defs[object] = A_NORMAL;
(gdb) bt
#0  parse_uncolor (buf=0x55555575d6e0, s=0x55555575d700, c=0x0, err=0x7fffffffd560, uncolor=<optimized out>) at gui/color.c:859
#1  0x00005555555991d0 in mutt_parse_rc_buffer (line=0x55555575d700, token=0x55555575d6e0, err=err@entry=0x7fffffffd560) at init.c:1014
#2  0x0000555555599533 in mutt_parse_rc_buffer (line=<optimized out>, token=<optimized out>, err=err@entry=0x7fffffffd560) at init.c:1032
#3  0x0000555555583a0e in source_rc (rcfile_path=rcfile_path@entry=0x7fffffffb3b0 "/home/strajder/.config/mutt/colorrc", err=err@entry=0x7fffffffd560) at command_parse.c:215
#4  0x00005555555858c0 in parse_source (buf=0x55555575d720, s=0x55555575d740, data=<optimized out>, err=0x7fffffffd560) at command_parse.c:1150
#5  0x00005555555991d0 in mutt_parse_rc_buffer (line=0x55555575d740, token=0x55555575d720, err=err@entry=0x7fffffffd560) at init.c:1014
#6  0x0000555555599533 in mutt_parse_rc_buffer (line=<optimized out>, token=<optimized out>, err=err@entry=0x7fffffffd560) at init.c:1032
#7  0x0000555555583a0e in source_rc (rcfile_path=<optimized out>, err=err@entry=0x7fffffffd560) at command_parse.c:215
#8  0x0000555555599990 in mutt_init (cs=<optimized out>, skip_sys_rc=<optimized out>, commands=commands@entry=0x7fffffffd9a0) at init.c:909
#9  0x0000555555578246 in main (argc=2, argv=0x7fffffffe038, envp=<optimized out>) at main.c:675
(gdb) l
854           (object != MT_COLOR_INDEX_AUTHOR) && (object != MT_COLOR_INDEX_FLAGS) &&
855           (object != MT_COLOR_INDEX_SUBJECT) && (object != MT_COLOR_INDEX_TAG) &&
856           (object != MT_COLOR_STATUS))
857       {
858         // Simple colours
859         c->defs[object] = A_NORMAL;
860
861         struct EventColor ec = { object };
862         notify_send(c->notify, NT_COLOR, NT_COLOR_RESET, &ec);
863         return MUTT_CMD_SUCCESS;
(gdb)
```

**Comment by gahr** [comment]
ok sorry I got confused, I thought you wanted to track another problem here, but instead you're simply re-stating what you already specified in #1943, right?

**Comment by Strahinja** [comment]
Yes. Since that issue is closed, I thought I might need to open a separate issue. If that was wrong, feel free to close this issue and reopen the existing one. The issues are the same in essence, it's just that the existing [fix](https://github.com/neomutt/neomutt/commit/e48d4aa26f076825b477d286e9053a2e3baaefea) isn't enough to fix it.

**Comment by gahr** [comment]
Thanks for the clarification!
