### ISSUE TITLE
Segmentation fault in msg_search() when starting

### ISSUE THREAD

**Issue by ehabkost** [neomutt/neomutt#2915]
## Actual Behaviour

Segmentation fault when starting neomutt, after upgrading to latest git (commit cd15d4e6ec3467d36c9cd6cc146ea6a64bb94267).

```
Sorting mailbox...
                  Program received signal SIGSEGV, Segmentation fault.
                                                                      0x0000000000486a6a in msg_search (pat=0x715f30, m=0x735ff0, e=0xde0610, msg=0x0) at pattern/exec.c:132
132         s.fp_in = msg->fp;
Missing separate debuginfos, use: dnf debuginfo-install glib2-2.66.8-1.fc33.x86_64 gmime30-3.2.7-3.fc33.x86_64 gpgme-1.14.0-2.fc33.x86_64 libassuan-2.5.3-4.fc33.x86_64 libblkid-2.36.1-1.fc33.x86_64 libffi-3.1-26.fc33.x86_64 libgcc-10.2.1-9.fc33.x86_64 libgpg-error-1.41-1.fc33.x86_64 libidn-1.36-1.fc33.x86_64 libmount-2.36.1-1.fc33.x86_64 libselinux-3.1-2.fc33.x86_64 libstdc++-10.2.1-9.fc33.x86_64 libtalloc-2.3.1-5.fc33.x86_64 libuuid-2.36.1-1.fc33.x86_64 ncurses-libs-6.2-3.20200222.fc33.x86_64 notmuch-0.31.3-2.fc33.x86_64 pcre-8.44-2.fc33.x86_64 pcre2-10.36-4.fc33.x86_64 sssd-client-2.4.2-2.fc33.x86_64 xapian-core-libs-1.4.17-1.fc33.x86_64 zlib-1.2.11-23.fc33.x86_64
(gdb) bt
#0  0x0000000000486a6a in msg_search (pat=0x715f30, m=0x735ff0, e=0xde0610, msg=0x0) at pattern/exec.c:132
#1  0x00000000004881b9 in pattern_exec (pat=0x715f30, flags=1 '\001', m=0x735ff0, e=0xde0610, msg=0x0, cache=0x7fffffffa610) at pattern/exec.c:842
#2  0x0000000000488f27 in mutt_pattern_exec (pat=0x715f30, flags=1 '\001', m=0x735ff0, e=0xde0610, cache=0x7fffffffa610) at pattern/exec.c:1083
#3  0x0000000000467aa2 in mutt_set_header_color (m=0x735ff0, e=0xde0610) at index/index.c:4180
#4  0x000000000045d785 in index_color (menu=0xdf5960, line=0) at index/index.c:942
#5  0x0000000000436e2c in menu_redraw_index (menu=0xdf5960) at menu.c:394
#6  0x000000000045de6a in index_custom_redraw (menu=0xdf5960) at index/index.c:1100
#7  0x000000000045ec6c in mutt_index_menu (dlg=0xd44570, m_init=0x735ff0) at index/index.c:1363
#8  0x0000000000436402 in main (argc=1, argv=0x7fffffffd128, envp=0x7fffffffd138) at main.c:1255
(gdb) p msg
$1 = (struct Message *) 0x0
(gdb) 
```

## Steps to Reproduce

I don't know yet if there's anything specific on my configuration files that trigger the crash. I will try to narrow it down.

## How often does this happen?

- Always

## When did it start to happen?

Bisected to commit fe32ed106ab372abc456350295bec9b41ccbc780

## Extra Info

* Operating System and its version: Fedora 33
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? Using screen.
* Is your email local (maildir) or remote (IMAP)? I'm Using notmuch virtual folders.

**Comment by gahr** [comment]
Thanks, I’ll have a look asap

**Comment by flatcap** [comment]
@gahr see [devel/msg-search]
I'm just drafting a PR
