### ISSUE TITLE
neomutt dies with SIGFPE when trying to open mail

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#2928]
## Actual Behaviour

```
#0  0x000055d9bb027315 in mutt_color_quote (q=q@entry=0) at gui/color.c:1486
#1  0x000055d9bb006443 in classify_quote (quote_list=quote_list@entry=0x7ffd30798238, 
    qptr=0x55d9bd147610 "> On Thu, Mar 25, 2021 at 01:12:38AM +0300, Alexey Belovushchenko wrote:\n", length=1, 
    force_redraw=force_redraw@entry=0x7ffd30798228, q_level=q_level@entry=0x7ffd30798234) at pager/pager.c:655
#2  0x000055d9bb007b5b in resolve_types (
    buf=0x55d9bd147610 "> On Thu, Mar 25, 2021 at 01:12:38AM +0300, Alexey Belovushchenko wrote:\n", 
    raw=0x55d9bd15cd50 "> On Thu, Mar 25, 2021 at 01:12:38AM +0300, Alexey Belovushchenko wrote:\n", 
    line_info=0x55d9bd14bbd0, n=n@entry=15, last=16, quote_list=quote_list@entry=0x7ffd30798238, 
    q_level=0x7ffd30798234, force_redraw=0x7ffd30798228, q_classify=true) at pager/pager.c:1138
#3  0x000055d9bb00872d in display_line (fp=0x55d9bd122140, last_pos=last_pos@entry=0x7ffd30798240, 
    line_info=line_info@entry=0x7ffd307983a0, n=15, last=last@entry=0x7ffd3079821c, max=max@entry=0x7ffd30798218, 
    flags=66, quote_list=0x7ffd30798238, q_level=0x7ffd30798234, force_redraw=0x7ffd30798228, 
    search_re=0x7ffd30798258, win_pager=0x55d9bd146ee0) at pager/pager.c:1789
#4  0x000055d9bb009268 in pager_custom_redraw (pager_menu=0x55d9bd14c3c0) at pager/pager.c:2182
#5  0x000055d9bb00a3c2 in mutt_pager (pview=pview@entry=0x7ffd30798d10) at pager/pager.c:2570
#6  0x000055d9bafbf0b0 in mutt_display_message (win_index=0x55d9bd11a550, win_ibar=0x55d9bd11a5f0, 
    win_pager=0x55d9bd146ee0, win_pbar=0x55d9bd146fa0, m=0x55d9bd0d2180, e=0x55d9bd0fe0e0) at commands.c:392
#7  0x000055d9bb002524 in mutt_index_menu (dlg=0x55d9bd0e35f0, m_init=<optimized out>) at index/index.c:2681
#8  0x000055d9bafdf362 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1255
```

## How often does this happen?

- Always on particular private emails

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

git master; i auto-upgrade daily.

## NeoMutt Version

```
NeoMutt 20210205-296-2dc363
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.12.1 (x86_64)
ncurses: ncurses 6.2.20210123 (compiled with 6.2.20210123)
libidn: 1.36 (compiled with 1.36)
GPGME: 1.15.1
OpenSSL: OpenSSL 1.1.1k  25 Mar 2021
storage: bdb

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --with-sysroot=/ --libdir=/usr/lib64 CCACHE=none --disable-doc --enable-nls --disable-notmuch --disable-autocrypt --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls --disable-testing

Compilation CFLAGS: -O2 -pipe -march=native -ftree-vectorize -malign-data=cacheline -mtls-dialect=gnu2 -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I//usr/include -DNCURSES_WIDECHAR -I/include -I//usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex +sasl 
  -smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Gentoo Lignux
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
local

**Comment by flatcap** [comment]
> i auto-upgrade daily.

Thanks! ❤️ That's really appreciated.

Please can you give #2929 a try.  (Branch [[devel/colour]](https://github.com/neomutt/neomutt/tree/devel/colour))

**Comment by l29ah** [comment]
Seems worky now, thanks.
