### ISSUE TITLE
SIGBUS when exited from viewing a message

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#3062]
## Actual Behaviour

```
(gdb) bt
#0  0x00005602dbbc5ecc in find_subject (m=m@entry=0x5602dd782e00, cur=cur@entry=0x5602dd768660) at mutt_thread.c:593
#1  0x00005602dbbc60d9 in pseudo_threads (tctx=tctx@entry=0x5602dd7a7f50) at mutt_thread.c:662
#2  0x00005602dbbc733b in mutt_sort_threads (tctx=tctx@entry=0x5602dd7a7f50, init=<optimized out>, init@entry=false)
    at mutt_thread.c:1232
#3  0x00005602dbbd0aad in mutt_sort_headers (m=m@entry=0x5602dd782e00, threads=0x5602dd7a7f50, init=<optimized out>, 
    init@entry=false, vsize=vsize@entry=0x5602dd7af510) at sort.c:403
#4  0x00005602dbbd34c8 in update_index_threaded (ctx=ctx@entry=0x5602dd7af510, check=check@entry=MX_STATUS_NEW_MAIL, 
    oldcount=oldcount@entry=180) at index/dlg_index.c:391
#5  0x00005602dbbd3ec5 in update_index (menu=0x5602dd7d06a0, ctx=0x5602dd7af510, 
    check=check@entry=MX_STATUS_NEW_MAIL, oldcount=180, shared=shared@entry=0x5602dd7b5730) at index/dlg_index.c:502
#6  0x00005602dbbda5b1 in op_display_message (shared=0x5602dd7b5730, priv=0x5602dd816a90, op=0)
    at index/functions.c:342
#7  0x00005602dbbdb04d in index_function_dispatcher (win_index=<optimized out>, op=op@entry=70)
    at index/functions.c:3013
#8  0x00005602dbbd4b66 in mutt_index_menu (dlg=<optimized out>, m_init=<optimized out>) at index/dlg_index.c:1333
#9  0x00005602dbbbf7c1 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1368
```

If NeoMutt crashed, did your OS create a 'coredump' file?
yup
## Steps to Reproduce
idk

## How often does this happen?
Couldn't reproduce but had a few more crashes recently that i couldn't get a backtrace on.
## When did it start to happen?

- When I upgraded
  Which version did you use to use?

idk, i was always on master, like now.

## NeoMutt Version

```
NeoMutt 20210205-808-a1660b
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.14.3+ (x86_64)
ncurses: ncurses 6.2.20210619 (compiled with 6.2.20210619)
libidn: 1.38 (compiled with 1.38)
GPGME: 1.16.0
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
storage: bdb
compression: zlib

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --with-sysroot=/ --libdir=/usr/lib64 CCACHE=none CC_FOR_BUILD=x86_64-pc-linux-gnu-gcc --disable-doc --enable-nls --disable-notmuch --disable-autocrypt --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --disable-lz4 --enable-zlib --disable-zstd --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls --disable-testing

Compilation CFLAGS: -O2 -pipe -march=native -ftree-vectorize -malign-data=cacheline -mtls-dialect=gnu2 -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I//usr/include -DNCURSES_WIDECHAR -I/include -I//usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls -notmuch 
  +openssl +pgp +regex +sasl -smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Gentoo Lignux
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
maildir

**Comment by flatcap** [comment]
Have you tried deleting your header cache? (a bit of a long shot)

**Comment by l29ah** [comment]
No i have not.
