### ISSUE TITLE
more memory leaks found by ASAN, may be notmuch related

### ISSUE THREAD

**Issue by ebblake** [neomutt/neomutt#3066]
## Expected Behaviour
memory leaks should be avoided

## Actual Behaviour
running with ASAN, a couple lingering memory leaks were flagged even after #3055 and friends were fixed.
```

=================================================================
==257422==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 6865791 byte(s) in 305878 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x5a20ac in nm_mbox_check notmuch/notmuch.c:2170
    #7 0x4a7c4d in mx_mbox_check /home/eblake/neomutt/mx.c:1124
    #8 0x4ce472 in mutt_index_menu index/dlg_index.c:1131
    #9 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #10 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 2750965 byte(s) in 144423 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x5a20ac in nm_mbox_check notmuch/notmuch.c:2170
    #7 0x4a7c4d in mx_mbox_check /home/eblake/neomutt/mx.c:1124
    #8 0x4f071b in mutt_pager pager/dlg_pager.c:697
    #9 0x501711 in mutt_display_message pager/message.c:436
    #10 0x4d27cc in op_display_message index/functions.c:325
    #11 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #12 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #13 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #14 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 117242 byte(s) in 4203 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x59e325 in rename_filename notmuch/notmuch.c:1404
    #7 0x5a31e1 in nm_mbox_sync notmuch/notmuch.c:2305
    #8 0x4a29b1 in sync_mailbox /home/eblake/neomutt/mx.c:482
    #9 0x4a5746 in mx_mbox_close /home/eblake/neomutt/mx.c:851
    #10 0x4caa4e in change_folder_mailbox index/dlg_index.c:603
    #11 0x4e450d in op_sidebar_open index/functions.c:2911
    #12 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #13 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #14 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #15 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 2662 byte(s) in 27 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x7f669a99695f in __vasprintf_internal (/lib64/libc.so.6+0x7e95f)

Direct leak of 820 byte(s) in 43 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x59e325 in rename_filename notmuch/notmuch.c:1404
    #7 0x5a31e1 in nm_mbox_sync notmuch/notmuch.c:2305
    #8 0x4a29b1 in sync_mailbox /home/eblake/neomutt/mx.c:482
    #9 0x4a6a50 in mx_mbox_sync /home/eblake/neomutt/mx.c:999
    #10 0x4daf14 in op_main_sync_folder index/functions.c:1571
    #11 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #12 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #13 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #14 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 651 byte(s) in 24 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x59e325 in rename_filename notmuch/notmuch.c:1404
    #7 0x59fe06 in nm_update_filename notmuch/notmuch.c:1763
    #8 0x436eed in append_message /home/eblake/neomutt/copy.c:909
    #9 0x4370fd in mutt_append_message /home/eblake/neomutt/copy.c:937
    #10 0x4a3520 in trash_append /home/eblake/neomutt/mx.c:581
    #11 0x4a5472 in mx_mbox_close /home/eblake/neomutt/mx.c:817
    #12 0x4caa4e in change_folder_mailbox index/dlg_index.c:603
    #13 0x4e450d in op_sidebar_open index/functions.c:2911
    #14 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #15 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #16 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #17 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 586 byte(s) in 31 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x5a3b71 in nm_tags_commit notmuch/notmuch.c:2428
    #7 0x4a8c31 in mx_tags_commit /home/eblake/neomutt/mx.c:1296
    #8 0x4d852b in op_main_modify_tags index/functions.c:1106
    #9 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #10 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #11 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #12 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 315 byte(s) in 15 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x59e325 in rename_filename notmuch/notmuch.c:1404
    #7 0x5a31e1 in nm_mbox_sync notmuch/notmuch.c:2305
    #8 0x4a29b1 in sync_mailbox /home/eblake/neomutt/mx.c:482
    #9 0x4a5746 in mx_mbox_close /home/eblake/neomutt/mx.c:851
    #10 0x4caa4e in change_folder_mailbox index/dlg_index.c:603
    #11 0x4d62aa in op_main_change_folder index/functions.c:824
    #12 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #13 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #14 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #15 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Direct leak of 210 byte(s) in 2 object(s) allocated from:
    #0 0x7f669b35f93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
    #1 0x7f669a99699f in __vasprintf_internal (/lib64/libc.so.6+0x7e99f)

Direct leak of 85 byte(s) in 7 object(s) allocated from:
    #0 0x7f669b35fcb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x735df8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x7425ea in mutt_str_append_item mutt/string.c:474
    #3 0x7098c1 in driver_tags_getter email/tags.c:66
    #4 0x709e57 in driver_tags_get email/tags.c:147
    #5 0x599c23 in update_email_tags notmuch/notmuch.c:490
    #6 0x5a3b71 in nm_tags_commit notmuch/notmuch.c:2428
    #7 0x4a8c31 in mx_tags_commit /home/eblake/neomutt/mx.c:1296
    #8 0x4d829d in op_main_modify_tags index/functions.c:1085
    #9 0x4e4c88 in index_function_dispatcher index/functions.c:3016
    #10 0x4cfd0f in mutt_index_menu index/dlg_index.c:1340
    #11 0x482ab3 in main /home/eblake/neomutt/main.c:1368
    #12 0x7f669a93fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

SUMMARY: AddressSanitizer: 9739327 byte(s) leaked in 454653 allocation(s).

```

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

This was using my day-to-day mail habits (probably more than 24 hours of execution, swapping between lots of folders); unlike previous leak reports (where I just started then quit neomutt), this doesn't have easy reproductions, other than what you can spot in the backtraces.

## How often does this happen?
- Sometimes
I've confirmed that just starting and immediately exiting neomutt doesn't leak for my config file, so we've at least knocked out some of the easier leaks that I had been seeing for a long time.

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
Encountered while testing commit 339c0c06e

## NeoMutt Version

```
NeoMutt 20210205-852-339c0c
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.14.9-200.fc34.x86_64 (x86_64)
ncurses: ncurses 6.2.20200222 (compiled with 6.2.20200222)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.15.1
GnuTLS: 3.7.2
libnotmuch: 5.4.0
PCRE2: 10.36 2020-12-04
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --testing --sysconfdir=/etc --full-doc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --autocrypt --gnutls --gpgme --gss --disable-idn --idn2 --lmdb --lua --lz4 --notmuch --pcre2 --sasl --tokyocabinet --zlib --zstd {EXTRA_CFLAGS=-ggdb3 -Og} --asan

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pcre2 +pgp +sasl +smime +sqlite +sun_attachment 

Debug options:
  !asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Fedora 34
* Were you using multiple copies of NeoMutt at once?
* Were you using 'screen' or 'tmux'?
* Is your email local (maildir) or remote (IMAP)?
local mail accessed through notmuch and synchronized externally with mbsync

**Comment by flatcap** [comment]
Reading just the first block...

> Direct leak of 6865791 byte(s) in **305878 object(s)** allocated from:

Holy **\*\*\*\***!  That's a lot of leaks :-)
