### ISSUE TITLE
Memory leaks after sending a message

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3086]
I get the following output after sending a message and quitting:

```
=================================================================
==302808==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 272 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5580982d4d3b in mutt_mem_calloc mutt/memory.c:55
    #2 0x5580982772ed in mailbox_new core/mailbox.c:70
    #3 0x558098066a3c in mx_path_resolve /home/scott/IndependentInstalls/neomutt/mx.c:1680
    #4 0x558098251cb0 in mutt_write_fcc send/sendlib.c:1545
    #5 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #6 0x55809823ff1c in save_fcc send/send.c:1850
    #7 0x558098246363 in mutt_send_message send/send.c:2889
    #8 0x55809808fc12 in op_mail index/functions.c:702
    #9 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #10 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #11 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #12 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Direct leak of 192 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f8f235caad5  (<unknown module>)
    #2 0x7ffdc601c72f  ([stack]+0x1772f)

Indirect leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5580982d4d3b in mutt_mem_calloc mutt/memory.c:55
    #2 0x558098277389 in mailbox_new core/mailbox.c:76
    #3 0x558098066a3c in mx_path_resolve /home/scott/IndependentInstalls/neomutt/mx.c:1680
    #4 0x558098251cb0 in mutt_write_fcc send/sendlib.c:1545
    #5 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #6 0x55809823ff1c in save_fcc send/send.c:1850
    #7 0x558098246363 in mutt_send_message send/send.c:2889
    #8 0x55809808fc12 in op_mail index/functions.c:702
    #9 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #10 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #11 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #12 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59ff8 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0x5580982d4fc8 in mutt_mem_realloc mutt/memory.c:131
    #2 0x5580982b6611 in mutt_buffer_alloc mutt/buffer.c:282
    #3 0x5580982b58c6 in mutt_buffer_addstr_n mutt/buffer.c:105
    #4 0x5580982b62b2 in mutt_buffer_addstr mutt/buffer.c:229
    #5 0x5580982b6788 in mutt_buffer_strcpy mutt/buffer.c:315
    #6 0x558098066a98 in mx_path_resolve /home/scott/IndependentInstalls/neomutt/mx.c:1682
    #7 0x558098251cb0 in mutt_write_fcc send/sendlib.c:1545
    #8 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #9 0x55809823ff1c in save_fcc send/send.c:1850
    #10 0x558098246363 in mutt_send_message send/send.c:2889
    #11 0x55809808fc12 in op_mail index/functions.c:702
    #12 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #13 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #14 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #15 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 100 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5580982d4d3b in mutt_mem_calloc mutt/memory.c:55
    #2 0x5580982773ff in mailbox_new core/mailbox.c:77
    #3 0x558098066a3c in mx_path_resolve /home/scott/IndependentInstalls/neomutt/mx.c:1680
    #4 0x558098251cb0 in mutt_write_fcc send/sendlib.c:1545
    #5 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #6 0x55809823ff1c in save_fcc send/send.c:1850
    #7 0x558098246363 in mutt_send_message send/send.c:2889
    #8 0x55809808fc12 in op_mail index/functions.c:702
    #9 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #10 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #11 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #12 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5580982d4d3b in mutt_mem_calloc mutt/memory.c:55
    #2 0x55809828b437 in cs_subset_new config/subset.c:147
    #3 0x558098278a47 in mailbox_set_subset core/mailbox.c:252
    #4 0x558098276535 in account_mailbox_add core/account.c:78
    #5 0x558098066e8e in mx_ac_add /home/scott/IndependentInstalls/neomutt/mx.c:1764
    #6 0x55809805ca3d in mx_mbox_ac_link /home/scott/IndependentInstalls/neomutt/mx.c:282
    #7 0x55809805ccc7 in mx_mbox_open /home/scott/IndependentInstalls/neomutt/mx.c:318
    #8 0x558098251d39 in mutt_write_fcc send/sendlib.c:1547
    #9 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #10 0x55809823ff1c in save_fcc send/send.c:1850
    #11 0x558098246363 in mutt_send_message send/send.c:2889
    #12 0x55809808fc12 in op_mail index/functions.c:702
    #13 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #14 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #15 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #16 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5580982d4d3b in mutt_mem_calloc mutt/memory.c:55
    #2 0x5580982d50cf in notify_new mutt/notify.c:62
    #3 0x55809828b618 in cs_subset_new config/subset.c:167
    #4 0x558098278a47 in mailbox_set_subset core/mailbox.c:252
    #5 0x558098276535 in account_mailbox_add core/account.c:78
    #6 0x558098066e8e in mx_ac_add /home/scott/IndependentInstalls/neomutt/mx.c:1764
    #7 0x55809805ca3d in mx_mbox_ac_link /home/scott/IndependentInstalls/neomutt/mx.c:282
    #8 0x55809805ccc7 in mx_mbox_open /home/scott/IndependentInstalls/neomutt/mx.c:318
    #9 0x558098251d39 in mutt_write_fcc send/sendlib.c:1547
    #10 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #11 0x55809823ff1c in save_fcc send/send.c:1850
    #12 0x558098246363 in mutt_send_message send/send.c:2889
    #13 0x55809808fc12 in op_mail index/functions.c:702
    #14 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #15 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #16 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #17 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a59e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x5580982d4d3b in mutt_mem_calloc mutt/memory.c:55
    #2 0x5580982d50cf in notify_new mutt/notify.c:62
    #3 0x558098277302 in mailbox_new core/mailbox.c:73
    #4 0x558098066a3c in mx_path_resolve /home/scott/IndependentInstalls/neomutt/mx.c:1680
    #5 0x558098251cb0 in mutt_write_fcc send/sendlib.c:1545
    #6 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #7 0x55809823ff1c in save_fcc send/send.c:1850
    #8 0x558098246363 in mutt_send_message send/send.c:2889
    #9 0x55809808fc12 in op_mail index/functions.c:702
    #10 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #11 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #12 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #13 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 20 byte(s) in 2 object(s) allocated from:
    #0 0x7f8f27a59c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f8f235cb168  (<unknown module>)

Indirect leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x7f8f27a009f7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x5580982e250e in mutt_str_dup mutt/string.c:375
    #2 0x5580982e299d in mutt_str_replace mutt/string.c:451
    #3 0x558098065994 in mx_path_canon2 /home/scott/IndependentInstalls/neomutt/mx.c:1485
    #4 0x558098066b0e in mx_path_resolve /home/scott/IndependentInstalls/neomutt/mx.c:1684
    #5 0x558098251cb0 in mutt_write_fcc send/sendlib.c:1545
    #6 0x55809825175b in mutt_write_multiple_fcc send/sendlib.c:1494
    #7 0x55809823ff1c in save_fcc send/send.c:1850
    #8 0x558098246363 in mutt_send_message send/send.c:2889
    #9 0x55809808fc12 in op_mail index/functions.c:702
    #10 0x55809809fbdd in index_function_dispatcher index/functions.c:3017
    #11 0x55809808a221 in mutt_index_menu index/dlg_index.c:1343
    #12 0x55809803cb39 in main /home/scott/IndependentInstalls/neomutt/main.c:1378
    #13 0x7f8f27249564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: 1017 byte(s) leaked in 11 allocation(s).
```

NeoMutt version info:
```
$ neomutt -v
NeoMutt 20211022
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.0-38-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1j  16 Feb 2021
libnotmuch: 5.3.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --asan --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

Debug options:
  !asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by 0-wiz-0** [comment]
Fixing the leak caused a segfault, see #3129. So this is not a good fix.
