### ISSUE TITLE
asan reports heap-buffer-overflow

### ISSUE THREAD

**Issue by ebblake** [neomutt/neomutt#3105]
## Expected Behaviour
no bad memory usage - asan builds should never crash ;)

## Actual Behaviour
asan reported:
```
=================================================================
==3702==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61e0009c2360 at pc 0x0000004fefac bp 0x7ffe340c52b0 sp 0x7ffe340c52a8
WRITE of size 8 at 0x61e0009c2360 thread T0
    #0 0x4fefab in display_line pager/display.c:1626
    #1 0x4ee6c6 in pager_custom_redraw pager/dlg_pager.c:331
    #2 0x4f1245 in mutt_pager pager/dlg_pager.c:671
    #3 0x5025d8 in mutt_display_message pager/message.c:436
    #4 0x4d3400 in op_display_message index/functions.c:325
    #5 0x4e58c1 in index_function_dispatcher index/functions.c:3017
    #6 0x4d093e in mutt_index_menu index/dlg_index.c:1341
    #7 0x482eb7 in main /home/eblake/neomutt/main.c:1377
    #8 0x7f09f6a7fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
    #9 0x40c23d in _start (/home/eblake/neomutt/neomutt+0x40c23d)

0x61e0009c2360 is located 0 bytes to the right of 2784-byte region [0x61e0009c1880,0x61e0009c2360)
allocated by thread T0 here:
    #0 0x7f09f749faf7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738acd in mutt_mem_calloc mutt/memory.c:55
    #2 0x4f0672 in mutt_pager pager/dlg_pager.c:600
    #3 0x5025d8 in mutt_display_message pager/message.c:436
    #4 0x4d3400 in op_display_message index/functions.c:325
    #5 0x4e58c1 in index_function_dispatcher index/functions.c:3017
    #6 0x4d093e in mutt_index_menu index/dlg_index.c:1341
    #7 0x482eb7 in main /home/eblake/neomutt/main.c:1377
    #8 0x7f09f6a7fb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

SUMMARY: AddressSanitizer: heap-buffer-overflow pager/display.c:1626 in display_line
Shadow bytes around the buggy address:
  0x0c3c80130410: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c80130420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c80130430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c80130440: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c80130450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3c80130460: 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa
  0x0c3c80130470: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c80130480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c80130490: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c801304a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c801304b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
==3702==ABORTING
```

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce
Sadly, I'm not sure what I did to trigger this one, other than using neomutt for normal usage. I'm using notmuch, and do recall replying to a thread, so there may have been an <entire-thread> action to expand a thread to pick up my reply in the thread view prior to the point of the crash.

## How often does this happen?
I'm not yet sure how to reproduce it, to know if it is one that users will hit regularly.

## When did it start to happen?

- When I upgraded to git build beyond the 20211022 release

## NeoMutt Version

```
NeoMutt 20211022-17-2c6998
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.14.13-200.fc34.x86_64 (x86_64)
ncurses: ncurses 6.2.20200222 (compiled with 6.2.20200222)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.15.1
GnuTLS: 3.7.2
libnotmuch: 5.4.0
PCRE2: 10.36 2020-12-04
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --sysconfdir=/etc --full-doc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --autocrypt --gnutls --gpgme --gss --disable-idn --idn2 --lmdb --lua --lz4 --notmuch --pcre2 --sasl --tokyocabinet --zlib --zstd --enable-asan

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pcre2 +pgp +sasl +smime +sqlite +sun_attachment 

Debug options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Fedora 34
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
local via notmuch

**Comment by roccoblues** [comment]
Hi @ebblake, can you still reproduce this with the latest version?
