### ISSUE TITLE
memory leaks detected by asan

### ISSUE THREAD

**Issue by ebblake** [neomutt/neomutt#3107]
## Expected Behaviour
proper memory tracking

## Actual Behaviour
asan caught the following:
```
=================================================================
==99570==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1391 byte(s) in 14 object(s) allocated from:
    #0 0x7fb53d2b7cb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x7fb53c8ee95f in __vasprintf_internal (/lib64/libc.so.6+0x7e95f)

Direct leak of 306 byte(s) in 3 object(s) allocated from:
    #0 0x7fb53d2b793f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
    #1 0x7fb53c8ee99f in __vasprintf_internal (/lib64/libc.so.6+0x7e99f)

Direct leak of 272 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x6df01d in mailbox_new core/mailbox.c:70
    #3 0x4aba7f in mx_path_resolve /home/eblake/neomutt/mx.c:1682
    #4 0x6d19be in op_compose_attach_message compose/functions.c:558
    #5 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #6 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #7 0x6adadc in mutt_send_message send/send.c:2711
    #8 0x4de3c0 in op_reply index/functions.c:1941
    #9 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #10 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #11 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #12 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 400 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7cb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x738f6d in mutt_mem_realloc mutt/memory.c:131
    #2 0x4a8fc6 in mx_alloc_memory /home/eblake/neomutt/mx.c:1230
    #3 0x59cae9 in append_message notmuch/notmuch.c:772
    #4 0x59d367 in append_replies notmuch/notmuch.c:864
    #5 0x59d386 in append_replies notmuch/notmuch.c:866
    #6 0x59d386 in append_replies notmuch/notmuch.c:866
    #7 0x59d386 in append_replies notmuch/notmuch.c:866
    #8 0x59d386 in append_replies notmuch/notmuch.c:866
    #9 0x59d386 in append_replies notmuch/notmuch.c:866
    #10 0x59d386 in append_replies notmuch/notmuch.c:866
    #11 0x59d431 in append_thread notmuch/notmuch.c:892
    #12 0x59d9c6 in read_threads_query notmuch/notmuch.c:1026
    #13 0x5a2de2 in nm_mbox_open notmuch/notmuch.c:2060
    #14 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #15 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #16 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #17 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #18 0x6adadc in mutt_send_message send/send.c:2711
    #19 0x4de3c0 in op_reply index/functions.c:1941
    #20 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #21 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #22 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #23 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7cb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x738f6d in mutt_mem_realloc mutt/memory.c:131
    #2 0x4a901d in mx_alloc_memory /home/eblake/neomutt/mx.c:1231
    #3 0x59cae9 in append_message notmuch/notmuch.c:772
    #4 0x59d367 in append_replies notmuch/notmuch.c:864
    #5 0x59d386 in append_replies notmuch/notmuch.c:866
    #6 0x59d386 in append_replies notmuch/notmuch.c:866
    #7 0x59d386 in append_replies notmuch/notmuch.c:866
    #8 0x59d386 in append_replies notmuch/notmuch.c:866
    #9 0x59d386 in append_replies notmuch/notmuch.c:866
    #10 0x59d386 in append_replies notmuch/notmuch.c:866
    #11 0x59d431 in append_thread notmuch/notmuch.c:892
    #12 0x59d9c6 in read_threads_query notmuch/notmuch.c:1026
    #13 0x5a2de2 in nm_mbox_open notmuch/notmuch.c:2060
    #14 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #15 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #16 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #17 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #18 0x6adadc in mutt_send_message send/send.c:2711
    #19 0x4de3c0 in op_reply index/functions.c:1941
    #20 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #21 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #22 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #23 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7cb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
    #1 0x738f6d in mutt_mem_realloc mutt/memory.c:131
    #2 0x71bebb in mutt_buffer_alloc mutt/buffer.c:282
    #3 0x71b25b in mutt_buffer_addstr_n mutt/buffer.c:105
    #4 0x71bba0 in mutt_buffer_addstr mutt/buffer.c:229
    #5 0x71c02a in mutt_buffer_strcpy mutt/buffer.c:315
    #6 0x4abadb in mx_path_resolve /home/eblake/neomutt/mx.c:1684
    #7 0x6d19be in op_compose_attach_message compose/functions.c:558
    #8 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #9 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #10 0x6adadc in mutt_send_message send/send.c:2711
    #11 0x4de3c0 in op_reply index/functions.c:1941
    #12 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #13 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #14 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #15 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x70e054 in url_new email/url.c:114
    #3 0x70eeab in url_parse email/url.c:254
    #4 0x5a5c40 in nm_mdata_new notmuch/mdata.c:82
    #5 0x599cc7 in init_mailbox notmuch/notmuch.c:196
    #6 0x5a2c38 in nm_mbox_open notmuch/notmuch.c:2036
    #7 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #8 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #9 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #10 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #11 0x6adadc in mutt_send_message send/send.c:2711
    #12 0x4de3c0 in op_reply index/functions.c:1941
    #13 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #14 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #15 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #16 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d262967 in strdup (/lib64/libasan.so.6+0x59967)
    #1 0x7451b5 in mutt_str_dup mutt/string.c:375
    #2 0x745611 in mutt_str_replace mutt/string.c:451
    #3 0x4aaa79 in mx_path_canon2 /home/eblake/neomutt/mx.c:1487
    #4 0x4abb4d in mx_path_resolve /home/eblake/neomutt/mx.c:1686
    #5 0x6d19be in op_compose_attach_message compose/functions.c:558
    #6 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #7 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #8 0x6adadc in mutt_send_message send/send.c:2711
    #9 0x4de3c0 in op_reply index/functions.c:1941
    #10 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #11 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #12 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #13 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d262967 in strdup (/lib64/libasan.so.6+0x59967)
    #1 0x7451b5 in mutt_str_dup mutt/string.c:375
    #2 0x70ef20 in url_parse email/url.c:256
    #3 0x5a5c40 in nm_mdata_new notmuch/mdata.c:82
    #4 0x599cc7 in init_mailbox notmuch/notmuch.c:196
    #5 0x5a2c38 in nm_mbox_open notmuch/notmuch.c:2036
    #6 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #7 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #8 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #9 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #10 0x6adadc in mutt_send_message send/send.c:2711
    #11 0x4de3c0 in op_reply index/functions.c:1941
    #12 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #13 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #14 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #15 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x6f1f0e in cs_subset_new config/subset.c:147
    #3 0x6e0620 in mailbox_set_subset core/mailbox.c:252
    #4 0x6de33f in account_mailbox_add core/account.c:78
    #5 0x4abebb in mx_ac_add /home/eblake/neomutt/mx.c:1766
    #6 0x4a1e7f in mx_mbox_ac_link /home/eblake/neomutt/mx.c:282
    #7 0x4a20e5 in mx_mbox_open /home/eblake/neomutt/mx.c:318
    #8 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #9 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #10 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #11 0x6adadc in mutt_send_message send/send.c:2711
    #12 0x4de3c0 in op_reply index/functions.c:1941
    #13 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #14 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #15 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #16 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x5a5a1f in nm_mdata_new notmuch/mdata.c:74
    #3 0x599cc7 in init_mailbox notmuch/notmuch.c:196
    #4 0x5a2c38 in nm_mbox_open notmuch/notmuch.c:2036
    #5 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #6 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #7 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #8 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #9 0x6adadc in mutt_send_message send/send.c:2711
    #10 0x4de3c0 in op_reply index/functions.c:1941
    #11 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #12 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #13 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #14 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 25 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d262967 in strdup (/lib64/libasan.so.6+0x59967)
    #1 0x7451b5 in mutt_str_dup mutt/string.c:375
    #2 0x745611 in mutt_str_replace mutt/string.c:451
    #3 0x59a8d6 in get_query_string notmuch/notmuch.c:370
    #4 0x59b07f in get_query notmuch/notmuch.c:447
    #5 0x5a2d27 in nm_mbox_open notmuch/notmuch.c:2048
    #6 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #7 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #8 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #9 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #10 0x6adadc in mutt_send_message send/send.c:2711
    #11 0x4de3c0 in op_reply index/functions.c:1941
    #12 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #13 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #14 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #15 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x73905c in notify_new mutt/notify.c:62
    #3 0x6df032 in mailbox_new core/mailbox.c:73
    #4 0x4aba7f in mx_path_resolve /home/eblake/neomutt/mx.c:1682
    #5 0x6d19be in op_compose_attach_message compose/functions.c:558
    #6 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #7 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #8 0x6adadc in mutt_send_message send/send.c:2711
    #9 0x4de3c0 in op_reply index/functions.c:1941
    #10 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #11 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #12 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #13 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x70debd in parse_query_string email/url.c:79
    #3 0x70fbb7 in url_parse email/url.c:334
    #4 0x5a5c40 in nm_mdata_new notmuch/mdata.c:82
    #5 0x599cc7 in init_mailbox notmuch/notmuch.c:196
    #6 0x5a2c38 in nm_mbox_open notmuch/notmuch.c:2036
    #7 0x4a29df in mx_mbox_open /home/eblake/neomutt/mx.c:388
    #8 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #9 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #10 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #11 0x6adadc in mutt_send_message send/send.c:2711
    #12 0x4de3c0 in op_reply index/functions.c:1941
    #13 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #14 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #15 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #16 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x73905c in notify_new mutt/notify.c:62
    #3 0x6f20ed in cs_subset_new config/subset.c:167
    #4 0x6e0620 in mailbox_set_subset core/mailbox.c:252
    #5 0x6de33f in account_mailbox_add core/account.c:78
    #6 0x4abebb in mx_ac_add /home/eblake/neomutt/mx.c:1766
    #7 0x4a1e7f in mx_mbox_ac_link /home/eblake/neomutt/mx.c:282
    #8 0x4a20e5 in mx_mbox_open /home/eblake/neomutt/mx.c:318
    #9 0x6d1a2b in op_compose_attach_message compose/functions.c:560
    #10 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #11 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #12 0x6adadc in mutt_send_message send/send.c:2711
    #13 0x4de3c0 in op_reply index/functions.c:1941
    #14 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #15 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #16 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #17 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x739e2d in notify_observer_add mutt/notify.c:210
    #3 0x4e8e43 in index_shared_data_set_context index/shared_data.c:187
    #4 0x4ce522 in mutt_index_menu index/dlg_index.c:1048
    #5 0x6d1d86 in op_compose_attach_message compose/functions.c:587
    #6 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #7 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #8 0x6adadc in mutt_send_message send/send.c:2711
    #9 0x4de3c0 in op_reply index/functions.c:1941
    #10 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #11 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #12 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #13 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fb53d2b7af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x738cff in mutt_mem_calloc mutt/memory.c:55
    #2 0x739e2d in notify_observer_add mutt/notify.c:210
    #3 0x42ef33 in ctx_new /home/eblake/neomutt/context.c:90
    #4 0x4ce50d in mutt_index_menu index/dlg_index.c:1048
    #5 0x6d1d86 in op_compose_attach_message compose/functions.c:587
    #6 0x6ddc2d in compose_function_dispatcher compose/functions.c:1993
    #7 0x6c6b0c in mutt_compose_menu compose/compose.c:448
    #8 0x6adadc in mutt_send_message send/send.c:2711
    #9 0x4de3c0 in op_reply index/functions.c:1941
    #10 0x4e5af3 in index_function_dispatcher index/functions.c:3017
    #11 0x4d0b70 in mutt_index_menu index/dlg_index.c:1341
    #12 0x482f34 in main /home/eblake/neomutt/main.c:1377
    #13 0x7fb53c897b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

SUMMARY: AddressSanitizer: 3070 byte(s) leaked in 32 allocation(s).
```

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce
Not sure what particular steps matter, but looking at the traces, at least one obvious candidate was me composing a message where I used `A` to attach another message before sending.

## How often does this happen?
- Sometimes

## When did it start to happen?

- When I upgraded
Currently running from git.

## NeoMutt Version

```
NeoMutt 20211022-17-2c6998
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.14.13-200.fc34.x86_64 (x86_64)
ncurses: ncurses 6.2.20200222 (compiled with 6.2.20200222)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.15.1
GnuTLS: 3.7.2
libnotmuch: 5.4.0
PCRE2: 10.36 2020-12-04
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --sysconfdir=/etc --full-doc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --autocrypt --gnutls --gpgme --gss --disable-idn --idn2 --lmdb --lua --lz4 --notmuch --pcre2 --sasl --tokyocabinet --zlib --zstd --enable-asan

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pcre2 +pgp +sasl +smime +sqlite +sun_attachment 

Debug options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
* Were you using multiple copies of NeoMutt at once?
* Were you using 'screen' or 'tmux'?
* Is your email local (maildir) or remote (IMAP)?

**Comment by roccoblues** [comment]
Hi @ebblake, can you still reproduce this with the latest version?
