### ISSUE TITLE
asan leak with 'neomutt -version' (but not 'neomutt -v')

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3149]
I get a detected leak when running `neomutt -version` but interestingly no leak with `neomutt -v`. See the leak at the bottom of the following output:

```
$ neomutt -version
NeoMutt 20211029-48-5f3961
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.13.0-22-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.4.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --asan --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

Debug options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

=================================================================
==29801==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fbc5424ca37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55a23795445c in mutt_mem_calloc mutt/memory.c:55
    #2 0x55a23794bcc0 in mutt_list_insert_tail mutt/list.c:69
    #3 0x55a2376af537 in main /home/vbox/IndependentInstalls/neomutt/main.c:585
    #4 0x7fbc53a0cfcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7fbc541f39a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55a237960c51 in mutt_str_dup mutt/string.c:186
    #2 0x55a2376af522 in main /home/vbox/IndependentInstalls/neomutt/main.c:585
    #3 0x7fbc53a0cfcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 22 byte(s) leaked in 2 allocation(s).
$ 
```

**Comment by flatcap** [comment]
That was a weird one!
Thanks
