### ISSUE TITLE
Leak detected by ASAN when changing to a folder

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3180]
From current master, I get the following leak when I open mutt and `c<TAB>` and choose a folder:

```
=================================================================
==2117269==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1088 byte(s) in 17 object(s) allocated from:
    #0 0x7fde1bbfba37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x556df4b818a6 in mutt_mem_calloc mutt/memory.c:55
    #2 0x556df48e6252 in mutt_sort_threads /home/scott/IndependentInstalls/neomutt/mutt_thread.c:1102
    #3 0x556df490a823 in mutt_sort_headers /home/scott/IndependentInstalls/neomutt/sort.c:403
    #4 0x556df487a2e5 in ctx_update /home/scott/IndependentInstalls/neomutt/context.c:214
    #5 0x556df4879318 in ctx_new /home/scott/IndependentInstalls/neomutt/context.c:96
    #6 0x556df49146b5 in change_folder_mailbox index/dlg_index.c:657
    #7 0x556df4914e9f in change_folder_string index/dlg_index.c:758
    #8 0x556df491fee7 in op_main_change_folder index/functions.c:867
    #9 0x556df492f5a6 in index_function_dispatcher index/functions.c:3207
    #10 0x556df4919700 in mutt_index_menu index/dlg_index.c:1341
    #11 0x556df48cb094 in main /home/scott/IndependentInstalls/neomutt/main.c:1379
    #12 0x7fde1b3bbfcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 1088 byte(s) leaked in 17 allocation(s).
```

## NeoMutt Version

```
NeoMutt 20211029-155-ec2bfc
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.5-051505-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.4.0
storage: tokyocabinet

Configure options: --asan --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

Devel options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

maildir

**Comment by flatcap** [comment]
Please can you give branch [[devel/threads]](https://github.com/neomutt/neomutt/tree/devel/threads) a try.

Thanks

**Comment by scottkosty** [comment]
> Please can you give branch [[devel/threads]](https://github.com/neomutt/neomutt/tree/devel/threads) a try.

I just tried it and can no longer reproduce the leak. Thanks!
