### ISSUE TITLE
Leak detected by ASAN with when colouring messages in a collapsed thread

### ISSUE THREAD

**Issue by dcpurton** [neomutt/neomutt#3184]
With this config file (`leak.rc`):

```
color index red default "~v~(~N)~(~F)"
```

Running `./neomutt -n -F leak.rc`  gives:

```
=================================================================
==100865==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x4a4312 in __interceptor_calloc (/home/dcpurton/development/neomutt/neomutt+0x4a4312)
    #1 0x9238bf in mutt_mem_calloc /home/dcpurton/development/neomutt/mutt/memory.c:55:13
    #2 0x6c1f26 in mutt_pattern_node_new /home/dcpurton/development/neomutt/pattern/compile.c:1076:27
    #3 0x6bf5e1 in mutt_pattern_comp /home/dcpurton/development/neomutt/pattern/compile.c:1197:17
    #4 0x69eac1 in add_pattern /home/dcpurton/development/neomutt/color/regex.c:228:11
    #5 0x69f4f2 in regex_colors_parse_color_list /home/dcpurton/development/neomutt/color/regex.c:304:13
    #6 0x69617c in parse_color /home/dcpurton/development/neomutt/color/command.c:643:7
    #7 0x694d8b in mutt_parse_color /home/dcpurton/development/neomutt/color/command.c:737:10
    #8 0x539771 in mutt_parse_rc_buffer /home/dcpurton/development/neomutt/init.c:1018:14
    #9 0x4e2309 in source_rc /home/dcpurton/development/neomutt/command_parse.c:217:15
    #10 0x5370e6 in mutt_init /home/dcpurton/development/neomutt/init.c:912:11
    #11 0x551b75 in main /home/dcpurton/development/neomutt/main.c:792:13
    #12 0x7f6fe1c227ec in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x277ec)

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```

## NeoMutt Version

```
NeoMutt 20211029-168-3bd10b
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.0-2-amd64 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn: 1.38 (compiled with 1.38)
GPGME: 1.16.0-unknown
GnuTLS: 3.7.2
libnotmuch: 5.5.0
storage: tokyocabinet

Configure options: --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt --debug-graphviz --asan

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5 -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

Devel options:
  asan graphviz 

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by flatcap** [comment]
Please can you give branch [[devel/pattern]](https://github.com/neomutt/neomutt/tree/devel/pattern) a try.

Thanks

**Comment by dcpurton** [comment]
This fixes the leak. Thanks.
