### ISSUE TITLE
Various <query> and <complete-query> issues

### ISSUE THREAD

**Issue by dcpurton** [neomutt/neomutt#3300]
Here's a test `rc` file exhibiting a couple of issues with `<query>` and `<complete-query>`.

These are all regressions with your recent refactoring changes.

```
# vim: syn=neomuttrc

# filename: query-test.rc

# run from build directory:
#   ./neomutt -n -F query-test.rc

set folder = "./"

set query_command = "echo '%s: 3 matches\na@example.com\tA\texample.com\nb@example.com\tB\texample.com\nc@example.com\tC\texample.com\n'"

# success
macro index <F1> "<query>example<enter><tag-entry><tag-entry><tag-entry><tag-prefix><enter>"

# success
macro index <F2> "<query>example<enter><tag-entry><tag-prefix><enter>"

# success
macro index <F3> "<query>example<enter><enter>"

# failure
# produces    To: example, , C <c@exmaple.com>
# expected    To: A <a@example.com>, B <b@example.com>, C <c@example.com>
macro index <F4> "<mail>example<complete-query><tag-entry><tag-entry><tag-entry><tag-prefix><enter>"

# success
macro index <F5> "<mail>example<complete-query><enter>"

# failure
# produces    To: example, A <a@example.com>
# expected    To: A <a@example.com>
macro index <F6> "<mail>example<complete-query><tag-entry><tag-prefix><enter>"

# segfault
macro index <F7> "<query>example<enter><enter>\cu<enter><query>"

# unrelated failures
# indicator line disappears
macro index <F8> "<query>example<enter><tag-entry><tag-entry><tag-entry>"
macro index <F9> "<mail>example<complete-query><tag-entry><tag-entry><tag-entry>"
```

**Comment by dcpurton** [comment]
GDB backtrace for segfault:

```c
Program received signal SIGSEGV, Segmentation fault.
0x0000000000707ebc in mutt_buffer_get_field (field=0xa10020 <str> "Query: ", buf=0x0, complete=0, 
    multiple=false, m=0x0, files=0x0, numfiles=0x0) at gui/curs_lib.c:310
310	   ret = mutt_enter_string_full(buf->data, buf->dsize, col, complete, multiple,
(gdb) bt
#0  0x0000000000707ebc in mutt_buffer_get_field (field=0xa10020 <str> "Query: ", buf=0x0, complete=0, multiple=false, m=0x0, files=0x0, numfiles=0x0) at gui/curs_lib.c:310
#1  0x00000000008a706c in op_query (mdata=0x7ffdef452c60, op=192) at alias/functions.c:196
#2  0x00000000008a7ece in alias_function_dispatcher (win=0x60e0000263e0, op=192) at alias/functions.c:342
#3  0x00000000008a375c in dlg_select_query (buf=0x60300000a3f0, all=0x7ffdef453020, retbuf=false, sub=0x6040000009d0) at alias/dlg_query.c:414
#4  0x00000000008a443b in query_index (sub=0x6040000009d0) at alias/dlg_query.c:549
#5  0x00000000005d7f31 in op_query (shared=0x606000004640, priv=0x607000001b40, op=192) at index/functions.c:1991
#6  0x00000000005c816d in index_function_dispatcher (win_index=0x60e000025b20, op=192) at index/functions.c:3181
#7  0x00000000005c6d5c in mutt_index_menu (dlg=0x60e000025960, m_init=0x0) at index/dlg_index.c:1341
#8  0x0000000000556d21 in main (argc=1, argv=0x7ffdef455b18, envp=0x7ffdef455b40) at main.c:1381
```
