### ISSUE TITLE
SIGSEGV when setting color in hook with variable

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3364]
## Expected Behaviour

I can set a color in a hook with a variable.

## Actual Behaviour

Segfault.

## Steps to Reproduce

With the below RC file I just start mutt and open a message and get a segfault:

```
set realname = 'Scott Kostyshak'
set imap_user = 'scott.kostyshak@gmail.com'
set imap_pass = `gpg --use-agent --quiet --batch -d ~/.skp/gmail.gpg`

set folder = "~/.mail"

set smtp_url = "smtp://scott.kostyshak@smtp.gmail.com:587/"
set smtp_pass = $imap_pass

set spoolfile = +INBOX

message-hook . 'set my_hdr_colour=default'
message-hook . 'color header $my_hdr_colour default (Date|From|To)'
```

Here is the backtrace:

```
(gdb) bt
#0  resolve_color (win=0x5555557f70e0, lines=0x5555557faf50, line_num=0, cnt=0, flags=66, special=0, ansi=0x7fffffffc4f0)
    at pager/display.c:153
#1  0x00005555555cf66e in format_line
    (win=0x5555557f70e0, lines=0x5555557f6ef8, line_num=0, buf=0x5555557fb8a0 "Date: Thu, 14 Apr 2022 14:46:32 -0400\n", flags=66, ansi=0x7fffffffc4f0, cnt=37, pspace=0x7fffffffc474, pvch=0x7fffffffc478, pcol=0x7fffffffc47c, pspecial=0x7fffffffc484, width=127, ansi_list=0x5555557f7080) at pager/display.c:885
#2  0x00005555555d074b in display_line
    (fp=0x5555557e8ef0, bytes_read=0x5555557f6ef0, lines=0x5555557f6ef8, line_num=0, lines_used=0x5555557f6f00, lines_max=0x5555557f6f04, flags=66, quote_list=0x5555557f6f20, q_level=0x5555557f6f28, force_redraw=0x5555557f7079, search_re=0x5555557f7038, win_pager=0x5555557f70e0, ansi_list=0x5555557f7080) at pager/display.c:1208
#3  0x00005555555d6b61 in pager_repaint (win=0x5555557f70e0) at pager/pager.c:209
#4  0x0000555555629ace in window_repaint (win=0x5555557f70e0) at gui/mutt_window.c:588
#5  0x0000555555629b04 in window_repaint (win=0x5555557f6d90) at gui/mutt_window.c:594
#6  0x0000555555629b04 in window_repaint (win=0x5555557f75c0) at gui/mutt_window.c:594
#7  0x0000555555629b04 in window_repaint (win=0x5555557e1800) at gui/mutt_window.c:594
#8  0x0000555555629b04 in window_repaint (win=0x5555557714e0) at gui/mutt_window.c:594
#9  0x0000555555629b04 in window_repaint (win=0x555555771240) at gui/mutt_window.c:594
#10 0x0000555555629b8c in window_redraw (win=0x555555771240) at gui/mutt_window.c:620
#11 0x00005555555d1572 in mutt_pager (pview=0x7fffffffcc50) at pager/dlg_pager.c:384
#12 0x00005555555d5edc in mutt_display_message (win_index=0x5555557e1a10, shared=0x5555557e18c0) at pager/message.c:499
#13 0x00005555555c319b in op_display_message (shared=0x5555557e18c0, priv=0x5555557e19e0, op=72) at index/functions.c:414
#14 0x00005555555c9b0d in index_function_dispatcher (win=0x5555557e1a10, op=72) at index/functions.c:2863
#15 0x00005555555c2154 in mutt_index_menu (dlg=0x5555557e1800, m_init=0x5555557f4ff0) at index/dlg_index.c:1345
#16 0x00005555555a3292 in main (argc=1, argv=0x7fffffffda18, envp=0x7fffffffda38) at main.c:1380
```

## How often does this happen?

- Always

## When did it start to happen?

Bisect leads to 4f1c0185d665ebd5bbe8c2fa3b7bbf32df6cd731.

## NeoMutt Version

```
NeoMutt 20220408-35-db88c3
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.5-051505-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.4.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

Maildir.

**Comment by flatcap** [comment]
Please can you give branch [[devel/default]](https://github.com/neomutt/neomutt/tree/devel/default) a try.

Thanks

**Comment by scottkosty** [comment]
Works well. Thanks for the quick fix!
