### ISSUE TITLE
neomutt hangs when closing with broken IMAP connection

### ISSUE THREAD

**Issue by matthewhughes934** [neomutt/neomutt#3428]
## Expected Behaviour

Closing a mailbox with a broken IMAP connection should timeout

## Actual Behaviour

Neomutt hangs (for at least several minutes, I'm not sure if there's some limit since I tend to just close neomutt first). Though sending `SIGINT` does tend to cause neomutt to abort the connection, re-establish a new one, and recover nicely.

## Steps to Reproduce

I noticed when neomutt was running and I disconnected my VPN (so not that reproduce-able).
However, I think an analogous setup is, while neomutt is running:

* Find an `IMAP` port in use by neomutt via `lsof -a -i 4 -i 6 -i TCP -c neomutt`
* Add an `iptables` rule to drop traffic for that port e.g. `sudo iptables -A INPUT -p tcp --dport $port_from_above -j DROP`
* Attempt to close the mailbox in neomutt (for me I tend to notice when changing folder)

## How often does this happen?

* Always (under the conditions above)

## When did it start to happen?

I'm not sure, I _think_ I had noticed it a while ago.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.17.9-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn: 1.38 (compiled with 1.38)
GPGME: 1.17.1
OpenSSL: OpenSSL 1.1.1o  3 May 2022
libnotmuch: 5.6.0
storage: kyotocabinet

Configure options: --with-ui=ncurses --ssl --gpgme --sasl --mixmaster --notmuch --kyotocabinet --gss --lua --disable-doc

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Arch Linux 5.17.9-arch1-1
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? `IMAP`

Note: if I set `imap_poll_timeout` and add polling when closing via:

```patch
diff --git a/imap/imap.c b/imap/imap.c
index fa3ab3a7f..860edcb3d 100644
--- a/imap/imap.c
+++ b/imap/imap.c
@@ -2202,7 +2202,7 @@ static enum MxStatus imap_mbox_close(struct Mailbox *m)
       if (m->msg_deleted == 0)
       {
         adata->closing = true;
-        imap_exec(adata, "CLOSE", IMAP_CMD_NO_FLAGS);
+        imap_exec(adata, "CLOSE", IMAP_CMD_POLL);
       }
       adata->state = IMAP_AUTHENTICATED;
     }
```

Then neomutt reports "connection...timed out" and successfully re-establishes a connection

This is possibly related to #3313.

**Comment by scottkosty** [comment]
I've seen similar behavior when disconnecting from a VPN, or when suspending/resuming my computer.

**Comment by gahr** [comment]
Thanks for the hint about using `IMAP_CMD_POLL`, @matthewhughes934 . We seem to be using that flag only for synchronous communications with an IMAP server (checking a mailbox's status, NOOP, flushing our write queue when it's full, etc.). Perhaps we should be using it some more, on fast operations like CLOSE. I'll investigate and think a bit about that.

**Comment by gahr** [comment]
(Note to self: keep in mind the commit message when `imap_poll_timeout` was introduced, https://github.com/neomutt/neomutt/commit/64a58521149601999b0d9e5ff4b0f39ef549a066)

**Comment by matthewhughes934** [comment]
Another hang I just noticed (got home and opened my laptop from sleep)

```
0x00007fddd6901f2c in read () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fddd6901f2c in read () at /usr/lib/libc.so.6
#1  0x00007fddd6ca17bb in  () at /usr/lib/libcrypto.so.1.1
#2  0x00007fddd6c8f15a in  () at /usr/lib/libcrypto.so.1.1
#3  0x00007fddd6c93d74 in  () at /usr/lib/libcrypto.so.1.1
#4  0x00007fddd6c93e97 in BIO_read () at /usr/lib/libcrypto.so.1.1
#5  0x00007fddd72a2093 in  () at /usr/lib/libssl.so.1.1
#6  0x00007fddd72a87f1 in  () at /usr/lib/libssl.so.1.1
#7  0x00007fddd72b59db in  () at /usr/lib/libssl.so.1.1
#8  0x00007fddd72ba0a7 in SSL_read () at /usr/lib/libssl.so.1.1
#9  0x000055cf405f78ad in ssl_socket_read
    (conn=0x55cf41d85420, buf=0x55cf41d856c4 "* STATUS <REDACTED>"..., count=1024) at conn/openssl.c:1331
#10 0x000055cf405f1a90 in mutt_socket_readchar (conn=0x55cf41d85420, c=0x7ffefe595f03 "C") at conn/socket.c:215
#11 0x000055cf405f1bf8 in mutt_socket_readln_d (buf=0x55cf425a1650 "c0010 OK Success", buflen=512, conn=0x55cf41d85420, dbg=5) at conn/socket.c:253
#12 0x000055cf405dd712 in imap_cmd_step (adata=0x55cf4353b940) at imap/command.c:1108
#13 0x000055cf405ddd10 in imap_exec (adata=0x55cf4353b940, cmdstr=0x55cf40659703 "NOOP", flags=4 '\004') at imap/command.c:1282
#14 0x000055cf405e0a27 in imap_check_mailbox (m=0x55cf4353b290, force=true) at imap/imap.c:1147
#15 0x000055cf405ecd31 in imap_keepalive () at imap/util.c:960
#16 0x000055cf404f2fa8 in km_dokey (mtype=MENU_INDEX) at keymap.c:682
#17 0x000055cf4051b756 in mutt_index_menu (dlg=0x55cf41cc8f20, m_init=0x55cf4353b290) at index/dlg_index.c:1235
#18 0x000055cf404fa7f4 in main (argc=1, argv=0x7ffefe596d28, envp=0x7ffefe596d38) at main.c:1374
```

Note `flags=4` which correspondings to `IMAP_CMD_POLL` but maybe I just started my laptop at an inopportune moment after the polling but before the actual query was made. Hitting it with `SIGINT` (via `CTRL-C`) lead to it hanging with message `Logging in...`, backtrace in that case

```
(gdb) bt
#0  0x00007fddd6901f2c in read () at /usr/lib/libc.so.6
#1  0x00007fddd6ca17bb in  () at /usr/lib/libcrypto.so.1.1
#2  0x00007fddd6c8f15a in  () at /usr/lib/libcrypto.so.1.1
#3  0x00007fddd6c93d74 in  () at /usr/lib/libcrypto.so.1.1
#4  0x00007fddd6c93e97 in BIO_read () at /usr/lib/libcrypto.so.1.1
#5  0x00007fddd72a2093 in  () at /usr/lib/libssl.so.1.1
#6  0x00007fddd72a87f1 in  () at /usr/lib/libssl.so.1.1
#7  0x00007fddd72b59db in  () at /usr/lib/libssl.so.1.1
#8  0x00007fddd72ba0a7 in SSL_read () at /usr/lib/libssl.so.1.1
#9  0x000055cf405f78ad in ssl_socket_read (conn=0x55cf41d85420, buf=0x55cf41d856c4 "* CAPABILITY <REDACTED>..., count=1024)
    at conn/openssl.c:1331
#10 0x000055cf405f1a90 in mutt_socket_readchar (conn=0x55cf41d85420, c=0x7ffefe595c83 "") at conn/socket.c:215
#11 0x000055cf405f1bf8 in mutt_socket_readln_d (buf=0x55cf425a1650 "c0000 OK Thats all she wrote! y8mb202864576wrd", buflen=512, conn=0x55cf41d85420, dbg=5) at conn/socket.c:253
#12 0x000055cf405dd712 in imap_cmd_step (adata=0x55cf4353b940) at imap/command.c:1108
#13 0x000055cf405ee078 in imap_auth_plain (adata=0x55cf4353b940, method=0x0) at imap/auth_plain.c:85
#14 0x000055cf405ed726 in imap_authenticate (adata=0x55cf4353b940) at imap/auth.c:144
#15 0x000055cf405e2a31 in imap_login (adata=0x55cf4353b940) at imap/imap.c:1860
#16 0x000055cf405dabd4 in cmd_handle_fatal (adata=0x55cf4353b940) at imap/command.c:185
#17 0x000055cf405dd761 in imap_cmd_step (adata=0x55cf4353b940) at imap/command.c:1112
#18 0x000055cf405ddd10 in imap_exec (adata=0x55cf4353b940, cmdstr=0x55cf40659703 "NOOP", flags=4 '\004') at imap/command.c:1282
#19 0x000055cf405e0a27 in imap_check_mailbox (m=0x55cf4353b290, force=true) at imap/imap.c:1147
#20 0x000055cf405ecd31 in imap_keepalive () at imap/util.c:960
#21 0x000055cf404f2fa8 in km_dokey (mtype=MENU_INDEX) at keymap.c:682
#22 0x000055cf4051b756 in mutt_index_menu (dlg=0x55cf41cc8f20, m_init=0x55cf4353b290) at index/dlg_index.c:1235
#23 0x000055cf404fa7f4 in main (argc=1, argv=0x7ffefe596d28, envp=0x7ffefe596d38) at main.c:1374
```

The above is mostly for my reference rather than hoping to contribute much to the conversation here as it's not very helpful from a reproducibility standpoint (and may just be some result of my specific setup)

**Comment by gahr** [comment]
```
#11 0x000055cf405f1bf8 in mutt_socket_readln_d (buf=0x55cf425a1650 "c0000 OK Thats all she wrote! y8mb202864576wrd", buflen=512, conn=0x55cf41d85420, dbg=5) at conn/socket.c:253
```

GMail is a fun IMAP server indeed :/
