### ISSUE TITLE
mail pager becomes unleavable after some time(? and mail in the underlying box?)/leaving it segfaults

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#3501]
## Expected Behaviour

I get the index again.

## Actual Behaviour

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055678d4375f1 in pager_global_observer (nc=0x7fff7d7f5720) at ./obj-x86_64-linux-gnu/../pager/pager.c:322

warning: Source file is more recent than executable.
322       if ((priv->redraw & PAGER_REDRAW_FLOW) && (priv->pview->flags & MUTT_PAGER_RETWINCH))
(gdb) bt
#0  0x000055678d4375f1 in pager_global_observer (nc=0x7fff7d7f5720) at ./obj-x86_64-linux-gnu/../pager/pager.c:322
#1  0x000055678d4f2577 in send (source=0x55678e9121a0, current=0x55678e9121a0, event_type=NT_GLOBAL, event_subtype=4, event_data=0x0)
    at ./obj-x86_64-linux-gnu/../mutt/notify.c:136
#2  0x000055678d3f249c in mutt_enter_command () at ./obj-x86_64-linux-gnu/../commands.c:683
#3  0x000055678d472c96 in op_enter_command (op=2105497376,
    op@entry=<error reading variable: DW_FORM_rnglistx index pointing outside of .debug_rnglists offset array [in module /usr/lib/debug/.build-id/2d/841e8f6aa1382f4870733ce1de954c2fbd2dd8.debug]>) at ./obj-x86_64-linux-gnu/../gui/global.c:61

(gdb) p priv
$1 = (struct PagerPrivateData *) 0x55678e9c5b90
(gdb) p *priv
$2 = {pview = 0x0, fp = 0x0, st = {st_dev = 39, st_ino = 609457, st_nlink = 1, st_mode = 33152, st_uid = 1000, st_gid = 100, __pad0 = 0, st_rdev = 0, st_size = 4802,
    st_blksize = 4096, st_blocks = 16, st_atim = {tv_sec = 1659997674, tv_nsec = 85788778}, st_mtim = {tv_sec = 1659997674, tv_nsec = 89788958}, st_ctim = {
      tv_sec = 1659997674, tv_nsec = 89788958}, __glibc_reserved = {0, 0, 0}}, bytes_read = 3784, lines = 0x0, lines_used = 74, lines_max = 112, cur_line = 74,
  old_top_line = 20, win_height = 54, top_line = 20, has_types = 16, quote_list = 0x0, q_level = 0, hide_quoted = 0, search_flag = 0,
  search_str = '\000' <repeats 255 times>, search_compiled = false, search_re = {buffer = 0x0, allocated = 0, used = 0, syntax = 0, fastmap = 0x0, translate = 0x0,
    re_nsub = 0, can_be_null = 0, regs_allocated = 0, fastmap_accurate = 0, no_sub = 0, not_bol = 0, not_eol = 0, newline_anchor = 0}, search_back = false,
  force_redraw = false, redraw = 4 '\004', ansi_list = {tqh_first = 0x0, tqh_last = 0x55678e9c5dc0}, notify = 0x55678e985090, rc = 0, searchctx = 0, first = false,
  wrapped = false, delay_read_timestamp = 0, pager_redraw = true, loop = PAGER_LOOP_QUIT}
(gdb) p priv->pview
$3 = (struct PagerView *) 0x0
```

## Steps to Reproduce

1. Have a mail open
2. Wait (mail comes in here, I'm assuming like a lot or whatever)
3. Attempt to go back; some stuff didn't work (q, opening (any mailbox! including a maildir one) from the sidebar), something else crashed

## How often does this happen?

Just this once.

## When did it start to happen?

Dunno. This is the first time.

## NeoMutt Version

```
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.10.0-16-amd64 (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.14.0-unknown
GnuTLS: 3.7.1
libnotmuch: 5.3.0
storage: lmdb
compression: zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --gnutls --gss --idn --mixmaster --sasl --lmdb --zlib --zstd --testing

Compilation CFLAGS: -g -O2 -ffile-prefix-map=/home/nabijaczleweli/backports/build-output/neomutt-20220429+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss
  +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster +nls +notmuch
  -openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Bullseye
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? IMAP

**Comment by nabijaczleweli** [comment]
Another repro, this time the pager cleared but nothing else happened, another core:
```
gdb neomutt core
bt
#0  0x0000555bb0a6a5f1 in pager_global_observer (nc=0x7fffb4e7baa0) at ./obj-x86_64-linux-gnu/../pager/pager.c:322
#1  0x0000555bb0b25577 in send (source=0x555bb1fcb1a0, current=0x555bb1fcb1a0, event_type=NT_GLOBAL, event_subtype=4, event_data=0x0)
    at ./obj-x86_64-linux-gnu/../mutt/notify.c:136
#2  0x0000555bb0a2549c in mutt_enter_command () at ./obj-x86_64-linux-gnu/../commands.c:683
#3  0x0000555bb0aa5c96 in op_enter_command (op=-1259881824) at ./obj-x86_64-linux-gnu/../gui/global.c:61
(gdb) list
warning: Source file is more recent than executable.
317
318       struct PagerPrivateData *priv = win_pager->wdata;
319       if (!priv)
320         return 0;
321
322       if ((priv->redraw & PAGER_REDRAW_FLOW) && (priv->pview->flags & MUTT_PAGER_RETWINCH))
323       {
324         priv->rc = OP_REFORMAT_WINCH;
325       }
326
(gdb) p priv
$1 = (struct PagerPrivateData *) 0x555bb207eb90
(gdb) p priv->pview
$2 = (struct PagerView *) 0x0
(gdb) p priv->redraw
$3 = 4 '\004'
(gdb)
```

This time nothing worked to leave (Q/opening boxes (on the same IMAP server or local) via sidebar/&c.) except a macro that did `macro index <f1> ':unmailboxes *<enter>:named-mailboxes feeds ~/mail/feeds "  podcasts" ~/mail/feeds/podcasts "  webcomics" ~/mail/feeds/webcomics<enter>:source ~/.mutt/nabijaczleweli@gmail.com<enter><change-folder>+INBOX<enter>'` to load <https://github.com/nabijaczleweli/dotfiles/blob/master/.mutt/nabijaczleweli%40gmail.com>

This, I think, is actually either the same or very similar to #3242?

**Comment by nabijaczleweli** [comment]
Happened again today, same backtrace:
```
#0  0x0000555cf60765f1 in pager_global_observer (nc=0x7ffd8180abd0) at ./obj-x86_64-linux-gnu/../pager/pager.c:322
#1  0x0000555cf6131577 in send (source=0x555cf65ce1a0, current=0x555cf65ce1a0, event_type=NT_GLOBAL, event_subtype=4, event_data=0x0)
    at ./obj-x86_64-linux-gnu/../mutt/notify.c:136
#2  0x0000555cf603149c in mutt_enter_command () at ./obj-x86_64-linux-gnu/../commands.c:683
#3  0x0000555cf60b1c96 in op_enter_command (op=-2122273840) at ./obj-x86_64-linux-gnu/../gui/global.c:61
```
