### ISSUE TITLE
Neomutt with Taskwarrior

### ISSUE THREAD

**Issue by angelus2014** [neomutt/neomutt#3509]
Not quite a Neomutt question, but I thought I could ask here anyway. Before I was using `notmuchtask` to combine Neomutt with Taskwarrior. But `notmuchtask` stopped working after a (minor) Python update and I can't see this getting fixed (`notmuchtask` seems abandoned, sadly enough).
Are there others who use Taskwarrior together with Neomutt and which 'plugin'/script could you recommend?

---
With regards,

Angelo Machils

**Comment by gour** [comment]
>  Are there others who use Taskwarrior together with Neomutt and which 'plugin'/script could you recommend?

Try [this](https://github.com/alkim0/task-attach).

Sincerely,
Gour

**Comment by angelus2014** [comment]
Hello,

On 17/08/22 04:50AM, Saša Janiška wrote:
>>  Are there others who use Taskwarrior together with Neomutt and which 'plugin'/script could you recommend?
>Try [this](https://github.com/alkim0/task-attach).

Thank you for the tip, but it's not working. It does ask for the 
description of the task, but no task is created.

-- 
With regards,

Angelo Machils

**Comment by gour** [comment]
> Thank you for the tip, but it's not working. It does ask for the description of the task, but no task is created.

Hmm, I'll try to take a look as soon as I get some free time, but at the moment I'm using [Etm](https://github.com/dagraham/etm-dgraham) with Claws-mail, but you can see my FAQ [entry](https://claws-mail.org/faq/index.php/Using_Claws_Mail_with_other_programs#Integrating_Claws-mail_with_Taskwarrior)  for integrating Claws with TW.

**Comment by gour** [comment]
> Thank you for the tip, but it's not working. It does ask for the description of the task, but no task is created.

I'm reworking my `neomutt`+`taskwarrior` setup based on `notmuch`...Not fully working yet, but try this script below....

[neomutt2task.txt](https://github.com/neomutt/neomutt/files/9440002/neomutt2task.txt)

Just remove `*.txt` extension and note that I'm recording timestamp when the task is created.

Hope it helps.

**Comment by angelus2014** [comment]
Hello,

On 28/08/22 08:50AM, Saša Janiška wrote:
>> Thank you for the tip, but it's not working. It does ask for the description of the task, but no task is created.
>
>I'm reworking my `neomutt`+`taskwarrior` setup based on `notmuch`...Not fully working yet, but try this script below....
>
>[neomutt2task.txt](https://github.com/neomutt/neomutt/files/9440002/neomutt2task.txt)
>
>Just remove `*.txt` extension and note that I'm recording timestamp when the task is created.

Thank you for your effort. In my case, it trows an error:

```
❯ python3 neomutt2task
Traceback (most recent call last):
   File "/Users/angelo/dotfiles/neomutt/.config/mutt/neomutt2task", line 12, in <module>
     from notmuch2 import Database
ModuleNotFoundError: No module named 'notmuch2'
```

I have removed the 2 from notmuch2, but now it complains that there is 
no module called `tasklib`. Tasklib is installed through pip3.


-- 
With regards,

Angelo Machils

**Comment by gour** [comment]
> Thank you for your effort. In my case, it trows an error: ❯ python3 neomutt2task Traceback (most recent call last): File "/Users/angelo/dotfiles/neomutt/.config/mutt/neomutt2task", line 12, in <module> from notmuch2 import Database ModuleNotFoundError: No module named 'notmuch2' 

You have to install [python2-notmuch2](https://pypi.org/project/notmuch2/) Python module and then check with:

```
$ python3
Python 3.10.6 (main, Aug 10 2022, 11:19:32) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import notmuch2
>>> 

```

I'm on Debian and it is packaged for it, otherwise use `pip3` :wink:

**Comment by angelus2014** [comment]
Hello,

On 29/08/22 08:29AM, Saša Janiška wrote:
>You have to install 
>[python2-notmuch2](https://pypi.org/project/notmuch2/) Python module 

On macOS, the install through pip(3) fails with several pages of 
errors...... :(


-- 
With regards,

Angelo Machils

**Comment by gour** [comment]
> On macOS, the install through pip(3) fails with several pages of errors...... :(

I'm sorry to hear it, but it's strange.

My recommendation is to [report](https://notmuchmail.org/#index9h2) it to `notmuch` devs and/or to visit IRC channel `irc://irc.libera.chat/#notmuch` ?


Sincerely,
Gour
