### ISSUE TITLE
crash: seg in imap_sync_mailbox

### ISSUE THREAD

**Issue by dagrh** [neomutt/neomutt#3511]
## Expected Behaviour

I think gmail had just disconnected, the message list went blank, and I hit 'I' to try and force it to reopen my inbox

## Actual Behaviour

a reconnect and display of inbox

If NeoMutt crashed, did your OS create a 'coredump' file?

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004bb0a7 in imap_sync_mailbox (m=m@entry=0x21f7d10, expunge=expunge@entry=true, close=close@entry=true) at imap/imap.c:1545
1545	  if (adata->state < IMAP_SELECTED)

(gdb) p adata
$1 = (struct ImapAccountData *) 0x0
#0  0x00000000004bb0a7 in imap_sync_mailbox (m=m@entry=0x21f7d10, expunge=expunge@entry=true, close=close@entry=true) at imap/imap.c:1545
#1  0x000000000042f9ce in mx_mbox_close (m=0x21f7d10) at mx.c:828
#2  0x000000000043807c in change_folder_mailbox (menu=0x269edf0, m=<optimized out>, oldcount=oldcount@entry=0x25fded4, shared=shared@entry=0x2da1f70, read_only=<optimized out>) at index/dlg_index.c:640
#3  0x00000000004383e1 in change_folder_string (menu=<optimized out>, buf=<optimized out>, buflen=<optimized out>, oldcount=oldcount@entry=0x25fded4, shared=shared@entry=0x2da1f70, read_only=read_only@entry=false)
    at index/dlg_index.c:791
#4  0x000000000043c0d9 in op_main_change_folder (shared=0x2da1f70, priv=0x25fded0, op=<optimized out>) at index/functions.c:884
#5  0x000000000043e54c in index_function_dispatcher (win=<optimized out>, op=op@entry=139) at index/functions.c:2860
#6  0x0000000000438b68 in mutt_index_menu (dlg=0x28db090, m_init=<optimized out>) at index/dlg_index.c:1333
#7  0x00000000004099dc in main (argc=<optimized out>, argv=0x7fff47e935c8, envp=<optimized out>) at main.c:1369

## Steps to Reproduce

unknown

## How often does this happen?

Seen once
## NeoMutt Version

```
```~/bin/mutt -v
NeoMutt 20220429-178-3b62e6-dirty
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.18.17-200.fc36.x86_64 (x86_64)
ncurses: ncurses 6.2.20210508 (compiled with 6.2.20210508)
libidn: 1.38 (compiled with 1.38)
OpenSSL: OpenSSL 3.0.5 5 Jul 2022
storage: tokyocabinet

Configure options: --prefix=/home/dgilbert/git/neomutt/try --tokyocabinet --ssl

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/home/dgilbert/git/neomutt/try/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls -notmuch 
  +openssl +pgp +regex -sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/home/dgilbert/git/neomutt/try/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/home/dgilbert/git/neomutt/try/etc"


## Extra Info

It's got the fix from issue 3451 on top of current main

<!-- This info might help us narrow down the source of the problem. -->

* Operating System and its version

Fedora 36

* Were you using multiple copies of NeoMutt at once?
Yep, 2 

* Were you using 'screen' or 'tmux'?

Nope,

* Is your email local (maildir) or remote (IMAP)?

IMAP via gmail

**Comment by gahr** [comment]
mh it's easy to add a check for a null adata, but I'd like to be able to reproduce it and see why we get to that point in the first place. So far I haven't been able to. I can tcpdrop my connection to gmail, but NeoMutt can reconnect straight away. Perhaps I should try simulating a longer downtime. I'll try that.
