### ISSUE TITLE
Memory leaks during limit/delete pattern

### ISSUE THREAD

**Issue by RaitoBezarius** [neomutt/neomutt#3523]
## Expected Behaviour

No memory leak

## Actual Behaviour

```
=================================================================
==2506863==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7f2e396e87cf in __interceptor_malloc (/nix/store/4v2bk6almk03mfnz4122dfz8vcxynvs3-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x6a4c8d in mutt_mem_malloc mutt/memory.c:95
    #2 0x6a78f3 in buffer_new mutt/pool.c:49
    #3 0x6a79ae in increase_buffer_pool mutt/pool.c:78
    #4 0x6a7ae5 in mutt_buffer_pool_get mutt/pool.c:104
    #5 0x45a5d2 in mutt_buffer_expand_path_regex /build/source/muttlib.c:141
    #6 0x454557 in reset_tilde /build/source/main.c:238
    #7 0x455b2d in main /build/source/main.c:713
    #8 0x7f2e388d124d in __libc_start_call_main (/nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 2048 byte(s) in 2 object(s) allocated from:
    #0 0x7f2e396e8b48 in realloc (/nix/store/4v2bk6almk03mfnz4122dfz8vcxynvs3-gcc-11.3.0-lib/lib/libasan.so.6+0xb1b48)
    #1 0x6a4d8e in mutt_mem_realloc mutt/memory.c:131
    #2 0x6a7b77 in mutt_buffer_pool_release mutt/pool.c:129
    #3 0x468611 in mutt_mailbox_list /build/source/mutt_mailbox.c:294
    #4 0x468812 in mutt_mailbox_notify /build/source/mutt_mailbox.c:234
    #5 0x494d31 in mutt_index_menu index/dlg_index.c:1177
    #6 0x45a17c in main /build/source/main.c:1374
    #7 0x7f2e388d124d in __libc_start_call_main (/nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/libc.so.6+0x2924d)

SUMMARY: AddressSanitizer: 2096 byte(s) leaked in 4 allocation(s).
```

## Steps to Reproduce

- limit to a pattern subject
- delete this pattern

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.63 (x86_64)
ncurses: ncurses 6.3.20220507 (compiled with 6.3.20220507)
libidn: 1.41 (compiled with 1.41)
GPGME: 1.18.0-unknown
OpenSSL: OpenSSL 3.0.5 5 Jul 2022
libnotmuch: 5.6.0
storage: kyotocabinet, lmdb
compression: zlib, zstd

Configure options: --prefix=/nix/store/lanpdv0pm2z9374r8i7g01hbsjpdpylb-neomutt-20220429 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags --zlib --zstd --with-kyotocabinet=/nix/store/q3srsmg3cjn1jkrg328p8lqd5adwqa3n-kyotocabinet-1.2.79 --zstd --mixmaster --asan

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Options par défaut :
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Options de compilation :
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache +homespool +idn +inotify -locales_hack -lua +mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

Devel options:
  asan 

MAILPATH="mailbox"
MIXMASTER="mixmaster"
PKGDATADIR="/nix/store/lanpdv0pm2z9374r8i7g01hbsjpdpylb-neomutt-20220429/share/neomutt"
SENDMAIL="sendmail"
SYSCONFDIR="/nix/store/lanpdv0pm2z9374r8i7g01hbsjpdpylb-neomutt-20220429/etc"

Pour en savoir plus à propos de NeoMutt, voir : https://neomutt.org
Si vous trouvez un bug dans NeoMutt, merci de le faire savoir sur :
    https://github.com/neomutt/neomutt/issues
ou envoyez un email à: <neomutt-devel@neomutt.org>
```

## Extra Info

- maildir

**Comment by gahr** [comment]
Can you please try with a recent checkout of the main branch? Also, can you please list the steps you're taking to reproduce this?
