### ISSUE TITLE
KBs of memory leak during intense usage for ≥1 week

### ISSUE THREAD

**Issue by RaitoBezarius** [neomutt/neomutt#3546]
So as always I run NeoMutt under ASAN and I quit a very long-lived instance of NeoMutt with the following output:

```
Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f0fd5d7b7cf in __interceptor_malloc (/nix/store/4v2bk6almk03mfnz4122dfz8vcxynvs3-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x6a4c8d in mutt_mem_malloc mutt/memory.c:95
    #2 0x64f402 in compr_zstd_open compress/zstd.c:57
    #3 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #4 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #5 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #6 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #7 0x4b2dcf in mutt_pager pager/dlg_pager.c:421
    #8 0x4bb802 in mutt_display_message pager/message.c:492
    #9 0x4a3045 in op_display_message index/functions.c:410
    #10 0x4a53ec in index_function_dispatcher index/functions.c:2858
    #11 0x495946 in mutt_index_menu index/dlg_index.c:1297
    #12 0x45a17c in main /build/source/main.c:1374
    #13 0x7f0fd4f6424d in __libc_start_call_main (/nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 131584 byte(s) in 1 object(s) allocated from:
    #0 0x7f0fd5d7b7cf in __interceptor_malloc (/nix/store/4v2bk6almk03mfnz4122dfz8vcxynvs3-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x6a4c8d in mutt_mem_malloc mutt/memory.c:95
    #2 0x64f44d in compr_zstd_open compress/zstd.c:59
    #3 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #4 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #5 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #6 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #7 0x4b2dcf in mutt_pager pager/dlg_pager.c:421
    #8 0x4bb802 in mutt_display_message pager/message.c:492
    #9 0x4a3045 in op_display_message index/functions.c:410
    #10 0x4a53ec in index_function_dispatcher index/functions.c:2858
    #11 0x495946 in mutt_index_menu index/dlg_index.c:1297
    #12 0x45a17c in main /build/source/main.c:1374
    #13 0x7f0fd4f6424d in __libc_start_call_main (/nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 95960 byte(s) in 1 object(s) allocated from:
    #0 0x7f0fd5d7b7cf in __interceptor_malloc (/nix/store/4v2bk6almk03mfnz4122dfz8vcxynvs3-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x7f0fd5b34253 in ZSTD_createDCtx (/nix/store/y1iq99faxkdrf28h2jz9gji0245jms6f-zstd-1.5.2/lib/libzstd.so.1+0x95253)
    #2 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #3 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #4 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #5 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #6 0x4b2dcf in mutt_pager pager/dlg_pager.c:421
    #7 0x4bb802 in mutt_display_message pager/message.c:492
    #8 0x4a3045 in op_display_message index/functions.c:410
    #9 0x4a53ec in index_function_dispatcher index/functions.c:2858
    #10 0x495946 in mutt_index_menu index/dlg_index.c:1297
    #11 0x45a17c in main /build/source/main.c:1374
    #12 0x7f0fd4f6424d in __libc_start_call_main (/nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 5080 byte(s) in 1 object(s) allocated from:
    #0 0x7f0fd5d7b7cf in __interceptor_malloc (/nix/store/4v2bk6almk03mfnz4122dfz8vcxynvs3-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x7f0fd5ac0e8b in ZSTD_createCCtx_advanced (/nix/store/y1iq99faxkdrf28h2jz9gji0245jms6f-zstd-1.5.2/lib/libzstd.so.1+0x21e8b)
    #2 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #3 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #4 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #5 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #6 0x4b2dcf in mutt_pager pager/dlg_pager.c:421
    #7 0x4bb802 in mutt_display_message pager/message.c:492
    #8 0x4a3045 in op_display_message index/functions.c:410
    #9 0x4a53ec in index_function_dispatcher index/functions.c:2858
    #10 0x495946 in mutt_index_menu index/dlg_index.c:1297
    #11 0x45a17c in main /build/source/main.c:1374
    #12 0x7f0fd4f6424d in __libc_start_call_main (/nix/store/bzd91shky9j9d43girrrj6vmqlw7x9m8-glibc-2.35-163/lib/libc.so.6+0x2924d)

SUMMARY: AddressSanitizer: 232656 byte(s) leaked in 4 allocation(s).
```

## Expected Behaviour

No memory leak.

## Actual Behaviour

Memory leaks.

## Steps to Reproduce

Alas, I have no step beyond what the functions seems to indicate, let me know if this is a bummer, I can try to reproduce it.

## How often does this happen?

It seems like it happens only after very long manipulations, including limit, etc, etc and multi-instances.

## When did it start to happen?

Do not know.

## NeoMutt Version

```
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.63 (x86_64)
ncurses: ncurses 6.3.20220507 (compiled with 6.3.20220507)
libidn: 1.41 (compiled with 1.41)
GPGME: 1.18.0-unknown
OpenSSL: OpenSSL 3.0.5 5 Jul 2022
libnotmuch: 5.6.0
storage: kyotocabinet, lmdb
compression: zlib, zstd

Configure options: --prefix=/nix/store/1s5gy5xkb3mhhwbr96h7ianrz68lbvqz-neomutt-20220429 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags --zlib --zstd --with-kyotocabinet=/nix/store/wbldbfjvswdqkvi6y1rj7d7qmqw74bnc-kyotocabinet-1.2.79 --zstd --mixmaster --asan

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Options par défaut :
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Options de compilation :
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache +homespool +idn +inotify -locales_hack -lua +mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

Devel options:
  asan 
```

## Extra Info

* NixOS
* Were you using multiple copies of NeoMutt at once? *YES*
* Were you using 'screen' or 'tmux'? *NO*
* Is your email local (maildir) or remote (IMAP)? *maildir*

**Comment by gahr** [comment]
Can you reproduce with a build off the main branch?

**Comment by RaitoBezarius** [comment]
> Can you reproduce with a build off the main branch?

Which build?

Reproduced again
```
=================================================================
==2543761==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7f44def4d7cf in __interceptor_malloc (/nix/store/hzfqs4fdgj4sj8pps4hrhzk1amdy0fhp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x6a4c8d in mutt_mem_malloc mutt/memory.c:95
    #2 0x64f402 in compr_zstd_open compress/zstd.c:57
    #3 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #4 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #5 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #6 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #7 0x4953a8 in mutt_index_menu index/dlg_index.c:1104
    #8 0x45a17c in main /build/source/main.c:1374
    #9 0x7f44de13c24d in __libc_start_call_main (/nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 263168 byte(s) in 2 object(s) allocated from:
    #0 0x7f44def4d7cf in __interceptor_malloc (/nix/store/hzfqs4fdgj4sj8pps4hrhzk1amdy0fhp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x6a4c8d in mutt_mem_malloc mutt/memory.c:95
    #2 0x64f44d in compr_zstd_open compress/zstd.c:59
    #3 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #4 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #5 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #6 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #7 0x4953a8 in mutt_index_menu index/dlg_index.c:1104
    #8 0x45a17c in main /build/source/main.c:1374
    #9 0x7f44de13c24d in __libc_start_call_main (/nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 191920 byte(s) in 2 object(s) allocated from:
    #0 0x7f44def4d7cf in __interceptor_malloc (/nix/store/hzfqs4fdgj4sj8pps4hrhzk1amdy0fhp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x7f44ded08253 in ZSTD_createDCtx (/nix/store/y6lzqg3xid4k8l5hmqzpxplxjc3s6547-zstd-1.5.2/lib/libzstd.so.1+0x95253)
    #2 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #3 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #4 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #5 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #6 0x4953a8 in mutt_index_menu index/dlg_index.c:1104
    #7 0x45a17c in main /build/source/main.c:1374
    #8 0x7f44de13c24d in __libc_start_call_main (/nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6+0x2924d)

Indirect leak of 10160 byte(s) in 2 object(s) allocated from:
    #0 0x7f44def4d7cf in __interceptor_malloc (/nix/store/hzfqs4fdgj4sj8pps4hrhzk1amdy0fhp-gcc-11.3.0-lib/lib/libasan.so.6+0xb17cf)
    #1 0x7f44dec94e8b in ZSTD_createCCtx_advanced (/nix/store/y6lzqg3xid4k8l5hmqzpxplxjc3s6547-zstd-1.5.2/lib/libzstd.so.1+0x21e8b)
    #2 0x6491e8 in mutt_hcache_open hcache/hcache.c:385
    #3 0x5b8617 in maildir_delayed_parsing maildir/maildir.c:604
    #4 0x5ba434 in maildir_mbox_check maildir/maildir.c:1320
    #5 0x471afa in mx_mbox_check /build/source/mx.c:1131
    #6 0x4953a8 in mutt_index_menu index/dlg_index.c:1104
    #7 0x45a17c in main /build/source/main.c:1374
    #8 0x7f44de13c24d in __libc_start_call_main (/nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6+0x2924d)

SUMMARY: AddressSanitizer: 465312 byte(s) leaked in 8 allocation(s).
```

If it provides any help.

**Comment by gahr** [comment]
> > Can you reproduce with a build off the main branch?
> 
> Which build?

I mean, can you please try to build NeoMutt from scratch from the main branch of the repository and see if the problem is still there?

**Comment by gahr** [comment]
@RaitoBezarius can you please try out the [devel/plug-compress-leak](https://github.com/neomutt/neomutt/tree/devel/plug-compress-leak) branch? I have fixed a leak, but I'm not sure it's related to the ones you're seeing.
