### ISSUE TITLE
Segfault on reading rc file when `ungroup`ing nonexistent group

### ISSUE THREAD

**Issue by tejing1** [neomutt/neomutt#3588]
## Expected Behaviour

I tried to `ungroup` before initializing a group, as a general cleanliness measure, in case I was reloading the config file or similar.

I expected it to do nothing in a case where the group hadn't been initialized.

## Actual Behaviour

neomutt segfaulted and coredumped. Backtrace:
```
(gdb) bt
#0  0x000000000050b960 in mutt_addrlist_clear ()
#1  0x000000000050c34b in group_remove ()
#2  0x000000000050c5a8 in mutt_grouplist_clear ()
#3  0x0000000000412fcc in parse_group ()
#4  0x0000000000426c94 in mutt_parse_rc_buffer ()
#5  0x000000000041257a in source_rc ()
#6  0x0000000000427120 in mutt_init ()
#7  0x000000000040d2a6 in main ()
```

## Steps to Reproduce

`ungroup -group foo *` when the group `foo` has not yet been touched

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my config

I added this line: `ungroup -group alternative_abusers *`
Commenting it out prevents the segfault.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.81 (x86_64)
ncurses: ncurses 6.3.20220507 (compiled with 6.3.20220507)
libidn: 1.41 (compiled with 1.41)
GPGME: 1.18.0-unknown
OpenSSL: OpenSSL 3.0.7 1 Nov 2022
libnotmuch: 5.6.0
storage: lmdb
compression: zlib, zstd

Configure options: --prefix=/nix/store/4df6gzqci3mw706m33s7hn14s3kp5xam-neomutt-20220429 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags --zlib --zstd

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache +homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="mailbox"
PKGDATADIR="/nix/store/4df6gzqci3mw706m33s7hn14s3kp5xam-neomutt-20220429/share/neomutt"
SENDMAIL="sendmail"
SYSCONFDIR="/nix/store/4df6gzqci3mw706m33s7hn14s3kp5xam-neomutt-20220429/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Nixos 22.11
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
Local

**Comment by gahr** [comment]
Thanks, I have a fix ready in the [devel/issue-3588](https://github.com/neomutt/neomutt/tree/devel/issue-3588) branch.

**Comment by tejing1** [comment]
Just compiled it, looks good, thanks. :+1:
