### ISSUE TITLE
double free or corruption (!prev) Abort (core dump) when deleting form remote IMAP 

### ISSUE THREAD

**Issue by croyleje** [neomutt/neomutt#3854]
## Expected Behavior
Select messages in remote folder and delete.

## Actual Behavior
Messages do appear to be deleted but program crashes.

If NeoMutt crashed, did your OS create a 'coredump' file?
Yes coredump file created.

## Steps to Reproduce
Delete files from remote/IMAP folder

## How often does this happen?
Occurs everytime.

## When did it start to happen?
Started happening consistently today, but has happened before.

## NeoMutt Version
NeoMutt 20230512
```
NeoMutt 20230512
Copyright (C) 1996-2020 Michael R. Elkins <me@mutt.org>
Copyright (C) 1996-2002 Brandon Long <blong@fiction.net>
Copyright (C) 1997-2009 Thomas Roessler <roessler@does-not-exist.org>
Copyright (C) 1998-2005 Werner Koch <wk@isil.d.shuttle.de>
Copyright (C) 1999-2017 Brendan Cully <brendan@kublai.com>
Copyright (C) 1999-2002 Tommi Komulainen <Tommi.Komulainen@iki.fi>
Copyright (C) 2000-2004 Edmund Grimley Evans <edmundo@rano.org>
Copyright (C) 2006-2009 Rocco Rutte <pdmef@gmx.net>
Copyright (C) 2014-2020 Kevin J. McCarthy <kevin@8t8.us>
Copyright (C) 2015-2022 Richard Russon <rich@flatcap.org>

Many others not mentioned here contributed code, fixes,
and suggestions.

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
OS Arch Linux completely updated.

##Coredump 
```
~/tmp$ gdb neomutt core.neomutt.1000.89c9d187325a458e8eaf3037882e2b03.33023.1683918018000000
GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from neomutt...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n])
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
(No debugging symbols found in neomutt)
[New LWP 33023]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `neomutt'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd1d309f26c in ?? () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007fd1d309f26c in  () at /usr/lib/libc.so.6
#1  0x00007fd1d304fa08 in raise () at /usr/lib/libc.so.6
#2  0x00007fd1d3038538 in abort () at /usr/lib/libc.so.6
#3  0x00007fd1d30392db in  () at /usr/lib/libc.so.6
#4  0x00007fd1d30a91b7 in  () at /usr/lib/libc.so.6
#5  0x00007fd1d30ab3b4 in  () at /usr/lib/libc.so.6
#6  0x00007fd1d30adcb3 in free () at /usr/lib/libc.so.6
#7  0x000055a7131c2dea in  ()
#8  0x000055a7130e0807 in  ()
#9  0x000055a7130dd5c2 in  ()
#10 0x000055a7130e5292 in  ()
#11 0x000055a712e618a8 in  ()
#12 0x000055a712e9b2a0 in  ()
#13 0x000055a712ea6c16 in  ()
#14 0x000055a712e8dec4 in  ()
#15 0x000055a712e2e355 in  ()
#16 0x00007fd1d3039850 in  () at /usr/lib/libc.so.6
#17 0x00007fd1d303990a in __libc_start_main () at /usr/lib/libc.so.6
#18 0x000055a712dcd045 in  ()
(gdb)
```

I am not very familiar with `gdb` or coredumps but if there is any other command you would like me to run let me or I can supply the complete dump file.

**Comment by mlmatlock** [comment]
Noticing the same thing with 20230517 release.

**Comment by mlmatlock** [comment]
Does this help?

http://ix.io/4w3x

**Comment by flatcap** [comment]
Very helpful, thanks!

```
main.c:1351:             main                   (argc=1, argv=0x7ffd7d6767b8, envp=0x7ffd7d6767c8)
index/dlg_index.c:1352:  mutt_index_menu        (dlg=0x556814f0c6f0, m_init=0x55681479d800)
sidebar/functions.c:387: sb_function_dispatcher (win=0x556814f079d0, op=274)
sidebar/functions.c:230: op_sidebar_open        (wdata=0x556814f07a90, op=274)
index/dlg_index.c:1454:  dlg_change_folder      (dlg=0x556814f0c6f0, m=0x55681479d800)
index/dlg_index.c:640:   change_folder_mailbox  (menu=0x556814f0ca20, m=0x55681479d800, oldcount=0x556814d75bd4, shared=0x556814f05250, read_only=false)
mx.c:829:                mx_mbox_close          (m=0x556814f05680)
imap/imap.c:1674:        imap_sync_mailbox      (m=0x556814f05680, expunge=true, close=true)
imap/imap.c:343:         sync_helper            (m=0x556814f05680, right=4, flag=MUTT_DELETED, name=0x5568139214f8 "\\Deleted")
imap/imap.c:1000:        imap_exec_msgset       (m=0x556814f05680, pre=0x556813921218 "UID STORE", post=0x7ffd7d6753c0 "+FLAGS.SILENT (\\Deleted)", flag=MUTT_DELETED, changed=true, invert=false)
mutt/memory.c:75:        mutt_mem_free          (ptr=0x556814f056d8)
```

**Comment by croyleje** [comment]
```
/var/lib/systemd/coredump$ coredumpctl gdb neomutt
           PID: 2150 (neomutt)
           UID: 1000 (amd)
           GID: 1000 (amd)
        Signal: 6 (ABRT)
     Timestamp: Wed 2023-05-17 14:55:48 EDT (17min ago)
  Command Line: neomutt
    Executable: /usr/bin/neomutt
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (amd)
       Boot ID: ef8366ea26954e2fbe2f6b05fde70bdd
    Machine ID: 3d4e0c8ce63343238507dcec02cfb70b
      Hostname: arch
       Storage: /var/lib/systemd/coredump/core.neomutt.1000.ef8366ea26954e2fbe2f6b05fde70bdd.2150.1684349748000000.zst (present)
  Size on Disk: 1.3M
       Message: Process 2150 (neomutt) of user 1000 dumped core.

                Stack trace of thread 2150:
                #0  0x00007feab049f26c n/a (libc.so.6 + 0x8926c)
                #1  0x00007feab044fa08 raise (libc.so.6 + 0x39a08)
                #2  0x00007feab0438538 abort (libc.so.6 + 0x22538)
                #3  0x00007feab04392db n/a (libc.so.6 + 0x232db)
                #4  0x00007feab04a91b7 n/a (libc.so.6 + 0x931b7)
                #5  0x00007feab04ab6ae n/a (libc.so.6 + 0x956ae)
                #6  0x00007feab04adcb3 __libc_free (libc.so.6 + 0x97cb3)
                #7  0x000055a5ab66edea n/a (neomutt + 0x67fdea)
                #8  0x000055a5ab58c807 n/a (neomutt + 0x59d807)
                #9  0x000055a5ab5895c2 n/a (neomutt + 0x59a5c2)
                #10 0x000055a5ab591292 n/a (neomutt + 0x5a2292)
                #11 0x000055a5ab30d8a8 n/a (neomutt + 0x31e8a8)
                #12 0x000055a5ab3472a0 n/a (neomutt + 0x3582a0)
                #13 0x000055a5ab352c16 n/a (neomutt + 0x363c16)
                #14 0x000055a5ab339ec4 n/a (neomutt + 0x34aec4)
                #15 0x000055a5ab2da355 n/a (neomutt + 0x2eb355)
                #16 0x00007feab0439850 n/a (libc.so.6 + 0x23850)
                #17 0x00007feab043990a __libc_start_main (libc.so.6 + 0x2390a)
                #18 0x000055a5ab279045 n/a (neomutt + 0x28a045)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/neomutt...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Reading symbols from /home/amd/.cache/debuginfod_client/2fb1ab7e0ba9b2958012733c4959f6b48ff809f1/debuginfo...
[New LWP 2150]
                                                                                                                                                                                                                                                                                  --Type <RET> for more, q to quit, c to continue without paging--c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `neomutt'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140728372428000}}
        ret = <optimized out>
#1  0x00007feab049f2d3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007feab044fa08 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007feab0438538 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
#4  0x00007feab04392db in __libc_message (fmt=fmt@entry=0x7feab05b3515 "%s\n") at ../sysdeps/posix/libc_fatal.c:150
        ap = {{gp_offset = 16, fp_offset = 21925, overflow_arg_area = 0x7ffde0a5fec0, reg_save_area = 0x7ffde0a5fe50}}
        fd = 2
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#5  0x00007feab04a91b7 in malloc_printerr (str=str@entry=0x7feab05b62d8 "free(): double free detected in tcache 2") at malloc.c:5651
#6  0x00007feab04ab6ae in _int_free (av=0x7feab05f1ba0 <main_arena>, p=0x55a5adca0510, have_lock=have_lock@entry=0) at malloc.c:4459
        tmp = <optimized out>
        cnt = <optimized out>
        e = 0x55a5adca0520
        tc_idx = 24
        size = 416
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
#7  0x00007feab04adcb3 in __GI___libc_free (mem=<optimized out>) at malloc.c:3367
        ar_ptr = <optimized out>
        p = <optimized out>
        err = 2
#8  0x000055a5ab66edea in mutt_mem_free (ptr=0x55a5adc96918) at mutt/memory.c:75
        p = 0x55a5adc96918
#9  0x000055a5ab58c807 in imap_exec_msgset (m=0x55a5adc968c0, pre=0x55a5ab68d210 "UID STORE", post=0x7ffde0a60060 "+FLAGS.SILENT (\\Deleted)", flag=MUTT_DELETED, changed=true, invert=false) at imap/imap.c:1000
        adata = 0x55a5adbe2630
        emails = 0x55a5adca0520
        pos = 0
        rc = 0
        count = 0
        cmd = {data = 0x0, dptr = 0x0, dsize = 0}
        c_sort = SORT_THREADS
#10 0x000055a5ab5895c2 in sync_helper (m=0x55a5adc968c0, right=4, flag=MUTT_DELETED, name=0x55a5ab68d4f0 "\\Deleted") at imap/imap.c:343
        count = 0
        rc = -1
        buf = "+FLAGS.SILENT (\\Deleted)", '\000' <repeats 999 times>
#11 0x000055a5ab591292 in imap_sync_mailbox (m=0x55a5adc968c0, expunge=true, close=false) at imap/imap.c:1674
        emails = 0x55a5adca0520
        rc = 0
        adata = 0x55a5adbe2630
        mdata = 0x55a5adcac100
        check = MX_STATUS_REOPENED
        c_sort = SORT_THREADS
        c_message_cache_clean = false
        __func__ = "imap_sync_mailbox"
#12 0x000055a5ab30d8a8 in mx_mbox_sync (m=0x55a5adc968c0) at /usr/src/debug/neomutt/neomutt-20230512/mx.c:1002
        rc = MX_STATUS_OK
        purge = 1
--Type <RET> for more, q to quit, c to continue without paging--c
        msgcount = 2
        deleted = 2
        c_trash = 0x55a5ad6fe070 "imaps://imap.gmail.com/[Gmail]/Trash"
        m_trash = 0x55a5adc97620
        __func__ = "mx_mbox_sync"
#13 0x000055a5ab3472a0 in op_main_sync_folder (shared=0x55a5ad6ed0f0, priv=0x55a5ad71e690, op=180) at index/functions.c:1621
        ovc = 2
        oc = 2
        e = 0x0
        index = 1
        check = 21925
#14 0x000055a5ab352c16 in index_function_dispatcher (win=0x55a5ad561b50, op=180) at index/functions.c:3017
        fn = 0x55a5ab6daec0 <IndexFunctions+1824>
        i = 76
        priv = 0x55a5ad71e690
        dlg = 0x55a5ad6f70a0
        shared = 0x55a5ad6ed0f0
        rc = -7
        result = 0x55a5adc968c0 "\200\376ʭ\245U"
        __func__ = "index_function_dispatcher"
#15 0x000055a5ab339ec4 in mutt_index_menu (dlg=0x55a5ad6f70a0, m_init=0x55a5ad720b90) at index/dlg_index.c:1333
        c_arrow_cursor = false
        c_braille_friendly = false
        index = 1
        c_auto_tag = true
        shared = 0x55a5ad6ed0f0
        panel_index = 0x55a5ad6e8a60
        priv = 0x55a5ad71e690
        op = 180
        c_collapse_all = false
        rc = -1
        __func__ = "mutt_index_menu"
#16 0x000055a5ab2da355 in main (argc=1, argv=0x7ffde0a61548, envp=0x7ffde0a61558) at /usr/src/debug/neomutt/neomutt-20230512/main.c:1351
        dlg = 0x55a5ad6f70a0
        m = 0x55a5ad720b90
        c_read_only = false
        subject = 0x0
        include_file = 0x0
        draft_file = 0x0
        new_type = 0x0
        dlevel = 0x0
        dfile = 0x0
        cli_nntp = 0x0
        e = 0x0
        attach = {stqh_first = 0x0, stqh_last = 0x7ffde0a60ee0}
        commands = {stqh_first = 0x0, stqh_last = 0x7ffde0a60ed0}
        queries = {stqh_first = 0x0, stqh_last = 0x7ffde0a60ec0}
        alias_queries = {stqh_first = 0x0, stqh_last = 0x7ffde0a60eb0}
        cc_list = {stqh_first = 0x0, stqh_last = 0x7ffde0a60ea0}
        bcc_list = {stqh_first = 0x0, stqh_last = 0x7ffde0a60e90}
        sendflags = 0
        flags = 0 '\000'
        version = 0
        i = 0
        explicit_folder = false
        dump_variables = false
        one_liner = false
        hide_sensitive = false
        batch_mode = false
        edit_infile = false
        double_dash = 1
        nargc = 1
        rc = 1
        repeat_error = true
        folder = {data = 0x55a5ad6fbc60 "imaps://agent@jasoncroyle.com:993/INBOX", dptr = 0x55a5ad6fbc87 "", dsize = 4224}
        expanded_infile = {data = 0x0, dptr = 0x0, dsize = 0}
        tempfile = {data = 0x0, dptr = 0x0, dsize = 0}
        cs = 0x55a5ad5141f0
        rc2 = 0
        c_autocrypt = false
        c_folder = 0x55a5ad71a7c0 "imaps://imap.gmail.com/[Gmail]/Drafts"
        __func__ = "main"
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007feab049f2d3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007feab044fa08 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007feab0438538 in __GI_abort () at abort.c:79
#4  0x00007feab04392db in __libc_message (fmt=fmt@entry=0x7feab05b3515 "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#5  0x00007feab04a91b7 in malloc_printerr (str=str@entry=0x7feab05b62d8 "free(): double free detected in tcache 2") at malloc.c:5651
#6  0x00007feab04ab6ae in _int_free (av=0x7feab05f1ba0 <main_arena>, p=0x55a5adca0510, have_lock=have_lock@entry=0) at malloc.c:4459
#7  0x00007feab04adcb3 in __GI___libc_free (mem=<optimized out>) at malloc.c:3367
#8  0x000055a5ab66edea in mutt_mem_free (ptr=0x55a5adc96918) at mutt/memory.c:75
#9  0x000055a5ab58c807 in imap_exec_msgset (m=0x55a5adc968c0, pre=0x55a5ab68d210 "UID STORE", post=0x7ffde0a60060 "+FLAGS.SILENT (\\Deleted)", flag=MUTT_DELETED, changed=true, invert=false) at imap/imap.c:1000
#10 0x000055a5ab5895c2 in sync_helper (m=0x55a5adc968c0, right=4, flag=MUTT_DELETED, name=0x55a5ab68d4f0 "\\Deleted") at imap/imap.c:343
#11 0x000055a5ab591292 in imap_sync_mailbox (m=0x55a5adc968c0, expunge=true, close=false) at imap/imap.c:1674
#12 0x000055a5ab30d8a8 in mx_mbox_sync (m=0x55a5adc968c0) at /usr/src/debug/neomutt/neomutt-20230512/mx.c:1002
#13 0x000055a5ab3472a0 in op_main_sync_folder (shared=0x55a5ad6ed0f0, priv=0x55a5ad71e690, op=180) at index/functions.c:1621
#14 0x000055a5ab352c16 in index_function_dispatcher (win=0x55a5ad561b50, op=180) at index/functions.c:3017
#15 0x000055a5ab339ec4 in mutt_index_menu (dlg=0x55a5ad6f70a0, m_init=0x55a5ad720b90) at index/dlg_index.c:1333
#16 0x000055a5ab2da355 in main (argc=1, argv=0x7ffde0a61548, envp=0x7ffde0a61558) at /usr/src/debug/neomutt/neomutt-20230512/main.c:1351
```

**Comment by flatcap** [comment]
Thanks, @croyleje that's more enlightening :-)
