### ISSUE TITLE
SIGSEGV on `next-thread` in empty view

### ISSUE THREAD

**Issue by Werkov** [neomutt/neomutt#3959]
## Expected Behaviour

Program continues execution (with no action effectively taken).

## Actual Behaviour

Program segfaults.

If NeoMutt crashed, did your OS create a 'coredump' file?

```
#0  0x000000000042b10d in mutt_aside_thread (e=0x0, forwards=forwards@entry=true, subthreads=false) at mutt_thread.c:1301
1301	  cur = e->thread;
(gdb) bt
#0  0x000000000042b10d in mutt_aside_thread (e=0x0, forwards=forwards@entry=true, subthreads=false) at mutt_thread.c:1301
#1  0x0000000000439aac in op_main_next_thread (shared=0xa88190, priv=0xa9af00, op=<optimized out>) at index/functions.c:1365
#2  0x000000000043ddd0 in index_function_dispatcher (win=<optimized out>, op=157) at index/functions.c:3043
#3  0x0000000000437f21 in dlg_index ()
#4  0x000000000040974b in main ()
```

## Steps to Reproduce

- Open a folder
- Apply filter that matches no messages (e.g. `l ~s unexisting-string<Enter>`)
- Try `<Ctrl>-N`
- `'./neomutt' terminated by signal SIGSEGV (Address boundary error)`

## How often does this happen?

- Always (steps are above)

## When did it start to happen?

- When I accidentally used `<Ctrl>-N` for the first time

## NeoMutt Version

```
eoMutt 20230517-199-d2da0b
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.3.9-1-default (x86_64)
ncurses: ncurses 6.4.20230617 (compiled with 6.4.20230617)
libidn2: 2.3.4 (compiled with 2.3.4)
libnotmuch: 5.6.0

Configure options: --notmuch --disable-doc

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include -DNCURSES_WIDECHAR -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss -hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex -sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version: openSUSE Tumbleweed 20230709
* Were you using multiple copies of NeoMutt at once? yes
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

**Comment by flatcap** [comment]
Sorry about that, @Werkov.
Thanks for the detailed bug report, that made it very easy to [reproduce and fix](https://github.com/neomutt/neomutt/pull/3962).
