### ISSUE TITLE
After receiving new mail in mailbox when viewing from attach-message: huge ID (IMAP-only), tagging attaches twice, subsequent mailbox re-open SIGABRTs or new-mail open SIGSEGVs

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#3986]
happens on 20230517+dfsg-0.1~bpo11+2 and 186c63f8f8ece4c9c38d2b3b9270323d4205cb8f

## Expected Behaviour

no crash

## Actual Behaviour

yes crash

If NeoMutt crashed, did your OS create a 'coredump' file? yeah

## Steps to Reproduce

c~/mail/INBOX (or +INBOX on IMAP)
% (optional)
m (click through, whatever data)
attach-message ~/mail/INBOX (or +INBOX on IMAP)
[in another teletype now do `mail $(id -u)`, or just make yourself receive mail]
imap-fetch-mail (if on IMAP, mbox autorefreshes)
the seqid is huge: ![](https://github.com/neomutt/neomutt/assets/6709544/a363b8e2-aae8-4220-b5c3-7e3653faefd4) (if on imap)
tag the new message
q
it's attached twice! ![](https://github.com/neomutt/neomutt/assets/6709544/3ef32551-ef83-43d9-b047-1b04d8e4f56a)
either send or discard the mail
the message will still have a huge ID (if on IMAP)

c~/mail/INBOX (or +INBOX on IMAP) again (or reopen it from sidebar):
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7dedd9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7d9ef32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7d89472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7de2340 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7efc459 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff7df76ba in malloc_printerr (str=str@entry=0x7ffff7eff158 "double free or corruption (!prev)") at ./malloc/malloc.c:5660
#6  0x00007ffff7df972c in _int_free (av=0x7ffff7f35c60 <main_arena>, p=0x555555de9f00, have_lock=<optimized out>, have_lock@entry=0) at ./malloc/malloc.c:4587
#7  0x00007ffff7dfbd9f in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3385
#8  0x00005555556522f6 in mutt_mem_free (ptr=ptr@entry=0x7ffff73b6218) at mutt/memory.c:75
#9  0x000055555563baa8 in email_free (ptr=0x7ffff73b6218) at email/email.c:71
#10 0x0000555555599123 in mx_fastclose_mailbox (m=m@entry=0x5555557e1cf0, keep_account=false) at mx.c:460
#11 0x0000555555599ca9 in mx_mbox_close (m=0x5555557e1cf0) at mx.c:912
#12 0x00005555555a2924 in change_folder_mailbox (menu=0x555555817da0, m=0x5555557e1cf0, oldcount=0x5555556ecd14, shared=shared@entry=0x555555816460, read_only=false)
    at index/dlg_index.c:640
#13 0x00005555555a5926 in op_main_change_folder (shared=0x555555816460, priv=0x5555556ecd10, op=<optimized out>) at index/functions.c:895
#14 0x00005555555a416e in index_function_dispatcher (win=<optimized out>, op=op@entry=139) at index/functions.c:3044
#15 0x00005555555a3b8e in dlg_index (dlg=dlg@entry=0x5555557c61d0, m_init=<optimized out>) at index/dlg_index.c:1351
#16 0x000055555558e8d0 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1360
```

if you open the new message instead of reopening:
```
                  Program received signal SIGSEGV, Segmentation fault.
                                                                      0x00005555556434a5 in unlink_message (old=old@entry=0x555555e3bbc0, cur=cur@entry=0x555555e61b20) at email/thread.c:70
70        if (cur->prev)
(gdb) bt
#0  0x00005555556434a5 in unlink_message (old=old@entry=0x555555e3bbc0, cur=cur@entry=0x555555e61b20) at email/thread.c:70
#1  0x0000555555595b1f in mutt_sort_threads (tctx=0x55555582d370, init=<optimized out>) at mutt_thread.c:1090
#2  0x000055555559f7c8 in mutt_sort_headers (mv=mv@entry=0x55555582d290, init=<optimized out>) at sort.c:408
#3  0x00005555555a2768 in update_index_threaded (mv=0x55555582d290, check=MX_STATUS_NEW_MAIL, oldcount=1585) at index/dlg_index.c:436
#4  update_index (menu=0x555555817da0, mv=0x55555582d290, check=check@entry=MX_STATUS_NEW_MAIL, oldcount=1585, shared=shared@entry=0x555555816460) at index/dlg_index.c:553
#5  0x00005555555a491c in op_display_message (shared=0x555555816460, priv=0x5555556ecd10, op=0) at index/functions.c:431
#6  0x00005555555a416e in index_function_dispatcher (win=<optimized out>, op=op@entry=72) at index/functions.c:3044
#7  0x00005555555a3b8e in dlg_index (dlg=dlg@entry=0x5555557c61d0, m_init=<optimized out>) at index/dlg_index.c:1351
#8  0x000055555558e8d0 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1360
```

## How often does this happen?

- Always

## When did it start to happen?
idk

## NeoMutt Version

```
$ ./neomutt -v
NeoMutt 20230517-305-687829
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.1.0-9-amd64 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)

Configure options: --disable-doc --disable-idn2

Compilation CFLAGS: -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme
  -gsasl -gss -hcache -homespool -idn +inotify -locales_hack -lua -mixmaster
  +nls -notmuch -openssl +pgp +regex -sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
```
$ neomutt -v
NeoMutt 20230517
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.1.0-9-amd64 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
GPGME: 1.18.0
GnuTLS: 3.7.9
libnotmuch: 5.6.0
storage: lmdb
compression: zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --gnutls --gss --idn2 --mixmaster --gsasl --lmdb --zlib --zstd

Compilation CFLAGS: -g -O2 -ffile-prefix-map=/home/nabijaczleweli/backports/build-output/neomutt-20230517+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.4 -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include/p11-kit-1 -I/usr/include -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme
  +gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster
  +nls +notmuch -openssl +pgp +regex -sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
## Extra Info

* Operating System and its version: bookworm
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? either

**Comment by flatcap** [comment]
Thanks for all the debugging.
I can repeat the problem and I understand what's going wrong.
The new mail causes the thread-tree to be rebuilt, but someone's still using the old one.

My [ASAN](https://neomutt.org/dev/analysis/asan) backtrace
```
memory allocated
main.c:1360:               main
index/dlg_index.c:1351:    dlg_index
index/functions.c:3044:    index_function_dispatcher
index/functions.c:768:     op_mail
send/send.c:2737:          mutt_send_message
compose/dlg_compose.c:365: dlg_compose
compose/functions.c:1981:  compose_function_dispatcher
compose/functions.c:776:   op_attachment_attach_message
index/dlg_index.c:1205:    dlg_index
index/dlg_index.c:553:     update_index
index/dlg_index.c:436:     update_index_threaded
sort.c:408:                mutt_sort_headers
mutt_thread.c:1146:        mutt_sort_threads

memory freed
main.c:1360:               main
index/dlg_index.c:1351:    dlg_index
index/functions.c:3044:    index_function_dispatcher
index/functions.c:768:     op_mail
send/send.c:2737:          mutt_send_message
compose/dlg_compose.c:365: dlg_compose
compose/functions.c:1981:  compose_function_dispatcher
compose/functions.c:776:   op_attachment_attach_message
index/dlg_index.c:1374:    dlg_index
mview.c:63:                mview_free
mutt_thread.c:374:         mutt_thread_ctx_free
mutt/hash.c:472:           mutt_hash_free
mutt_thread.c:1026:        thread_hash_destructor

memory used
main.c:1360:               main
index/dlg_index.c:1351:    dlg_index
index/functions.c:3044:    index_function_dispatcher
index/functions.c:768:     op_mail
send/send.c:2737:          mutt_send_message
compose/dlg_compose.c:365: dlg_compose
compose/functions.c:1981:  compose_function_dispatcher
compose/functions.c:776:   op_attachment_attach_message
index/dlg_index.c:1071:    dlg_index
mview.c:97:                mview_new
mview.c:215:               mview_update
sort.c:408:                mutt_sort_headers
mutt_thread.c:1085:        mutt_sort_threads
```
