### ISSUE TITLE
notmuch query

### ISSUE THREAD

**Issue by JonJFineman** [neomutt/neomutt#4055]
## Expected Behaviour

Open a notmuch virtual mailbox

## Actual Behaviour
Illegal instruction (core dumped)

Didn't work.

If NeoMutt crashed, did your OS create a 'coredump' file? yes

## Steps to Reproduce
Open below mailbox:
```
virtual-mailboxes "UNREAD" "notmuch://?query=tag:unread \
  and not tag:deleted \
  and not tag:move:trash \
  and not folder:Sent \
  and not folder:Trash \
  and not folder:Feeds.yt_pending \
  and not folder:Feeds.ted_pending \
  and not folder:Feeds.z_rejected_pending \
  and not folder:Spam \
  and not folder:sales"
```

## How often does this happen?

- Always yes

- On a particular email
  If the email isn't private, please attach it to this issue.

Other virtual mailboxes work, for ex:
virtual-mailboxes "All-Mbox" "notmuch://?query=* (not folder:Trash and not folder:Sent and not tag:move:trash)"

## When did it start to happen?

- When I upgraded yes
  Which version did you use to use?
commit 8c90f5e2cde587ad4742be813737da4bd7f3957a

- When I changed my config
  Can you narrow down **what** you changed?

## NeoMutt Version

```
+ /home/jjf/bin/x_neomutt -v
NeoMutt 20230517-448-8c90f5-dirty
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 7.4 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.17
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.22.0
LibreSSL: LibreSSL 3.8.2
OpenSSL: LibreSSL 3.8.2
libnotmuch: 5.6.0
storage: tdb

Configure options: --autocrypt --with-lock=flock --fmemopen --gpgme --notmuch --ssl --sasl --sqlite --tdb --debug --disable-doc

Compilation CFLAGS: -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/local/include -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt -fcntl +flock +fmemopen +futimens +getaddrinfo -gnutls +gpgme 
  -gsasl -gss +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

```
Reading notmuch://?query=tag:unread   and not tag:deleted   and not tag:move:trash   and not folder:Sent   and not folder:Trash   and not folder:Feeds.yt_pending   and not f
older:Feeds.ted_pending   and not folder:Feeds.z_rejected_pending   and not folder:Spam   and not folder:sales...Illegal instruction (core dumped)                           
```

```
$: egdb bin/x_neomutt x_neomutt.core
GNU gdb (GDB) 9.2
Reading symbols from bin/x_neomutt...
(No debugging symbols found in bin/x_neomutt)
[New process 469889]
Core was generated by `x_neomutt'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000003e9fd142b87 in mutt_hash_find_elem ()
(gdb) bt
#0  0x000003e9fd142b87 in mutt_hash_find_elem ()
#1  0x000003e9fd12772a in cs_get_elem ()
#2  0x000003e9fd12a8ab in cs_subset_create_inheritance ()
#3  0x000003e9fd12467c in cs_subset_number ()
#4  0x000003e9fd042d1b in log_disp_curses ()
#5  0x000003e9fd146d7a in send ()
#6  0x000003e9fd0acb61 in window_notify_all ()
#7  0x000003e9fd0acb78 in window_notify_all ()
#8  0x000003e9fd0ad322 in mutt_window_reflow ()
#9  0x000003e9fd0ac629 in msgwin_set_text ()
#10 0x000003e9fd0ac0bb in msgwin_window_observer ()
#11 0x000003e9fd146dc8 in send ()
#12 0x000003e9fd0acb61 in window_notify_all ()
#13 0x000003e9fd0acb78 in window_notify_all ()
#14 0x000003e9fd0acb78 in window_notify_all ()
#15 0x000003e9fd0ad322 in mutt_window_reflow ()
#16 0x000003e9fd0ac629 in msgwin_set_text ()
#17 0x000003e9fd0ac0bb in msgwin_window_observer ()
#18 0x000003e9fd146dc8 in send ()
#19 0x000003e9fd0acb61 in window_notify_all ()
#20 0x000003e9fd0acb78 in window_notify_all ()
#21 0x000003e9fd0acb78 in window_notify_all ()
#22 0x000003e9fd0ad322 in mutt_window_reflow ()
#23 0x000003e9fd0ac629 in msgwin_set_text ()
#24 0x000003e9fd0ac0bb in msgwin_window_observer ()
#25 0x000003e9fd146dc8 in send ()
#26 0x000003e9fd0acb61 in window_notify_all ()
#27 0x000003e9fd0acb78 in window_notify_all ()
#28 0x000003e9fd0acb78 in window_notify_all ()
#29 0x000003e9fd0ad322 in mutt_window_reflow ()
#30 0x000003e9fd0ac629 in msgwin_set_text ()
#31 0x000003e9fd0ac0bb in msgwin_window_observer ()
#32 0x000003e9fd146dc8 in send ()
#33 0x000003e9fd0acb61 in window_notify_all ()
#34 0x000003e9fd0acb78 in window_notify_all ()
#35 0x000003e9fd0acb78 in window_notify_all ()
#36 0x000003e9fd0ad322 in mutt_window_reflow ()
#37 0x000003e9fd0ac629 in msgwin_set_text ()
#38 0x000003e9fd0ac0bb in msgwin_window_observer ()
#39 0x000003e9fd146dc8 in send ()
#40 0x000003e9fd0acb61 in window_notify_all ()
#41 0x000003e9fd0acb78 in window_notify_all ()
```
and it goes on and on
I got tired of waiting after line 27000.

* Operating System and its version
  kern.version=OpenBSD 7.4-beta (GENERIC.MP) #1376: Sat Sep 23 20:21:38 MDT 2023
      deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP

  Same results with the same build (different compile options) on Alpinelinux 3.18.4

* Were you using multiple copies of NeoMutt at once? No.
* Were you using 'screen' or 'tmux'? No.
* Is your email local (maildir) or remote (IMAP)? Maildir

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @JonJFineman, it was very helpful.

The new resizeable Message Window had a bit of a problem if it wasn't visible.

Please can you give branch [[devel/msgwin]](https://github.com/neomutt/neomutt/tree/devel/msgwin) a try.

Thanks!

**Comment by JonJFineman** [comment]
Thanks. That works.
