### ISSUE TITLE
core dump while quitting 

### ISSUE THREAD

**Issue by JonJFineman** [neomutt/neomutt#4059]
## Expected Behaviour

I was searching for emails with the "l" command. I quit that, got the expected sorting mail box. Quit that folder and got a core dump.

## Actual Behaviour

Didn't exit cleanly.

If NeoMutt crashed, did your OS create a 'coredump' file?

## How often does this happen?

- Always

- Sometimes

- On a particular email
  If the email isn't private, please attach it to this issue.

Once. Can't reproduce.

## When did it start to happen?

- When I upgraded yes
  Which version did you use to use?

- When I changed my config
  Can you narrow down **what** you changed?

## NeoMutt Version

```
x_neomutt -v
NeoMutt 20231006-dirty
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 7.4 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.17
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.22.0
LibreSSL: LibreSSL 3.8.2
OpenSSL: LibreSSL 3.8.2
libnotmuch: 5.6.0
storage: tdb

Configure options: --autocrypt --with-lock=flock --fmemopen --gpgme --notmuch --ssl --sasl --sqlite --tdb --debug --disable-doc

Compilation CFLAGS: -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/local/include -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt -fcntl +flock +fmemopen +futimens +getaddrinfo -gnutls +gpgme 
  -gsasl -gss +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
```
kern.version=OpenBSD 7.4 (GENERIC.MP) #1395: Thu Oct  5 11:25:53 MDT 2023 deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? maildir

```
egdb x_neomutt x_neomutt.core 

Reading symbols from x_neomutt...
(No debugging symbols found in x_neomutt)
[New process 573064]
Core was generated by `x_neomutt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000001b8133fd64a in msgcont_get_msgwin ()
(gdb) bt
#0  0x000001b8133fd64a in msgcont_get_msgwin ()
#1  0x000001b8133fe681 in msgwin_set_text ()
#2  0x000001b813422dbe in nm_mdata_free ()
#3  0x000001b813472762 in mailbox_free ()
#4  0x000001b813471b33 in account_mailbox_remove ()
#5  0x000001b813471c49 in account_free ()
#6  0x000001b8134730d9 in neomutt_free ()
#147 000001b81338dfff in main ()
```

**Comment by flatcap** [comment]
> Should I try to reproduce this and report?

Yes, please :heart:

**Comment by scottkosty** [comment]
> > Should I try to reproduce this and report?
> 
> Yes, please ❤️

Will do. Might take me some time though since I'm traveling.
