### ISSUE TITLE
Crash on startup, in expando parsing of mix_entry_format

### ISSUE THREAD

**Issue by stefanor** [neomutt/neomutt#4406]
## Expected Behaviour

Start neomutt.

## Actual Behaviour

Segfault.

If NeoMutt crashed, did your OS create a 'coredump' file?

```
Program received signal SIGSEGV, Segmentation fault.
Download failed: Invalid argument.  Continuing without source file ./string/../sysdeps/x86_64/multiarch/strlen-avx2.S.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
warning: 76	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x0000555555683e69 in skip_classic_expando
    (str=str@entry=0x55555575bcb2 "n %c %-16s %a", defs=defs@entry=0x5555556abf14)
    at ../expando/helpers.c:154
#2  0x0000555555682b10 in node_expando_parse
    (str=str@entry=0x55555575bcb1 "4n %c %-16s %a", parsed_until=parsed_until@entry=0x7fffffffaca0, defs=defs@entry=0x5555556abf14, flags=flags@entry=0 '\000', error=error@entry=0x7fffffffacf0) at ../expando/node_expando.c:245
#3  0x00005555556836fd in node_parse
    (str=0x55555575bcb1 "4n %c %-16s %a", end=end@entry=0x0, condition_start=condition_start@entry=CON_NO_CONDITION, parsed_until=parsed_until@entry=0x7fffffffaca0, defs=defs@entry=0x5555556abf14, error=error@entry=0x7fffffffacf0) at ../expando/parse.c:272
#4  0x0000555555683be3 in node_tree_parse
    (root=root@entry=0x7ffffffface8, string=<optimized out>, defs=defs@entry=0x5555556abf14, error=error@entry=0x7fffffffacf0) at ../expando/parse.c:315
#5  0x0000555555681248 in expando_parse
    (str=<optimized out>, defs=0x5555556abf14, err=err@entry=0x555555749b40)
    at ../expando/expando.c:85
#6  0x000055555568089e in expando_string_set
    (cs=0x55555576ce60, var=0x55555571f700 <MainVars+8672>, cdef=0x55555571f6d0 <MainVars+8624>, value=<optimized out>, err=0x555555749b40) at ../expando/config_type.c:79
#7  0x00005555556897d5 in cs_he_string_set
    (cs=<optimized out>, he=he@entry=0x555555789d00, value=<optimized out>, err=err@entry=0x555555749b40) at ../config/set.c:622
#8  0x000055555568be53 in cs_subset_he_string_set
    (sub=0x55555576e450, he=0x555555789d00, value=<optimized out>, err=0x555555749b40)
    at ../config/subset.c:370
#9  cs_subset_he_string_set
    (sub=0x55555576e450, he=he@entry=0x555555789d00, value=<optimized out>, err=err@entry=0x555555749b40) at ../config/subset.c:364
#10 0x000055555567fc8e in command_set_set
    (name=name@entry=0x555555749520, value=value@entry=0x555555749460, err=err@entry=0x555555749b40) at ../parse/set.c:135
#11 0x0000555555680380 in parse_set
    (buf=0x555555749520, s=0x5555557493a0, data=0, err=0x555555749b40) at ../parse/set.c:615
#12 0x000055555567f6f0 in parse_rc_buffer
    (line=0x5555557493a0, token=0x555555749520, err=err@entry=0x555555749b40)
    at ../parse/rc.c:79
#13 0x000055555567f7fa in parse_rc_buffer
    (line=<optimized out>, token=<optimized out>, err=err@entry=0x555555749b40)
    at ../parse/rc.c:96
#14 0x000055555558659a in source_rc
    (rcfile_path=<optimized out>, err=err@entry=0x555555749b40) at ../commands.c:282
#15 0x00005555555869df in parse_source
    (buf=0x555555749220, s=0x555555749160, data=<optimized out>, err=0x555555749b40)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../commands.c:1087
#16 0x000055555567f6f0 in parse_rc_buffer
    (line=0x555555749160, token=0x555555749220, err=err@entry=0x555555749b40)
    at ../parse/rc.c:79
#17 0x000055555567f7fa in parse_rc_buffer
    (line=<optimized out>, token=<optimized out>, err=err@entry=0x555555749b40)
    at ../parse/rc.c:96
#18 0x000055555558659a in source_rc (rcfile_path=<optimized out>, err=0x555555749b40)
    at ../commands.c:282
#19 0x0000555555598f63 in mutt_init
    (cs=<optimized out>, dlevel=dlevel@entry=0x0, dfile=dfile@entry=0x0, skip_sys_rc=<optimized out>, commands=commands@entry=0x7fffffffd760) at ../init.c:537
#20 0x000055555558133b in main
    (argc=<optimized out>, argv=0x7fffffffdd98, envp=<optimized out>) at ../main.c:855
```

## Steps to Reproduce

Include `set mix_entry_format="%4n %c %-16s %a"` in config. Start neomutt.

## How often does this happen?

- Always, on startup.

## When did it start to happen?

- When I upgraded from `20240425+dfsg-2` to `20241002+dfsg-1`
- Commenting out `set mix_entry_format="%4n %c %-16s %a"` (which is the default value) from my config, avoids the crash.

## NeoMutt Version

This occurred with Debian's `20241002+dfsg-1` version of Neomutt.

```
NeoMutt 20241002
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.10.9-amd64 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.18.0
GnuTLS: 3.8.6
libnotmuch: 5.6.0
PCRE2: 10.42 2022-12-11
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --autocrypt --disable-paths-in-cflags --full-doc --gnutls --gpgme --gsasl --gss --lmdb --lua --lz4 --notmuch --pcre2 --sqlite --tokyocabinet --zlib --zstd

Compilation CFLAGS: -g -O2 -Werror=implicit-function-declaration -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5 -O2

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  +gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +nls +notmuch 
  -openssl +pcre2 +pgp -sasl +smime +sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Debian trixie
* Were you using multiple copies of NeoMutt at once? N/A
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? No

**Comment by flatcap** [comment]
Damn!  Sorry about that.
I could have sworn that deprecated config was handled more centrally.
It wasn't, so the Expando code was getting very confused.

There's a fix in branch [[devel/deprecated]](https://github.com/neomutt/neomutt/tree/devel/deprecated) if you wish to give it a try.

Thanks
